### ISSUE TITLE
Use "instance creation" instead of "instance-creation" for method protocol name

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#1001]
Smalltalk as well as Pharo is using a method protocol/method category "instance creation". This is best practice and common agreement even in other Smalltalk systems. We even have a lint rule and a hint is displayed in the browser to name the tag correctly.

The only classes violating this are the Libgit and Iceberg classes where it was called "instance-creation"
instead of "instance creation"

See 

```Smalltalk
   | violating |
    violating := OrderedCollection new.
    Object allSubclassesDo: [:cls | cls methods do: [:m |
              m category = #'instance-creation' 
                ifTrue: [ violating add: m -> m category ]
            ]
        ].
    violating 
```
in Pharo-7.0+alpha.build.1250
Please change the categories in Iceberg to use "instance creation" too.

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/22462/

**Comment by guillep** [comment]
To appear in next release 1.3

I've used the following script:
```
Object allSubclassesDo: [:cls | cls methods do: [:m |
	m category = #'instance-creation'
		ifTrue: [ m protocol: #'instance creation' ] ] ].
```

I hope that's enough.
