### ISSUE TITLE
Iceberg fails on image comming from CI

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1002]
Today I got an image from a CI and a project already loaded. (I cannot share it :( )

When I tried to launch Iceberg to commit some changes I got an error (see details below).

I don't have much time to dig into the error :( 

Maybe the state of my local repos are wrong but in that case, I would expect a way to fix things instead of a debugger. 

`NotFound: Object not found - no match for id (6defd7f42d0c79619d8d28b83f9175af9188989b)`

```
IceLibgitErrorVisitor>>visitENOTFOUND:
LGit_GIT_ENOTFOUND>>acceptError:
[ :error | error acceptError: (IceLibgitErrorVisitor onContext: self) ] in IceLibgitRepository>>handleLibgitError: in Block: [ :error | error acceptError: (IceLibgitErrorVisit...etc...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
LGit_GIT_ENOTFOUND(Exception)>>signal
LGit_GIT_ENOTFOUND class(LGitCallReturnHandler class)>>signalWith:
LGitReturnCodeEnum>>handleLGitReturnCode
LGitCommit(LGitExternalObject)>>withReturnHandlerDo:
LGitCommit>>lookup
LGitCommit(LGitObject)>>initializeWithId:
LGitCommit class(LGitObject class)>>of:fromId:
LGitCommit class>>of:fromHexString:
[ ^ LGitCommit of: self repositoryHandle fromHexString: self id ] in IceGitCommit>>libgitCommit in Block: [ ^ LGitCommit of: self repositoryHandle fromHexSt...etc...
BlockClosure>>on:do:
IceLibgitRepository>>handleLibgitError:
IceGitCommit>>libgitCommit
IceGitCommit>>fileSystem
IceBasicProjectReader>>canReadProjectFromCommitish:
[ :any | any canReadProjectFromCommitish: anIceCommitish ] in IceProjectReader class>>readProjectFrom: in Block: [ :any | any canReadProjectFromCommitish: anIceCom...etc...
[ :each | 
(aBlock value: each)
	ifTrue: [ ^ foundBlock cull: each ] ] in OrderedCollection(Collection)>>detect:ifFound:ifNone: in Block: [ :each | ...
OrderedCollection>>do:
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
OrderedCollection(Collection)>>detect:
IceProjectReader class>>readProjectFrom:
IceGitCommit>>project
IceBasicProject(IceAbstractProject)>>isDirty
IceWorkingCopy>>isModified
```

**Comment by jecisc** [comment]
Apparently, the problem is that on disk I have local repos that are outdated and Iceberg crash because it can't find the commit present in the image.

**Comment by guillep** [comment]
Yes, this is a known problem. (BTW, let's not say crash, since this can be identified as a VM crash, a SIGSEV and it's not quite the same thing :P)

**Comment by guillep** [comment]
Duplicates #949

**Comment by jecisc** [comment]
In fact, my issue was slightly different that #949 and my case can have a quick fix for P7. 

In my case, the problem is not when we execute a Metacello expression but when I open the interface of Iceberg which has a project at a commit and a directory associated and a git project that does not have the commit. 

In that case we can catch the NotFound and try to fetch.
