### ISSUE TITLE
use displayScaleFactor 

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#1004]
The Iceberg UI should use displayScaleFactor to work better on HiDPI displays or during presentations

**Comment by guillep** [comment]
Can you add more details? I don't know what displayScaleFactor is.

**Comment by pavel-krivanek** [comment]
Since Morphic has no proper possibility to scale on the level of rendered canvas, in Pharo 7 a temporary solution: a setting named displayScaleFactor. Basic UI elements know about it and scale themselves by this factor. It does the scaling of icons too.
But as soon as someone hardcodes the dimension, it should be scaled too.
It is not a nice solution but for now better than nothing. If you set fonts size in settings to some default value /like Large/ them it sets the scaling factor too.
To Pharo 6.1 the compatibility messages that return 1 are already integrated

**Comment by estebanlm** [comment]
yes. 
I do not like it.
But I approve it since we do not have a better solution ATM.
