### ISSUE TITLE
Review update-repo-view: changes tree and diff

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#101]
Should we show the diff to the working copy or to the latest commit? 
Title of the tree is wrong.

**Comment by seandenigris** [comment]
While we're at it, IHMO the diff should be reversed: local repo on the left and working copy on the right. If you commit, it seems logical (to me anyway ha ha) that you are accepting going from what's on the left to what's on the right…

**Comment by estebanlm** [comment]
yes, in general, I scheduled a task to change everything to "left: the old thing, right: the new thing"... problem is I hadn't time yet and is not so obvious all the time :)
but yes... this is annoying not to have clear panel/colors.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. There is a new commit view. All diffs in iceberg now show (old <-> new).
