### ISSUE TITLE
Filter in repository view don't work with capital letters

### ISSUE THREAD

**Issue by gcotelli** [pharo-vcs/iceberg#1041]
Using the Filter... in the repository window if you use capital letters (even if it matches de repository name) the filtered results are empty. Works ok if no capital letters are used.

![icerbergfilterbug](https://user-images.githubusercontent.com/2106744/47570148-c5ba7900-d90b-11e8-90a8-52b61d872ae7.gif)

**Comment by guillep** [comment]
To appear in next version!
