### ISSUE TITLE
Packages starting with lowercase not recognized

### ISSUE THREAD

**Issue by vojtechbalik** [pharo-vcs/iceberg#1043]
I created a new local repository. Then in the package view, I was able to add and commit a package whose name starts with lowercase letter (e.g. 'test').
 
However, after commiting, the package disappears from the package view. In the repository view, I can see that the commit did happen (there's a timestamp, hash, etc. for it), but no changes were made (I cannot see any changes in the diff window). If I push to a remote, looking at the repository (gitlab in this case) I can see that lowercase-starting package is there.

Similar things happen if I clone the repo with such package. The package is not present in the package view, while physically its files are present.

**Comment by vojtechbalik** [comment]
(Tested this on windows and linux 32b and 64b)

**Comment by guillep** [comment]
I can reproduce it in latest dev version.

**Comment by guillep** [comment]
Hmm, somehow the tonel writer is validating that only uppercase directories are packages.

```
isValidPackage: aFileReference 
	
	| aBasename |
	aBasename := aFileReference basename.
		
	^ (aBasename first isLetter
		and: [ aBasename first isUppercase ])
		and: [ aFileReference isDirectory
		and: [ (aFileReference / 'package.st') exists ] ]
```

@estebanlm can you confirm if this is ok? Does Tonel support package names in lowercase?

**Comment by estebanlm** [comment]
well... no, but it may. 
Thing is, Tonel was trying to enforce a certain convention. A convention that may be not true in other smalltalks but in Pharo exists. 

Of course, we can change this if it proves not correct :)

**Comment by guillep** [comment]
To appear in next version
