### ISSUE TITLE
Show a button "View on Github" when creating a PR

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1044]
When a PR is created on github via the github plugin of Iceberg it would be great to have a "View on Github" button. 

Most of the time I got check the PR after opening it. 

In Pharo 7 it is possible to do that with a WebBrowser command. I don't know if it is possible to add a button in a Growl notification.

**Comment by jecisc** [comment]
Apparently, it will be hard to create a button in a growl morph (It is a subclass of TextMorph :'( ).

We can still make it clickable.

**Comment by estebanlm** [comment]
in theory, a TextMorph should allow that. 
and at least, it should allow a link. 

but I wonder if we want that, since it would change the UI : until now, growl messages are just that: messages.

can't we think in another solution?

**Comment by jecisc** [comment]
I was thinking about doing a "NotificationMorph" close to native notifications (you can embed images, buttons, icons, links...). But I gave up because I did not find a way to manage the layout of a morph that is not in a window :P

**Comment by jecisc** [comment]
Merged.
