### ISSUE TITLE
For Pharo 70 iceberg should not be shipped using deprecated class

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1058]
CmdShortcutCommandActivation -> CmdShortcutActivation

**Comment by Ducasse** [comment]
https://pharo.fogbugz.com/f/cases/22612/No-DeprecatedClass-use-Iceberg-Command-use-deprecated-CmdMenuActionContext-something

**Comment by Ducasse** [comment]
I issued a PR 
https://github.com/pharo-vcs/iceberg/pull/1059

**Comment by guillep** [comment]
Already available in latest Iceberg
