### ISSUE TITLE
Iceberg generates incorrect properties file

### ISSUE THREAD

**Issue by JurajKubelka** [pharo-vcs/iceberg#1060]
Please check this PR to understand the issue: https://github.com/Ducasse/Containers-PropertyEnvironment/pull/2

Using the latest Pharo 7 and converting a repository from treefile to Tonel format generates this content: 

```
{
 	#format : #tonel
 }e
 }
```

To convert it, I used Iceberg's menu option "convert to tonel".

I think I did it in:

```
Pharo 7.0.0
Build information: Pharo-7.0.0+alpha.build.1351.sha.f0b4d63e9c67d8b0fa9c68bd86613867d81ad45d (64 Bit)
```

**Comment by guillep** [comment]
Duplicates https://github.com/pharo-vcs/iceberg/pull/1013

This will be integrated in today's release.
