### ISSUE TITLE
'There is no associated repository configured.' warning on right clicking missing repository

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#1068]
It seems this is a side effect of

https://pharo.fogbugz.com/f/cases/22256/History-button-in-the-implementors-window-is-not-working

https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/25/commits/128d71f5adb4b87f76cf244bcc56daa1c73d799d

**Comment by guillep** [comment]
As a workaround, before this is integrated, you can replace

```
IceTipCopyCommitishCommand class>>canBeExecutedInContext: aToolContext
	^ aToolContext item commitId isNotNil
```

by 

```
IceTipCopyCommitishCommand class>>canBeExecutedInContext: aToolContext
	^ aToolContext item shortCommitId isNotNil
```

**Comment by bencoman** [comment]
That workaround worked for me (after I clicked Proceed`d past the error)
