### ISSUE TITLE
The reference to the extra >> Convert refers to an item that does not exist!

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1086]
![screen shot 2018-11-10 at 20 30 39](https://user-images.githubusercontent.com/432549/48305250-9587f280-e527-11e8-9496-6cda534d4f15.png)

**Comment by Ducasse** [comment]
There is no Convert option.

**Comment by Ducasse** [comment]
But the command is in the image. So for my personal use I hacked in the inspector.

**Comment by jecisc** [comment]
I suppose you got the problem with this repo and this commit? 

https://github.com/Ducasse/Containers-UniqueOrdered/tree/dd16d84aa43ce39567222d88a0533f85a8305d38

**Comment by Ducasse** [comment]
Yes. And now I lost all my code. 
So I will have to learn how to remove the latest version or reload a previous one :(
What is the problem? the use of u as startup letter?

**Comment by jecisc** [comment]
@Ducasse The repository is already in the Tonel format. This is the problem ;)

**Comment by Ducasse** [comment]
Ah Ok but this is strange then because I got something telling me that it was in filetree and that it could  be problem. 
Probably when I added the metadata. 
I will convert all my repo so I will see if I reproduce it.
