### ISSUE TITLE
Gitlab integration should manage non default port

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1099]
It would be great to be able to give a non default ssh port in a gitlab declaration.

I would like to be able to use a code like this:

```Smalltalk
Metacello new
	baseline: 'Bazard';
	repository: 'gitlab://gitlab.ferlicot.fr:3456:Projet/Bazard/src';
	load.
```

Or

```Smalltalk
Metacello new
	baseline: 'Bazard';
	repository: 'gitlab://gitlab.ferlicot.fr:3456/Projet/Bazard/src';
	load.
```

For than we need to update MCGitlabRepository class>>parseLocation:version: to extract the port then MCGitlabRepository>>scpUrl and MCGitlabRepository>>httpsUrl to use the port to get something like `ssh://git@gitlab.ferlicot.fr:3456/Projet/Bazard.git` instead of `git@gitlab.ferlicot.fr/Projet/Bazard.git`

**Comment by gcotelli** [comment]
@jecisc can you copy and paste here the SSH and HTTPS urls from the project page in Gitlab. I don't know it the port applies only to SSH url, or both.

**Comment by jecisc** [comment]
@gcotelli I was tired and wrote HTTPS but the ssh port does not impact the HTTPS scheme I guess. I did a PR to Pharo and Iceberg to add the support already :)

https://github.com/pharo-project/pharo/pull/2041
https://github.com/pharo-vcs/iceberg/pull/1101

**Comment by gcotelli** [comment]
Nice, all the parsing in this hierarchy needs some love. I don't know if there's some case when the HTTPS url will include a port, in that case we will need some way to specify it and not confuse it with the SSH one. But for now the changes looks good to me.

**Comment by jecisc** [comment]
I agree with you. But I'll let that to Cargo :P

**Comment by guillep** [comment]
Hi both :) What's the action to take here? I've relaunched the PR builds.
If that's ok, can I integrate this?

**Comment by gcotelli** [comment]
I cannot test it but for me the changes are Ok.
