### ISSUE TITLE
Entering an issue in create a branch raises a DNU

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1105]
When I entered a number in the create new branch from issue I get a DNU the first type I do it. This is on latest version of 

Image
-----
/Users/ducasse/Documents/Pharo/images/Pharo70-YourselfComment/Pharo70-YourselfComment.image
Pharo7.0.0rc1
Build information: Pharo-7.0.0+rc1.build.44.sha.d3be1c018447fa5f7ba666cea7aff396f36d4309 (32 Bit)
Unnamed

**Comment by guillep** [comment]
I cannot reproduce it with the pharo repository :/

I've tried by:
 - cloning using the github panel
 - cloning using the url panel
 - trying to create an issue from github issue
 - trying to create an issue from fogbugz
 - different combinations of the others

There is something else that may trigger the issue, so if you have some idea...

**Comment by guillep** [comment]
I've been able to reproduce it in a project that was in detached head (in a tag)

**Comment by guillep** [comment]
The merged PR should fix this.
