### ISSUE TITLE
Moving a class between packages not properly catched

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#1106]
Scenario:
=======
- Pharo 7.0.0 Build information: Pharo-7.0.0+rc1.build.49.sha.389dabb14e2e02521407af34098afeab9772d903 (64 Bit)

- I move the class FileDoesNotExist from  "FileSystem-Core" to "Deprecated70-FileSystem" by dragging it from one calypso browser to the other

- when I look in Iceberg for the change to commit I only see a single modification in package
  "Deprecated70" (the addition of the class there) but no modification in package "FileSystem-Core"
  as removal

**Comment by astares** [comment]
Pharo bug 

https://pharo.fogbugz.com/f/cases/22798/Moving-a-class-between-packages-not-properly-catched

**Comment by guillep** [comment]
It looks like a problem in how the class repackaged announcement is interpreted
