### ISSUE TITLE
fix for after issue 22833 (Preparation for removal of PluggableTextMorph*)

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1118]
Alain fixed a lot of points related to the PluggableTextMorph and old friends (we should be able to remove them). This fix should be integrated right after 22833 gets in.

**Comment by jecisc** [comment]
We should be careful to keep P6.1 compatibility until Pharo 8. But we can probably just copy Alain's new classes to the Pharo 6 package.

**Comment by Ducasse** [comment]
Yes but I think that this one should be able to work in P6 (I should ask alain).
