### ISSUE TITLE
"Please fetch a valid issue number" on a valid issue number

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1133]
When I tried to get 22845 I got an error telling me that the issue number was not valid
while it is. 
https://pharo.fogbugz.com/f/cases/22845/Recent-changes-on-Rubric-are-not-dark-theme-friendly

**Comment by Ducasse** [comment]
Apparently this failed because I already got a branch with the same name.

**Comment by jecisc** [comment]
Since we now use Github as issue tracker we can probably close. @guillep
