### ISSUE TITLE
Problems including local repositories

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#114]
If local repository has same origin as an existing Metacello github:// repository, it might fail when trying to get latest commit from the Metacello repository, which if does not provide (and maybe does not make sense to ask for it because I am not sure if the loaded version came from there).

So at minimum we should handle the case when metacello does not provide a significant commit id, but maybe also see if it makes sense to ask metacello for it.

**Comment by dalehenrich** [comment]
@npasserini in case it matters, I have written some extensions for FileTree that allow Metacello to track the loade SHA (I'm assuming this is what you are talking about here?), but I've only implemented them for GemStone, since at the time noone else was really using git and Metacello seriously :) ...

If you want I can try integrating then into Pharo5.0 and Pharo6.0 versions of FileTree (with the help of @ThierryGoubier

**Comment by npasserini** [comment]
@dalehenrich I think I can get the sha of the loaded commit, I am getting it from the directory name, is that right?

**Comment by dalehenrich** [comment]
@npasserini for tODE, I pick up the sha of the loaded commit by asking the project registration for its currentVersionString (MetacelloProjectRegistration>>currentVersionString). MetacelloProjectRegistration>>currentVersionString sends the message #repositoryVersionString to the projectSpec (MetacelloMCBaselineOfProjectSpec>>repositoryVersionString), which figures out the repository that the baseline was loaded from and then sends #repositoryVersionString to the repository:

```
MCRepository>>repositoryVersionString
 MCFileTreeRepository>>repositoryVersionString
  MCGitBasedNetworkRepository>>repositoryVersionString
```

For MCFileTreeRepository:

```Smalltalk
repositoryVersionString
  "extract a version string from the repository ... if possible"

  (MetacelloPlatform current gitCommitShaFor: self directory fullName)
    ifNotNil: [ :sha | ^ sha ].
  ^ super repositoryVersionString
```

#gitCommitShaFor: is only implemented for GemStone at the moment --- pharo has a stub implementation. And this is the spot where GitFileTree and Iceberg can get into the act ...

Up until  #gitCommitShaFor: all of the methods should already exist in Metacello and FileTree ... if they don't I want to arrange to implement them ... now I'm not sure how you are going to be handling Iceberg repositories, but unless you are using FileTree, we'll have to teach Metacello how to figure out the repository --- for locking and loading things from Iceberg ...

For the github repos, look at [MCGitBasedNetworkRepository>>repositoryVersionString](https://github.com/dalehenrich/metacello-work/blob/master/repository/Metacello-GitBasedRepository.package/MCGitBasedNetworkRepository.class/instance/repositoryVersionString.st) you'll see how it is done. Youshould probably just use MCGitBasedNetworkRepository>>repositoryVersionString...

**Comment by npasserini** [comment]
Hi @dalehenrich I am using MCRepository>>repositoryVersionString on a Metacello repository that was created using a tag (github://npasserini/pharo-git-test:1.2.3) and what I get is '975bc89' which does not seem to be a commit ID but a tag ID. 

Is that on purpose or should I post an issue?

**Comment by dalehenrich** [comment]
That's interesting, that looks like a bug in `MCGitBasedNetworkRepository>>projectVersion:`:

```
projectVersion: aString
  "Important that projectVersion be set AFTER projectPath, as projectPath needed for resolving projectVersionPattern"

  | x |
  aString ifNil: [ projectVersion := aString.
      ^ self ].
  (x := aString findDelimiters: {$#.
      $*.
      $?} startingAt: 1) <= aString size
    ifTrue: [ self resolveProjectVersionPattern: aString ]
    ifFalse: [ projectVersion := aString ]
```

When a pattern is supplied, and MCGitBasedNetworkRepository>>resolveProjectVersionPattern: is called, the tag list is downloaded and the sha is picked out of the list ... when non-tag commitish is used the zIp file produced has the short form commit SHA embedded in the download file name, but it does indeed look like when a tag is used, the zip file produced is the SHA of the tag is used instead ... a bit surprising and while the fix would be to unconditionally grab the tag list ... there are limits on how often you can hit api.github.com ... oh well, a bug is a bug:) ... Thanks for reporting this!

**Comment by npasserini** [comment]
Do you want me to create an issue?

2016-11-03 18:30 GMT+01:00 Dale Henrichs <notifications@github.com>:

**Comment by dalehenrich** [comment]
Yes please!
