### ISSUE TITLE
Iceberg cannot be updated in Pharo 6.1

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-vcs/iceberg#1140]
Iceberg cannot be updated in Pharo 6.1 because it cannot load Commander:
`Could not resolve: BaselineOfCommander [BaselineOfCommander] in ...`

Probably related to issue #1124

**Comment by guillep** [comment]
We should update the update script. Since some of Iceberg dependencies are now in tonel format and the update script unloads tonel first, so tonel needs to be reloaded before.
