### ISSUE TITLE
Feature: Reset

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1174]
Today I did a dumb commit on one of my branch to test some things and now I want to reset this commit. 

Currently, in Iceberg, I can checkout the previous commit of the branch, but I cannot reset my branch to this commit. It would be cool to be able to do it in Iceberg instead of command line.

**Comment by guillep** [comment]
As a workaround you can inspect the repository and do the equivalent of a `reset --hard HEAD~1`:

```
self branch commit: self branch commit parent.
```
