### ISSUE TITLE
Fix unused ivars in some iceberg classes

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#1182]
IceChangeImporter
IceMCPackageImporter
IceNode
IceOperation
IceSavedPackageVersion

have unused ivars !!!

**Comment by jecisc** [comment]
Hi Torsten,

There is already an issue and a PR.

https://github.com/pharo-vcs/iceberg/pull/1173

https://github.com/pharo-vcs/iceberg/issues/1172

**Comment by astares** [comment]
OK, so we close this one
