### ISSUE TITLE
The repository branch column is always too small (and possibly should be 3rd column)

### ISSUE THREAD

**Issue by macta** [pharo-vcs/iceberg#1188]
The repositories window shows the branch column second in a fixed width that is inevitably too small - whereas the status column could be fixed width but is in the 3rd variable column. This means that you find it hard to read your branch name (see photo).

It would be handy if status was the second column (and about the same size as the name column) and the branch column in the 3 position and variable width (or the same width as the remaining windows).

![image](https://user-images.githubusercontent.com/5553623/53112445-1eef8d80-3537-11e9-98ca-15027c79e73f.png)

**Comment by guillep** [comment]
I'm checking this one to warm up. In my image with several projects installed I have:

![image](https://user-images.githubusercontent.com/708322/53167040-1ea6cf00-35d7-11e9-859d-a9bc30ea29ef.png)

Which has a slightly larger status column. Checking it a bit further, the longest string we may have in that column seems to be: `Uncommited changes. {1} incoming. {1} not published`. But maybe in case the user wants to adjust it for that special case he could just resize the column?

**Comment by guillep** [comment]
And that would give us...

![image](https://user-images.githubusercontent.com/708322/53167304-da67fe80-35d7-11e9-9c64-663b7f522efb.png)

**Comment by macta** [comment]
From the pictures this looks perfect - how do I easily try this out to test it - is it just simply to take my contribution image and load in that branch? (I'm guessing so and will try it)

**Comment by guillep** [comment]
Actually, just pulling from the dev-1.0 will be enough. I've already integrated this 2 secs ago.
