### ISSUE TITLE
cannot commit a method

### ISSUE THREAD

**Issue by hogoww** [pharo-vcs/iceberg#1222]
Not sure if this belongs here on the Pharo repository.
Discovered on a moose 7 64 bit, and reproduced it on pharo7 stable 64 bit. (I doubt it's system related).

Reproducible bug with the following.
-Create a random Package/Class
-Add the package to iceberg (commit it once before anything isn't required)
-add a method and finish its name by a dot : aSelector. 

Pharo will ignore the dot (as seen in the screenshot) but Iceberg will keep this method in the diff, and commit it every time.

![iceberg](https://user-images.githubusercontent.com/21278554/55166250-10684780-516f-11e9-9952-90e1f96590af.png)

Pierre.

**Comment by hogoww** [comment]
Careful when replicating it, it's bugged an image for me, when trying to open it again.
(I'm not sure it's related though)

 pharo: /home/travis/build/OpenSmalltalk/opensmalltalk-vm/build.linux64x64/third-party/libgit2-0.25.1/src/global.c:322: git__global_state: Assertion `git_atomic_get(&git__n_inits) > 0' failed.
bash: line 1:  6404 Aborted                 (core dumped) "/home/aHome/Pharo/vms/70-x64/pharo" "/home/aHome/Pharo/images/test iceberg bug/test iceberg bug.image"

**Comment by estebanlm** [comment]
thing is 

```Smalltalk
aSelector.
    ^ 42
```

is invalid format (the dot at the end).
Or course, we should send an error message, but the fact is this method is invalid :)

**Comment by hogoww** [comment]
I agree, but maybe that should be enforced by Pharo compiler.
 (there's a similar problem with packages)

I may be mistaken, but it's a bug I felt I already saw. And this is a way to reproduce it.

**Comment by guillep** [comment]
See https://github.com/pharo-vcs/tonel/pull/77 and https://github.com/pharo-vcs/tonel/issues/76

**Comment by jecisc** [comment]
@hogoww This is working for me with Iceberg dev-1.0

Can you confirm and close the issue if it is fixed? thanks.
