### ISSUE TITLE
P7: Using merge use incoming gives walkback: doesNotUnderstand: #visitConflictingOperation: IceConflictingOperation>>accept: 

### ISSUE THREAD

**Issue by macta** [pharo-vcs/iceberg#1225]
I had a merge conflict when pushing pulled changes to my fork (I was on master, did a pull from upstream and then did a push to my fork). I got a merge conflict error - and I chose to just use incoming (although it wasn't clear to me if incoming meant my change on master - which was the intent - I right click on the error and picked use incoming). When I clicked merge to procede I got a walkback (below).

My iceberg is then hosed after this (I get red morphs, and it says "instance of array dnu #project)

IceGitWorkingCopyUpdateVisitor(Object)>>doesNotUnderstand: #visitConflictingOperation:
IceConflictingOperation>>accept:
[ anIceNode value accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ anIceNode value accept: self ]
BlockClosure>>ensure:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>withNode:do:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
[ :each | each accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf: in Block: [ :each | each accept: self ]
Array(SequenceableCollection)>>do:
IceNode>>childrenDo:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf:
IceGitWorkingCopyUpdateVisitor>>visitRootDefinition:
IceRootDefinition>>accept:
IceGitWorkingCopyUpdateVisitor>>visitNoModification:
IceNoModification>>accept:
IceGitWorkingCopyUpdateVisitor>>visitNonConflictingOperation:
IceNonConflictingOperation>>accept:
[ anIceNode value accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ anIceNode value accept: self ]
BlockClosure>>ensure:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>withNode:do:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
IceGitIndex>>updateDiskWorkingCopy:
IceWorkingCopy>>commitChanges:withMessage:force:
IceMerge>>updateHead
IceMerge>>execute
IceAttachedSingleVersionWorkingCopy>>mergeCommit:
IceWorkingCopy>>mergeCommit:
IceGitLocalBranch(IceLocalBranch)>>pullFrom:
IcePullRemoteCommand>>execute

**Comment by guillep** [comment]
Hi @macta , Would it be too complicated to provide the two commitishs that you were trying to merge?

**Comment by macta** [comment]
@guillep - not sure if its too late (as I had to revert my fork commit to get past this issue) - however let me try to give the info:

my fork repo was this:https://github.com/macta/pharo-exercism/commit/e43fdae6d061a27c3de29e62ef1b3b2c280e2fc5 (I think - or possibly the one after: https://github.com/macta/pharo-exercism/commit/72a8f736bfa4cb7b8d4c08c81f398ae6df4d336b)

My upstream was this: https://github.com/exercism/pharo-smalltalk/commit/72a8f736bfa4cb7b8d4c08c81f398ae6df4d336b . (I think - or posssibly the one before)

You can see in my fork that I then had to a revert: https://github.com/macta/pharo-exercism/commit/d89a286ad4f6eefe4e2a3176cc4291937cb826ef and a merge  https://github.com/macta/pharo-exercism/commit/c61af606150350cf13e8a754236eeabb9d68edd0 to get iceberg to work.

the file in conflict was the config.json file in that merge - and I tried to use the "load/use incoming" option in the merge browser - but it barfed as in the exception.

**Comment by macta** [comment]
I hit this one again - I had a (longer running) branch that I was working on, I committed and then had to merge master with the main repo and after it showed me the list of changes , it then gave this error.

My branch was macta/pharo-exercism (improved-mentor-solution-browser) commitish: 66ad19ddc4e1a4f91a2a8932f03643c5e69d3a7a and I was merging with (exercism/pharo-smalltalk - master) id:
d1fc39e670263a5fab922cc29e5234a790ce1256

**Comment by macta** [comment]
I've tried this in a fresh image and get the same results - it also kills my iceberg

**Comment by guillep** [comment]
I've been playing around with the posted commits but I cannot find a way to have a merge with contflicts... I'll try a bit more, but otherwise I think I'll wait to have another reproducible case...

**Comment by guillep** [comment]
Finally manage to reproduce it (by hunch) and built a test case with the same exception. To appear in the next release :)
