### ISSUE TITLE
Repositories are cloned in the wrong image folder

### ISSUE THREAD

**Issue by dupriezt** [pharo-vcs/iceberg#1226]
When cloning github repositories with iceberg in recent pharo 8 images, the repo is cloned at an incorrect path.
Instead of cloning inside the current image's folder, iceberg clones in the folder of another image: "Pharo 8.0 - 64bit (development version, latest)-spdbg-01". Even after deleting this folder, cloning a repo with iceberg in **any** recent pharo 8 image will recreate this **exact same** folder to put the cloned files in it.

This also means that if I clone a repo in an image, then attempt to clone the same repo in another image, iceberg will throw an exception saying that the file already exists ("you already have an iceberg repository at ...") because the iceberg of both images try to clone the repo at the same place: this "Pharo 8.0 - 64bit (development version, latest)-spdbg-01" folder.

This problem is not present in fresh pharo 7 images or old pharo 8 images. It's only present in recent pharo 8 images.

Ubuntu 18.04

Steps:
- fresh pharo 8 image (through pharo launcher)
- in iceberg: clone remote repository: "git@github.com:dupriezt/Spec-Debugger.git"
- this creates a "Pharo 8.0 - 64bit (development version, latest)-spdbg-01" folder in ~/Pharo/images/ to put the "iceberg" folder
- fresh pharo 8 image (through pharo launcher)
- In iceberg: clone remote repository: the same repository -> Error "You already have an Iceberg repository at [...]/Pharo 8.0 - 64bit (development version, latest)-spdbg-01/pharo-local/iceberg/Spec-Debugger"

**Comment by astares** [comment]
There are settings for the directories in Iceberg. Just open WorldMenu -> Pharo -> Settings.

There you will find a Tools - Software configuration management - Iceberg - Default Code subdirectory
You can retrieve it using 

```Smalltalk
IceLibgitRepository defaultCodeSubdirectory
```
I guess when it is empty it should use the current cache directory. But I'm not sure.

Also there is a setting "Share repositories between images" in the settings browser:

```Smalltalk
IceLibgitRepository shareRepositoriesBetweenImages
```

if selected this should use the setting "Location for shared repositories"

```Smalltalk
IceLibgitRepository sharedRepositoriesLocationString
```

Maybe you enabled it manually - or in a startup script.

**Comment by guillep** [comment]
I've also seen before this bug, related to the fact that you have "stored" your settings. Can you check that:
 - your settings do not contain the bad path
 - launching the image without settings does it fix the problem?

**Comment by dupriezt** [comment]
The "Share repositories between images" setting is off. The "Location for share repository" setting is worth "/home/tdupriez/iceberg", so that's not even the bogus folder iceberg keeps cloning into.

I don't know how to launch an image without settings...

**Comment by fuhrmanator** [comment]
I remember now, why I did "Store settings" a second time and got bitten again by this bug -- I wanted my SSH keys to be visible to all (new) images. 

I think @jecisc has a better way to manage settings with scripts, since this bug is really painful.

**Comment by dupriezt** [comment]
*Launching the image without settings does not solve the issue.*
Well, I tried this workaround again, and now it works, so at least there's that.

**Comment by guillep** [comment]
This is not necessarily an Iceberg bug but a Pharo bug.
Iceberg calculates the directory where it will clone using Pharo's local directory.

```
FileLocator localDirectory resolve
```

The problem is that going to settings, and clicking on "Store settings" will store the local directory of the current image and make it the local directory of all other images loading settings at startup.

To reproduce:
 - create an image A with Pharo Launcher
 - Go to settings and click on Store Settings
 - close image A and create a new image B
 - then `FileLocator localDirectory resolve` will wrongly resolve to image A's path.

To workaround this, people can launch images without settings, for example, using the launcher's second option:

![](https://cdn.discordapp.com/attachments/345132530585829377/565807653423415296/unknown.png)
