### ISSUE TITLE
P7: Merging my branch to master gives: "Instance of IceGitWorkingCopyUpdateVisitor did not understand #remoteFileReferenceInPath:"

### ISSUE THREAD

**Issue by macta** [pharo-vcs/iceberg#1229]
I have been working on a branch in my fork (for a few days) and there have been commits to the main repository.

I have now committed my work to my branch and gone to merge with upstream/master and I get this walkback:

Instance of IceGitWorkingCopyUpdateVisitor did not understand #remoteFileReferenceInPath:

IceGitWorkingCopyUpdateVisitor(Object)>>doesNotUnderstand: #remoteFileReferenceInPath:
IceDirectoryDefinition(IceFileSystemDefinition)>>removeFrom:
IceGitWorkingCopyUpdateVisitor>>visitRemoval:
IceRemoval>>accept:
IceGitWorkingCopyUpdateVisitor>>visitNonConflictingOperation:
IceNonConflictingOperation>>accept:
[ anIceNode value accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ anIceNode value accept: self ]
BlockClosure>>ensure:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>withNode:do:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
[ :each | each accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf: in Block: [ :each | each accept: self ]
Array(SequenceableCollection)>>do:
IceNode>>childrenDo:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf:
IceGitWorkingCopyUpdateVisitor>>visitDirectoryDefinition:
IceDirectoryDefinition>>accept:
IceGitWorkingCopyUpdateVisitor>>visitNoModification:
IceNoModification>>accept:
IceGitWorkingCopyUpdateVisitor>>visitNonConflictingOperation:
IceNonConflictingOperation>>accept:
[ anIceNode value accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode: in Block: [ anIceNode value accept: self ]
BlockClosure>>ensure:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>withNode:do:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitTreeNode:
IceNode>>accept:
[ :each | each accept: self ] in IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf: in Block: [ :each | each accept: self ]
Array(SequenceableCollection)>>do:
IceNode>>childrenDo:
IceGitWorkingCopyUpdateVisitor(IceTreeVisitor)>>visitChildrenOf:

**Comment by macta** [comment]
@guillep I thought this was associate with a different issue, but in retesting I realised its a new issue. 

My branch was macta/pharo-exercism (improved-mentor-solution-browser) commitish: 66ad19ddc4e1a4f91a2a8932f03643c5e69d3a7a and I was merging with (exercism/pharo-smalltalk - master) id:
d1fc39e670263a5fab922cc29e5234a790ce1256

**Comment by guillep** [comment]
I could reproduce it :) I'm working on it.

**Comment by macta** [comment]
Sounds promising - I was going to upload some more photos. Interestingly, with your patch it freezes my image for 2-3 mins when I see it re-ocuuring (possibly some sort of deadlock?) and then all my desperate clicks get replayed with Windows flying everywhere. Interestingly “cmd .”
Does nothing and you have to patiently wait until it comes back. When it did, I get this reoccurrence every 10 mins or so. I have about 15 browsers open (and I wonder if Mirage rendering thumbnails makes it happen more obviously?)

**Comment by macta** [comment]
@guillep - not sure if recent fixes have sorted this one, but is a real pain?

After your guidance about using merge to catchup my branch with master, this walkback keeps hitting me, making iceberg rather unhelpful. It's essential to save your image before doing any kind of merge (as this error destroys it), and they you have to resort the the command line or source tree.

I can recreate this issue as follows:

If I load the the branch: "issue-287" from: https://github.com/carlotxra/pharo-smalltalk.git and then merge with exercism/master (8711a8e5eee14a434b07711facbbb4edd5bc8e12) i get this error.
