### ISSUE TITLE
Cannot cancel to checkout a branch in P8 latest

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1236]
![Screen Shot 2019-05-16 at 20 51 28](https://user-images.githubusercontent.com/432549/57879333-85c1d180-781c-11e9-9b51-25aee12f134e.png)

**Comment by jecisc** [comment]
I got the same issue in the latest Pharo 8.

Iceberg version: version 1.7.0

**Comment by Ducasse** [comment]
is this fixed?

**Comment by Ducasse** [comment]
Yes I checked so I close it.
