### ISSUE TITLE
(Pharo 8.0.0) what if I don't want to `Accept` ...

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/iceberg#1240]
How do I escape from this window without accepting?
![image](https://user-images.githubusercontent.com/623951/58292840-d8990d00-7d77-11e9-95a2-518009aa9633.png)

**Comment by dalehenrich** [comment]
Most dialog boxes in the known universe have a cancel button:) I must just be old school:)

**Comment by jecisc** [comment]
Hi Dale,

This is a known bug. We are refactoring the Spec GUI framework in Pharo and currently the « cancel » button vanished from the Iceberg’s modals, so the only way now is to use Halos to close the windows (cmd/ctrl + alt + click on the morph). 
We’ll soon take a look at it to fix this problem. 
Thank you for the report.

**Comment by dalehenrich** [comment]
Oh good:) If it's a known bug, I'll close this puppy ...
