### ISSUE TITLE
Fresh Pharo 7 should  default checkout matching branch not latest Pharo 8

### ISSUE THREAD

**Issue by bencoman** [pharo-vcs/iceberg#1246]
When launching a fresh Pharo 7 image then...
"pharo" repository > repair repository > clone again this repository
         Owner name: pharo-project
         Project name: pharo

It is in a detached state since it checks out the latest Pharo 8 branc
while the Image is Pharo 7 code.  The image **should** remember which branch is it
and be able to default check out that branch during a repair.

For example, the fix is just to manually check out the matching branch. 
![Pharo7-Iceberg-default-detached-branch](https://user-images.githubusercontent.com/1713447/58646925-08787f80-8339-11e9-9cff-00bff430d28f.gif)
Can't that be done automatically?

**Comment by jecisc** [comment]
@bencoman This happen because when you clone a project, by default it will clone the branch the is declared as the default branch for the project on github. 

If you clone Pharo in command line without any option, it will also be Pharo 8 that will be checkout.

**Comment by bencoman** [comment]
That makes sense as default behaviour for a first pass at it.  However the Pharo Image should have additional information about which branch or commit it is associated with, so it is not exactly like completely fresh clone to an empty folder.  An analogy would be a scenario where I have some cloned repo on my machine and have a particular branch checked out, then I zip up just the `.git` folder and send it to you.  You unzip that to an empty folder and then do just `git reset` and your files are then an exact duplicate of mine.  

That works because the `.git` folder held the information about which branch was checked out.  The Pharo image should be able to carry the same information.

**Comment by bencoman** [comment]
On a related note, perhaps I miss something, but if I have an old nightly image I worked in a month ago, I find it hard to determine from in the Image which commit its code is based off.  It would be useful that when a nightly build is first run, it does a `git checkout -b $BUILDNUMBER $COMMIT` to create a local-only branch for its build number.  That then provides an easy reference within Iceberg of which commit a build is based off, and an easy point to return to.

**Comment by MarcusDenker** [comment]
I guess this is now so old that it can be closed
