### ISSUE TITLE
Cannot change class that have an inst var of the same name as a class inst var 

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1257]
The problem arises if you try to rename a class that has a class inst var of the same name as an inst var.

While trying to commit, you will pass by the method MCClassDefinition>>#initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp: but instead of getting an array of inst var names, you will get a string.

**Comment by guillep** [comment]
Fixed upstream. See comment in #1258
