### ISSUE TITLE
HTTP remote type

### ISSUE THREAD

**Issue by gcotelli** [pharo-vcs/iceberg#1260]
Sometimes you want to access a remote using plain HTTP and not HTTPS, for example for self-hosted instances. 
In that case you need something like a HTTP remote type.

**Comment by gcotelli** [comment]
The changes should be pretty straighforward:

```
MCGitBasedNetworkRepository>>#httpUrl
	^ self httpsUrl copyReplaceAll: 'https://' with: 'http://'
MCGitBasedNetworkRepository>>#httpsUrl
       self subclassResponsibility
```
and changing `Iceberg class>>#settingsOn:` to include `('HTTP (http://github.com/<username>/<project>.git)'	-> #httpUrl)` as an option in the array.

I couldn't figure out how to use Iceberg to contribute to Iceberg. The Pharo 8 version is showing a lot of deprecation warnings and I cannot update the Pharo 7 version to the latests dev branch.

**Comment by astares** [comment]
@gc#  The deprecations are due to Spec transition. You can just ignore them. 

It would be good to open an issue on Iceberg repo for this (https://github.com/pharo-vcs/iceberg)

**Comment by guillep** [comment]
Fixed upstream
