### ISSUE TITLE
Right click on a commit in the repository triggers an error: DNU IceTipHistoryContext >> selectedBranch

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-vcs/iceberg#1268]
Fueled stack here:
[Debugger-Stack-IceTipHistoryContext-2019-07-12-115038.zip](https://github.com/pharo-vcs/iceberg/files/3385943/Debugger-Stack-IceTipHistoryContext-2019-07-12-115038.zip)

**Comment by MarcusDenker** [comment]
This seems to be working in the latest version. (there is no class IceTipHistoryContext anymore)
