### ISSUE TITLE
ClyCommitMCPackageCommand>>#execute works incorrectly

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#1316]
Version: v1.6.2

In the method ClyCommitMCPackageCommand>>#execute, the checks `targetRepo isDetached` and `targetRepo hasUnbornProject` are wrong because the `targetRepo` here is a `IceLibgitRepository`, not its model.

You can simulate it with the code like:
```smalltalk
repos := IceRepository registry select: [ :repo | {'APart Pharo' asPackage} anySatisfy: [ :each | repo includesPackageNamed: each name ] ].

targetRepo := repos size = 1 ifTrue: [ repos first ] ifFalse: [ UIManager default chooseFrom: (repos collect: #name) values: repos title: 'Choose repository' ].

targetRepo isDetached.
```

To Richard, the error about MNU #isDetached appeared when he tried to pull, did cancel on warning on uncommitted changes and then tried to commit them via Iceberg.

**Comment by cdlm** [comment]
Just got it, it killed the image too.

**Comment by guillep** [comment]
This is not an iceberg issue. It's a calypso issue that is wrongly using an (also private and undocumented) API.
