### ISSUE TITLE
Remove DateAndTime >> asStringYMDHM from Iceberg in Pharo 8

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#1322]
Because it is been integrated into base package: https://github.com/pharo-project/pharo/pull/4963

**Comment by MarcusDenker** [comment]
this gas been merged and thus the issue can be closed (but I can not close it)

**Comment by MarcusDenker** [comment]
Hmm... no. crosscutting changes are evil. in Pharo9, the method is still an extension method of Iceberg
