### ISSUE TITLE
Odd Error when using Metacello

### ISSUE THREAD

**Issue by bergel** [pharo-vcs/iceberg#1326]
In a new pharo 8 image 64 bits (installed using Launcher), simply evaluating:
```Smalltalk
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3';
    load.
```
produces the error: `LGit_GIT_ERROR: Failed to connect to github.com: Interrupted system call`
<img width="936" alt="Screen Shot 2019-11-12 at 23 36 03" src="https://user-images.githubusercontent.com/393742/68728358-e6508200-05a5-11ea-9e5e-aaad1c49dd98.png">

I am under Catalina OSX

**Comment by olekscode** [comment]
Just to give more info: I had the same error yesterday on macOS Mojave (Pharo 8, 64-bit, trying to load Roassal3). I saw this issue: https://github.com/pharo-project/pharo/issues/2585 so I tried again several times and it didn't help. But when I closed and deleted an image, deleted several other images and emptied trash (in case there's not enough memory on my machine), everything worked fine.

I think it is a very annoying bug :(

**Comment by SergeStinckwich** [comment]
I have the same error now on:
```Smalltalk
Metacello new
	onWarningLog;
	repository: 'github://cormas/cormas/repository';
	baseline: 'Cormas';
	load.
```

**Comment by SergeStinckwich** [comment]
Error still there for time to time ... An explanation ?

**Comment by SabineMa** [comment]
same here.

**Comment by SergeStinckwich** [comment]
@guillep is working on a new libgit 1.0 plugin that might solve this issue hopefully.

**Comment by tinchodias** [comment]
Did anybody have the issue again in Pharo 9 in last... 6 months?
Personally, don't remember to see it again.

IIUC, @SergeStinckwich refers to https://github.com/pharo-vcs/libgit2-pharo-bindings/releases/tag/v2.0.0
released by May/2020, and announced later in pharo-dev list with subject "[Pharo-dev] [ANN] Libgit 1.0.0 in Pharo 9".

**Comment by bergel** [comment]
I think this error does not exist in the last version of Pharo
