### ISSUE TITLE
DNU when trying to commit from Calypso

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#1331]
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1058.sha.6e95be08d3ad423a200a157f8f7f4689ab322d9a (64 Bit)

With this image, when I try to save current changes by typing cmd+S on a class of the project,
I get a DNU: Instance of IceLibgitRepository did not understand #isDetached.
It works fine when using Iceberg UI to open the commit window.

IceLibgitRepository(Object)>>doesNotUnderstand: #isDetached
ClyCommitMCPackageCommand>>execute
ClyGlobalContextOfFullBrowser(ClySystemBrowserContext)>>executeCommand:by:
[ 
self prepareCommandForExecution.
context executeCommand: command by: self.
self applyCommandResult ] in CmdCommandActivator>>executeCommand in Block: [ ...
BlockClosure>>on:do:
CmdCommandActivator>>executeCommand
CmdShortcutActivation>>tryExecuteCommandInContext:byEvents:
[ :shortcut | 
executed := shortcut
	            tryExecuteCommandInContext: context
	            byEvents: anEventBuffer.
executed ifTrue: [ ^ self ] ] in CmdKMDispatcher>>dispatch: in Block: [ :shortcut | ...
SortedCollection(SequenceableCollection)>>select:thenDo:
CmdShortcutActivation class(ClassAnnotation class)>>visibleInstancesInContext:do:
CmdKMDispatcher>>dispatch:
KMTarget>>dispatch:
[ :targetToDispatch | 
targetToDispatch dispatch: KMBuffer uniqueInstance buffer copy.
aKeyboardEvent wasHandled ifTrue: [ ^ self ] ] in KMDispatchChain>>dispatch: in Block: [ :targetToDispatch | ...
KMDispatchChain>>do:
KMDispatchChain>>dispatch:
KMDispatcher>>dispatchKeystroke:
FTTableMorph(Morph)>>dispatchKeystrokeForEvent:
FTTableMorph(Morph)>>handleKeystrokeWithKeymappings:
KMShortcutHandler>>handleKeystroke:inMorph:
FTTableMorph(Morph)>>handleKeystroke:
KeyboardEvent>>sentTo:
FTTableMorph(Morph)>>handleEvent:
FTTableMorph(Morph)>>handleFocusEvent:
[ 
ActiveHand := self.
ActiveEvent := anEvent.
result := focusHolder handleFocusEvent:
	          (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear: in Block: [ ...
BlockClosure>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendKeyboardEvent:
HandMorph>>handleEvent:

**Comment by Peter-H-Meadows** [comment]
I'm getting the same thing in Pharo8.0.0+build.1128.sha.9f6475d88dda7d83acdeeda794df35d304cf620d (64 Bit).
It seems to work OK when I comment out the checks for targetRepo isMissing or: [ targetRepo isCodeMissing or: [ targetRepo isDetached or: [ targetRepo hasUnbornProject ] ] ]

**Comment by MarcusDenker** [comment]
fix has been merged
