### ISSUE TITLE
Pressing the history button in calypso on libgit1.0 VM P9 latest crashes

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#1377]
[crash.txt](https://github.com/pharo-vcs/iceberg/files/4799726/crash.txt)

**Comment by Ducasse** [comment]
```
ExternalAddress
    0x7ffee5841b08 M LGitDiff>diff_tree_to_tree:repo:old_tree:new_tree:opts: 0x11466cf10: a(n) LGitDiff
    0x7ffee5841b78 M [] in LGitDiff>diffTree:toTree:options: 0x11466cf10: a(n) LGitDiff
    0x7ffee5841ba8 M LGitDiff(LGitExternalObject)>withReturnHandlerDo: 0x11466cf10: a(n) LGitDiff
    0x7ffee5841be0 M LGitDiff>diffTree:toTree:options: 0x11466cf10: a(n) LGitDiff
    0x7ffee5841c30 M LGitTree>diffTo:options: 0x113dc3230: a(n) LGitTree
    0x7ffee5841c98 M [] in IceLibgitTonelLog>collectCommitsFor:path: 0x113dc20c8: a(n) IceLibgitTonelLog
```

**Comment by guillep** [comment]
@Ducasse could you try applying the changes in this commit and retest: https://github.com/pharo-vcs/iceberg/commit/8d2fa269537d3407b27e52b54a206f74b938e3c1

With that change I cannot reproduce that problem anymore. But further testing is always appretiated.
That change is part of release 1.8.3 https://github.com/pharo-vcs/iceberg/releases/tag/v1.8.3, which is proposed for integration in Pharo9 in here: https://github.com/pharo-project/pharo/pull/6628
