### ISSUE TITLE
FFI tries to access a variable that is not there

### ISSUE THREAD

**Issue by arturozambrano** [pharo-vcs/iceberg#1386]
The environment is a docker image based on:  Ubuntu 18.04. We are running Pharo 8 there.
Looks like the .so file packaged with the VM lacks of the `handle` variable.
This erros occurrs randomly. In our, case we run some headless scripts that configure a Pharo image.
When saving the image looks like Pharo tries to release resources resulting in the following stack:

```FFIVariableNameNotFound: Could not find accessor for variable named "#handle"
FFICallout>>loaderForArgNamed:
FFICallout>>loaderForArgNamed:indirectIndex:
FFIVariableArgument>>resolveUsing:
[ :arg2 | arg2 resolveUsing: arg1 ] in FFIFunctionSpec>>resolveUsing: in Block: [ :arg2 | arg2 resolveUsing: arg1 ]
OrderedCollection>>do:
FFIFunctionSpec>>resolveUsing:
FFICalloutMethodBuilder>>generateMethodFromSpec:
FFICalloutMethodBuilder>>generate
FFICalloutMethodBuilder>>build:
FFICalloutAPI>>function:library:
FFICalloutAPI>>function:module:
LGitObject class(LGitExternalObject class)>>call:options:
LGitObject class>>object_free:
LGitObject class(LGitExternalObject class)>>finalizeResourceData:
FFIExternalResourceExecutor>>finalize
WeakFinalizerItem>>finalizeValues`

**Comment by tinchodias** [comment]
Hello,

Do you still have this problem? sorry for the late reply.
Were you "manually" instantiating LGitObject?

What I understand from the stack trace is that the garbage collector found that an instance of LGitObject is not referenced anymore and then this process executes `LGitObject class>>object_free:` at some point. To tell libgit2 to free memory allocated.

Regards.

**Comment by tinchodias** [comment]
I'm closing the issue, but please re-open it if needed.

**Comment by arturozambrano** [comment]
> Hello,
> 
> Do you still have this problem? sorry for the late reply.

yes

> Were you "manually" instantiating LGitObject?

No, it  happens by P8, headless and using Iceberg to load
> 
> What I understand from the stack trace is that the garbage collector found that an instance of LGitObject is not referenced anymore and then this process executes `LGitObject class>>object_free:` at some point. To tell libgit2 to free memory allocated.
> 

The point is: I don't understand how the object is freed, and after that Iceberg tries to do something with it.
I have patched the code by handling the exception but it is just a hack to have my CI working without failures.

Thanks!


> Regards.
