### ISSUE TITLE
Paths with accentuated characters make Iceberg/Git crash

### ISSUE THREAD

**Issue by bstjean** [pharo-vcs/iceberg#1395]
** 1) Here's the stack:

IceLibgitErrorVisitor>>visitGenericError:
IceLibgitErrorVisitor>>visitERROR:
LGit_GIT_ERROR>>acceptError:
[ :error | 
location exists
	ifTrue: [ location ensureDeleteAll ].
error acceptError: (IceLibgitErrorVisitor onContext: self) ] in IceGitClone>>execute in Block: [ :error | ...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
LGit_GIT_ERROR(Exception)>>signal
LGit_GIT_ERROR class(LGitCallReturnHandler class)>>signalWith:
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
[ location ensureCreateDirectory.
repo := LGitRepository on: location.
cloneOptions := LGitCloneOptions
	withCredentialsProvider: (IceCredentialsProvider defaultForRemoteUrl: url).

"Keeping references, because if not the GC take them."
checkoutOptions := cloneOptions checkoutOptions.
callbacks := cloneOptions fetchOptions callbacks.
callbacks transferProgress: IceGitTransferProgress new.
checkoutOptions
	checkoutStrategy: LGitCheckoutStrategyEnum git_checkout_force.
checkoutOptions progressCallback: IceGitCheckoutProgress new.
repo clone: url options: cloneOptions.
(LGitRemote of: repo named: 'origin')
	lookup;
	setUrl: url ] in IceGitClone>>execute in Block: [ location ensureCreateDirectory....
BlockClosure>>on:do:
IceGitClone>>execute
IceRepositoryCreator>>cloneRepository
[ self validate.
self isCloning
	ifTrue: [ self cloneRepository ]
	ifFalse: [ self addLocalRepository ] ] in IceRepositoryCreator>>createRepository in Block: [ self validate....
BlockClosure>>on:do:
IceRepositoryCreator>>createRepository
[ repository := builder createRepository ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryFor: in Block: [ repository := builder createRepository ]
BlockClosure>>on:do:
MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryFor:
[ ^ self createIcebergRepositoryFor: urlToUse ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryWithFallbackFor:url: in Block: [ ^ self createIcebergRepositoryFor: urlToUse ]
BlockClosure>>on:do:
MCGitHubRepository(MCGitBasedNetworkRepository)>>createIcebergRepositoryWithFallbackFor:url:
[ | remote |
remote := IceGitRemote url: remoteUrl.
self createIcebergRepositoryWithFallbackFor: remote url: remoteUrl ] in MCGitHubRepository(MCGitBasedNetworkRepository)>>getOrCreateIcebergRepository in Block: [ | remote |...
OrderedCollection(Collection)>>detect:ifFound:ifNone:
OrderedCollection(Collection)>>detect:ifNone:
MCGitHubRepository(MCGitBasedNetworkRepository)>>getOrCreateIcebergRepository

** 2) Now, the text of the error:

"LGit_GIT_ERROR: failed to stat 'C:\Users\Benoît St-Jean\Documents\Pharo\images\Pharo 8.0 (64bit) - ...a pas de caractÃ¨re correspondant au caractÃ¨re Unicode dans la page de codes multi-octet cible.
"

** 3) STEPS TO REPRODUCE:

1) On Windows 10, create a user with an accentuated character in the username
2) Evaluate the following in a playground:

Metacello new
    baseline: 'Garage';
    repository: 'github://pharo-rdbms/garage';
    load: 'Garage-Mysql'.

**Comment by tesonep** [comment]
Forcing the encoding of the files has solved the problem
