### ISSUE TITLE
Discard All button should ask for confirmation first

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#1396]
The "Discard all" button is close to the "Add package" button and does not ask the user if the changes should be really discarded.

Today after modifying some packages and adding new packages to the image I wanted to add the new packages to my Iceberg project. As the buttons are close together I accidentially hit the  "Discard all" instead of the "Add package" button.

This discarded many changes I applied on the modified packages that were already in the project. So I lost code with this.

=> we should build in a dialog "Do you really want to discard your changes" with YES/NO that the user needs to confirm first.

**Comment by tinchodias** [comment]
Ouch. I hope you were able to recover the discarded changes. We can add a confirmation like "Fetch all" has.

I think we can fix this issue in dev-1.9 but after a migration I'm doing these days.

**Comment by astares** [comment]
@tinchodias It was not much - so I was able to redo. But people can loose their changes - so an additional confirmation would be a plus. Thanks for caring!

**Comment by guillep** [comment]
Yes I agree we should have a preview of it.
