### ISSUE TITLE
Browse repository version menu entry is displayed twice

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#1403]
In Pharo9.0.0
Build information: Pharo-9.0.0+build.1030.sha.15f7c48a5446a6f0375aa7de070675c0f16493ad (64 Bit)

![image](https://user-images.githubusercontent.com/5980033/104110861-0845b180-52dc-11eb-9cf7-0ff8de0334e5.png)

**Comment by tinchodias** [comment]
The labels were the same but they are:
- open the code of this package in Calypso
- open the code of this package in Monticello Browser
In v2 I changed the labels, so we can close this issue.
