### ISSUE TITLE
Duplicate repository names

### ISSUE THREAD

**Issue by sanjayminni** [pharo-vcs/iceberg#1404]
After adding a repository and then installing using metacello the Repository name appears twice / duplicate 

![IcebergDulplicateRepositoryName](https://user-images.githubusercontent.com/12030766/105825036-1f2b1a00-5fe5-11eb-98c4-bdbadb366686.jpg)

**Comment by macta** [comment]
I have the same problem - I get it in a clean P8 image in osx loading a metacello baseline too:

![image](https://user-images.githubusercontent.com/5553623/106064938-6fdc6900-60f2-11eb-948b-145c8b6aab88.png)

**Comment by Ducasse** [comment]
Yes this is a wellknown bug and we will not fix it.

**Comment by Ducasse** [comment]
No time focusing on Pharo 90 because this is not a show stopper.

**Comment by timm-mwp** [comment]
I agree - getting P9 right makes sense
