### ISSUE TITLE
Issues with glamour fast tree

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#149]
1) Cant navigate with arrows (open/close branches)
2) Refresh closes some branches
3) Subscript out of bounds error (not sure how to reproduce it)
4) Shortcuts not working (test ctrl+B for browse)

**Comment by npasserini** [comment]
In fact 4 only fails for ctrl+b.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Iceberg uses now spec for all views.
