### ISSUE TITLE
Colors need a legend.

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#181]
I think it could be cool to get a legend somewhere for the colors. Maybe just a ? with a tooltip somewhere.

**Comment by guillep** [comment]
Not valid. What colors?

**Comment by jecisc** [comment]
@guillep In the dev-0.6 version when there is changes the repository is displayed green. When there is incoming changes it's yellow, when there is outgoing changes it's blue and when a package is not loaded it's grey.

Don't know for the dev-0.7 version.
