### ISSUE TITLE
Iceberg fails on Inria Jenkins due to old Git

### ISSUE THREAD

**Issue by girba** [pharo-vcs/iceberg#196]
Loading Iceberg in the image before loading Moose breaks the job:

     	iceberg-metacello adapter for: github://kursjan/petitparser2
	31mMCFileTreeGitError: Git error: Unknown option: -C
	usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
	           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
	           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
	           [-c name=value] [--help]
	           <command> [<args>]

	0m[ :command :outString :errString | 
	command isSuccess
		ifTrue: [ ^ outString ]
		ifFalse: [ MCFileTreeGitError new
				signal: 'Git error: ' , (errString ifEmpty: outString) ] ] in MCFileTreeGitRepository class>>runOSSubprocessGitCommand:in: in Block: [ :command :outString :errString | ...
	BlockClosure>>cull:cull:cull:
	OSSUnixSubprocess>>runAndWaitPollingEvery:retrievingStreams:onExitDo:
	MCFileTreeGitRepository class>>runOSSubprocessGitCommand:in:
	[ :bar | 
	bar label: self gitCommand , ' ' , anArrayOfStrings first.
	Smalltalk platform isWin32
		ifTrue:
			[ ^ self runProcessWrapperGitCommand: anArrayOfStrings in: aDirectory ]
		ifFalse: [ ((Smalltalk at: #OSSUnixSubprocess ifAbsent: [  ])
				ifNil: [ false ]
				ifNotNil: [ :g | g isClass ])
				ifTrue: [ ^ self runOSSubprocessGitCommand: anArrayOfStrings in: aDirectory ]
				ifFalse: [ ^ self runOSProcessGitCommand: anArrayOfStrings in: aDirectory ] ] ] in MCFileTreeGitRepository class>>runGitCommand:in: in Block: [ :bar | ...

Adding right after loading Iceberg:
    
     IceRepository defaultBackendType: IceLibgitLocalRepository.

Should solve it for now.

**Comment by npasserini** [comment]
After changing the backend, problem persists: https://ci.inria.fr/moose/job/moose-6.1/320/console

**Comment by girba** [comment]
I think it is not the same problem, because it fails in a different place.

**Comment by npasserini** [comment]
Ok, I misunderstood your report. I do not think that we can fix the original problem (or that it is worth it). First, the CI is using a very old version of git, 1.7 I think, which is no longer supported by git. 

Second, I think that libgit is a better backend option and will be the default backend for Iceberg, I am not even sure that we will have the time to maintain both backends.

Finally, the problem is not in the iceberg code itself, but in gitfiletree
```runOSSubprocessGitCommand: anArrayOfStrings in: aDirectory
	| classOfOSSUnixSubprocess |
	classOfOSSUnixSubprocess := Smalltalk at: #OSSUnixSubprocess.
	classOfOSSUnixSubprocess new
		command: self gitCommand;
		arguments:
			{'-C'.
			(MCFileTreeFileUtils current directoryPathString: aDirectory)}
				, anArrayOfStrings;
		redirectStdout;
		redirectStderr;
		runAndWaitPollingEvery: (Delay forMilliseconds: 5)
			retrievingStreams: true
			onExitDo: [ :command :outString :errString | 
			command isSuccess
				ifTrue: [ ^ outString ]
				ifFalse: [ MCFileTreeGitError new signal: 'Git error: ' , (errString ifEmpty: outString) ] ]
				``` 

If we are decided to invest time in this direction, we should talk to Thierry.

**Comment by ThierryGoubier** [comment]
Hi Nico, Doru,

2016-11-08 12:10 GMT+01:00 Nico Passerini <notifications@github.com>:

> Ok, I misunderstood your report. I do not think that we can fix the
> original problem (or that it is worth it). First, the CI is using a very
> old version of git, 1.7 I think, which is no longer supported by git.
>
> Second, I think that libgit is a better backend option and will be the
> default backend for Iceberg, I am not even sure that we will have the time
> to maintain both backends.
>
It is a good solution that Iceberg focuses on libgit support. GitFileTree
has different goals, and I maintain it independently.

> Finally, the problem is not in the iceberg code itself, but in gitfiletree
> runOSSubprocessGitCommand: anArrayOfStrings in: aDirectory
> | classOfOSSUnixSubprocess |
> classOfOSSUnixSubprocess := Smalltalk at: #OSSUnixSubprocess.
> classOfOSSUnixSubprocess new
> command: self gitCommand;
> arguments:
> {'-C'.
> (MCFileTreeFileUtils current directoryPathString: aDirectory)}
> , anArrayOfStrings;
> redirectStdout;
> redirectStderr;
> runAndWaitPollingEvery: (Delay forMilliseconds: 5)
> retrievingStreams: true
> onExitDo: [ :command :outString :errString |
> command isSuccess
> ifTrue: [ ^ outString ]
> ifFalse: [ MCFileTreeGitError new signal: 'Git error: ' , (errString
> ifEmpty: outString) ] ]
>
> If we are decided to invest time in this direction, we should talk to
> Thierry.
>
The support for -C in git is required by the use of OSProcess for older
versions of Pharo and the latest 64 bits version for which UFFI-based
layers do not work yet.

I would suggest forking a special version of filetree on github, and
rewrite the CI job to load that fork with a Metacello lock.

Given the perspective of switching all CI jobs to Travis, this seems
reasonable as a short term hack.

**Comment by girba** [comment]
Indeed, I also do not think it is meaningful to make old Git versions work. What would be meaningful would be to fail with a nice message that points to the problem. As it is now, I could not know what the issue actually is. If the error would have said "Old version of Git detected (X.Y). Please upgrade to A.B" it would have been perfect. Is it doable?

**Comment by ThierryGoubier** [comment]
2016-11-08 15:23 GMT+01:00 Tudor Girba <notifications@github.com>:

> Indeed, I also do not think it is meaningful to make old Git versions
> work. What would be meaningful would be to fail with a nice message that
> points to the problem. As it is now, I could not know what the issue
> actually is. If the error would have said "Old version of Git detected
> (X.Y). Please upgrade to A.B" it would have been perfect. Is it doable?
>
It's a significant effort (check it on every image session start basically,
parse a version code because otherwise it appear as one of the possible
errors generated by a call to git), but this is probably a nice feature...
even if the only user for the check is Jenkins :)

Which Pharo version has this to be targeted for? How is Iceberg loading
GitFileTree? Will you be ready to test with a machine or VM with a version
of git old enough?

Thierry

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
