### ISSUE TITLE
Libgit backend fails to load versions when code is not in the root of the repository.

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#198]
Reported by @girba. Error log in:  https://ci.inria.fr/moose/job/moose-6.1/320/console

The simplest way to reproduce it is: 
```
IceRepository defaultBackendType: IceLibgitLocalRepository.
repo := (IceRepository origin: 'git@github.com:peteruhnak/geometry.git') subdirectory: 'repository'.
(repo packageNamed: 'Geometry') latestVersion mcVersion
```

**Comment by npasserini** [comment]
It turns out that the problem has nothing to do with the code being in the root or not. Apparently the geometry repository at https://github.com/peteruhnak/geometry has (at least some of) its method files marked as binary files, so libgit returns a ByteArray instead of a ByteString as contents of the tree entry.

We can work it around, but I am not sure that it is a good idea.

**Comment by npasserini** [comment]
It turns out that the problem has nothing to do with the code being in the root or not. Apparently the geometry repository at https://github.com/peteruhnak/geometry has (at least some of) its method files marked as binary files, so libgit returns a ByteArray instead of a ByteString as contents of the tree entry.

We can work it around, but I am not sure that it is a good idea.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
