### ISSUE TITLE
diff from an incoming version shows new classes as deleted

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#199]
I have a project on a master branch. I merged code from another branch with outside the image. I now have new incoming commits for the master that can be displayed by Iceberg (I did not find a way to merge and check the diff before merging with Iceberg).
new / removed methods are displayed correctly (green for incoming, red for current) but classes are not correctly displayed. New classes are seen as removed and the methods of new classes are not displayed

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. ¡
