### ISSUE TITLE
Improve repositories browser

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#216]
I am working on making the Iceberg main view a bit more "project oriented" So @estebanlm @dalehenrich, I listen to your ideas.

**Comment by jecisc** [comment]
Will you enable Iceberg to act as a facade for Metacello as I asked in https://github.com/npasserini/iceberg/issues/184 ? Or is it not in your plans?

**Comment by estebanlm** [comment]
@jecisc this is not related ;)

**Comment by npasserini** [comment]
Let's continue that discussion in #184 .
