### ISSUE TITLE
Commit in Libgit does not accept special characters in the message

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#225]
I do not know exactly what is special here, but this message is not accepted: 

"Use just #basename of the branch for merging. 

This is because #merge involves a checkout and if you checkout origing/<mergeDestinationBranch> you will be checking out a detached HEAD pointing to the latest commit in a remote branch, which is not useful for merging. Instead, if you provide just the #basename (i.e. <mergeDestinationBranch> without 'origin/'), the backend will always checkout a local branch (creating it if it does not exist previously), which will be suitable for merging onto it."

**Comment by guillep** [comment]
Fixed. Commit message now transforms line endings to lfs and encodes the text to utf8 as expected.
