### ISSUE TITLE
clone takes much time in big repositories

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/iceberg#237]
for example, if I do: 

```Smalltalk 
Metacello new
	baseline: 'Iceberg';
	repository: 'github://estebanlm/pharo-vm/mc';
	load.
```

it will take an eternity

**Comment by estebanlm** [comment]
yeah, this is not like that anymore... except on windows. I don't know why windows is still like that.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
