### ISSUE TITLE
When repository is forgotten, the package panes are left as is and not cleared ...

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/iceberg#240]
based on commit 0ff1bd0...

I would expect that the package panes would be forgotten as well .. the menu items are active as well .. not sure what would happen if you used one of the menu items ...

**Comment by guillep** [comment]
I think this may still be an issue in latest version with the new UI.

**Comment by guillep** [comment]
Should not be happening anymore in latest version. Please reopen if necessary
