### ISSUE TITLE
when forgotten repository added again, the old package state appears to be preserved

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/iceberg#241]
based on commit 0ff1bd0... also related to bug #240 ...

I added a local repository that had two packages ... I forgot the repository, then deleted one of the packages on disk, then added the repository again and the packages pane listed the two packages ...

I had to open a Monticello Repository browser and do a `flush cached versions`, forget and re-add the repository to get Iceberg to notice that there was only one package in the repository ...

**Comment by guillep** [comment]
This should not be valid anymore in the latest version.
