### ISSUE TITLE
red X in Iceberg window

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/iceberg#242]
This happened after doing the following steps:

1. add local repository where PharoGs-Basic-ProtoObject package already exists, but DO NOT load the package.
2. create a package of the same name using the Monticello Browser (is there a way to create a package using the Iceberg browser).
3. move the ProtoObject class to the PharoGs-Basic-ProtoObject package
4. attempt to add the package to the project/repository ...
5. get the following 

![iceberg-bug](https://cloud.githubusercontent.com/assets/623951/21365693/3dadb8ac-c6ab-11e6-8a39-4ef41c81776a.png)

I'm only trying to write a new version of the package from an image withouf first loading the package ... something that should be doable .... 

I really need to do this so my workaround will be to use git file tree ...

**Comment by estebanlm** [comment]
Hi Dale, 
Are you using master or 0.3 version?
because now most of development is in dev-0.4... and we are very close of releasing an usable "release candidate" version...  (even if there are still lots of small problems) :)

**Comment by dalehenrich** [comment]
Sorry about that, I'm using the master branch ... @npasserini had mentioned something about a dev version, but since that was a week or so ago, I thought that perhaps it had already been merged into the master branch, but I see now that he had told me to use dev-0.4 ..... I guess I'll switch to using the dev-0.4 branch from now on ...

**Comment by npasserini** [comment]
We should merge dev-0.4 into master.

2016-12-21 0:49 GMT+01:00 Dale Henrichs <notifications@github.com>:

**Comment by estebanlm** [comment]
yeah, the problem of that is that it will not work on mac because of the old (and bad) libgit2 library... I will work on fix that to allow the merge this week :P

**Comment by estebanlm** [comment]
@dalehenrich can you confirm if this remains in dev-0.4 branch?

**Comment by estebanlm** [comment]
@dalehenrich ping?

**Comment by estebanlm** [comment]
hi @dalehenrich. This has changed so much that it does not has sense anymore. 
it should be fixed :)

**Comment by dalehenrich** [comment]
thx!
