### ISSUE TITLE
Forget Repository does not work

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#246]
I cloned a repository and made a mistake in the subdirectory. Since I do not find a way to edit it I wanted to remove this but the problem is that it does nothing when I click on "Forget repository" except adding a popup.

**Comment by jecisc** [comment]
Does not happen anymore on Mac. I need to check on windows before closing.

**Comment by estebanlm** [comment]
@jecisc ping

**Comment by jecisc** [comment]
I cannot check it because of my SqueakSSL plugin's problem :( But if it works on mac it should work on windows I think. We can close for now and I will re-open if it happens again.

**Comment by estebanlm** [comment]
heh... I just saw that under certain conditions, this remains true... I will reopen it to keep an eye on it :P

**Comment by tesonep** [comment]
Fixed in 0.7
