### ISSUE TITLE
Allow to cherry-pick changes to commit

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#254]
It would be cool to have a system as Komitter to be able to select the changes we commit. Sometimes we do two different changes and we want two commits.

**Comment by jecisc** [comment]
Also it seems that Iceberg commit all the packages all the time. We should be able to commit packages individually also. (I do not mean to commit packages individually all the time, it's great to be able to commit multiple packages)

**Comment by estebanlm** [comment]
no, this a feature, commits in iceberg are by project, not by package. 
what you will be able to do in the near future is to cherry-pick the changes you want to commit (as in Komitter), but no per-package commit. Of course, you will be able to "cherry-pick" the changes in just a package, but well...

**Comment by jecisc** [comment]
If we are able to pick changes as in Komitter it's fine with me :) It's what I want.

**Comment by jecisc** [comment]
@estebanlm I think this can be close right?

**Comment by estebanlm** [comment]
yes :) 

is in 0.5
