### ISSUE TITLE
Iceberg should remember last setting of "Upload changes on commit"

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#258]
Let's assume that you have a github project locally cloned and from time to time you commit your work.
After doing some coding you usually synchronize to commit your changes with Iceberg.

Let's also assume that you work offline - not connected to the internet (for instance in a train)
and later push your branch to the origin.

In the sync view there is a checkbox "Upload changes on commit?" - so if you work OFFLINE you can unselect this box.  If you commit often you have to unselect it very often. Doing this again and again 
before each commit is annoying. Iceberg should remember the previous setting of this checkbox.

**Comment by astares** [comment]
Eclipse solved this by having two buttons "Commit" and "Commit and Push".

See http://wiki.eclipse.org/images/f/ff/Egit-3.1-StagingView.png

**Comment by jecisc** [comment]
I also think that two buttons is better than the checkbox.

**Comment by jecisc** [comment]
@estebanlm Can be closed
