### ISSUE TITLE
showing compacted version of changes?

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/iceberg#269]
So... when managing large projects, I find annoying the diff panel tree that shows all packages, even those that do not have changes... in that view in fact I want to focus on the modified packages and for example on pharo-core I have to scroll down always to see anything (I have like 300 packages, and sometimes a one-line change). 

What do you think? It has sense?

**Comment by jecisc** [comment]
In the git's gui tool I use out of Pharo it shows only folder/packages containing changes. I never found this weird. When we want to commit I think it would be cool to see only changed packages indeed. IMO if you let the possibility to see both versions, the "changed packages only" should be the default one.

**Comment by estebanlm** [comment]
yeah, let's do that

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
