### ISSUE TITLE
using multi-remotes does not show correctly in/out elements

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/iceberg#270]
so, we introduced the possibility of have multiple remotes. 
we also introduced the capability of define "default pulling/pushing remote" for the tool, different to the one that is defined as default (who is origin/branch usually)... the problem is that the browser does not show correctly this definitions hence introducing a lot of confusion.

**Comment by estebanlm** [comment]
I made a quick fix here: https://github.com/estebanlm/iceberg/tree/issue270
@npasserini can you validate this approach?

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. There is a new UI to select the pull/push targets, and branches have gone back to have an upstream to be git compatible.
