### ISSUE TITLE
Add a "Close sync window on push" setting

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#278]
This is a really small improvement but it would be cool if Iceberg could check the changes after a push and close the sync windows if there is no more changes. 

This is to fight against the "I have too many windows" Pharo's syndrome. 

Maybe if people do not like it we could have the same system than the Pharo launcher with a check-box at the bottom on the windows "Close on push?"

**Comment by estebanlm** [comment]
Mmm... I disagree with this. This will break any mental workflow existent (because this is not what other tools do or/and what people are expecting).
Also the sync window is more than a "commit" window.

Now... "close on push" is something I can accept :)

**Comment by guillep** [comment]
This should not be valid anymore in the latest version.
