### ISSUE TITLE
New feature: amend

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#283]
I would love to be able to do an amend while committing. It could be a checkbox under/over the commit message editor as in gitkraken. [1][2]

[1] https://puu.sh/u7fkn/f0fffb63fc.png
[2] https://puu.sh/u7fle/57e613b615.png

I would save me a lot of squash outside Pharo.

**Comment by jecisc** [comment]
This is not something I expect to see soon, but it's good to keep issues for the future :)

**Comment by guillep** [comment]
Maybe you want to give it a try yourself? I think people in general do not need amend or even rebase (even if I use them myself to cheat).

Maybe you could try to start extending the IceLibGitRepository and friends?

I'll close this issue until there is a PR for it.
