### ISSUE TITLE
Extend URLs to support Gogs and other rep management tools as well as HTTP

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#284]
Iceberg currently only understands URLS from github. This is limiting, especially if one for instances used "Gogs" or other repo management tools. Or if you run locally without HTTPS but HTTP instead.

Example: 
======
INSTALL GOGS ON YOUR LOCAL MACHINE (takes 5 minutes)

1. Download the binary ZIP for your platform from https://gogs.io/docs/installation/install_from_binary
 2. Extract into a directory
 3. Run
           ./gogs web
 4. Visit http://localhost:3000, set the database to SQLite3
        a) you can also change where the *.db files resides on disk
        b) you can also setup where your bare repositories are located
 5. Give an admin name and password and save the initial settings

=> You have "gogs" as an own git server with a web based running locally (edited)

If you have Gogs running locally your URLs might look like that:

    http://localhost:3000/root/myproject.git

but    

   IceRemote url: 'http://localhost:3000/root/myproject.git'

throws an error.

**Comment by astares** [comment]
Also if you setup gogs behind an nginx or apache server the URL might have a subpath before the 
owner of the project. So if "gogs" or other repo management is proxied on URLs like http://myraspberrypi/subpath/moresubpath a final repo string might look like that:

       http://myraspberrypi/subpath/moresubpath/owner/myproject.git

and should also be accepted

**Comment by astares** [comment]
Here are some example URLs that might appear and the regexp
https://www.debuggex.com/r/fFggA8Uc4YYKjl34

**Comment by dalehenrich** [comment]
Personally I think the style of url used by gitfiletree works pretty well:

```
  A gitfiletree url with a host is the target for a remote. All other parameters are optional.
	Parameters are:
		dir : the directory inside the repository where the target MC packages are.
		branch : the git branch to fetch.
		protocol: the user name part to add to the ssh Url, default to git, but can also be https (which implies read only access).
		readOnly : is the repository read only? If present, reduce the history to a minimum (and change the GUI).
	Alternative url syntax:
		gitfiletree://github.com/dalehenrich/filetree:pharo5.0_dev/repository
	with:
		host : github.com
		project : dalehenrich/filetree
		branch : pharo5.0_dev
		dir : repository
```
It can accommodate virtually any git server ... 

The scheme name can be fiddled with: `giticeberg` or `gitfiletree` or `gitcypress` to indicate which tool is to be used. An alternative is to use a common scheme like `git` and then have the tools register with Metacello so that the appropriate tool is invoked by Metacello for management of the package itself ...

**Comment by astares** [comment]
It's more complicated I guess.

Lets make an example: I've setup a Raspberry Pi at home with nginx web server running. In my home network I can access the machine with its hostname and using HTTP.

    http://myraspberrypi   to access the entry page for different stuff.

Now I installed gogs (see gogs.io) on the same pi and as the root location is already used
for the HTML entry page I've setup a reverse proxy from nginx to gogs which is 
accessible on the following location including a path:
 
   http://myraspberrypi/gogs/

With this the repo URLs will look like 

      http://myraspberrypi/gogs/owner/repo.git  and they run in HTTP instead of HTTPs.

I can even set it up for a special user which must be respected in the URL too:

      http://user@myraspberrypi/gogs/owner/repo.git

So beside the git:// and scp:// protocols we can have any regular HTTP or HTTPs URL 
with a user, a (non-standard) port, a subpath and at the end the owner and the repo
(either with .git extension or for convinience without to be able to clip it from a webbrowser).
The hostpart can be a full domain or just a machine name in the LAN.

This leads me to the following own custom regex that I now assembled based on this
in Pharo: 

    ((http|https)\://)(([\w]+)@)*([\w.]+)(\:([\d]+))*(/[\w]+)*/([\w]+)/([\w]+(.git)?)

if you want to browse it's parts visit  https://www.debuggex.com, select "PYTHON"
and paste in

  (?P<ProtocolPart>(?P<protocol>http|https)\://)(?P<UserPart>(?P<user>[\w]+)@)*(?P<hostname>[\w.]+)(?P<portPart>\:(?P<port>[\d]+))*(?P<path>/[\w]+)*/(?P<owner>[\w]+)/(?P<RepoPart>[\w]+(?P<Extension>.git)?)

which is the same regexp but with ?P<Annotations>

I now extended iceberg with this together with many tests and it works fine in all tested combinations/scenarios.

**Comment by astares** [comment]
I created a PULL request:   https://github.com/npasserini/iceberg/pull/287 with all the changes.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
