### ISSUE TITLE
Cannot use Versionner if Iceberg is in the image

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#286]
In a Pharo 6 image I have Iceberg dev-0.4. I wanted to create a configuration using versionner but when I try to add a dependency I get an Error `Instance of IceMetacelloRepositoryAdapter did not understand #isCache`.

If I implement the method to return false I then get an Error `Instance of IceMetacelloRepositoryAdapter did not understand #koRemote`.

**Comment by jecisc** [comment]
For now I just reject all IceMetacelloRepositoryAdapter from RemotesManager>>buildRoots.

**Comment by astares** [comment]
The #koRemote problem was fixed this week in Pharo base image:  https://pharo.fogbugz.com/f/cases/19738

**Comment by astares** [comment]
Sorry that was the #koRemote issue for Pharo 5.0. There is another for Pharo 6.0
https://pharo.fogbugz.com/f/cases/19739 not yet integrated as of now. But you can load the slice and try.

**Comment by estebanlm** [comment]
this has been integrated
