### ISSUE TITLE
MessageNotUnderstood: IceClassChangeSet>>operation While reverting changes

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#288]
Today I try to revert some changes from the synch view but I got: MessageNotUnderstood: IceClassChangeSet>>operation

It happen when you try to revert the deletion of a class at least.

**Comment by estebanlm** [comment]
yes, not all changes are reversible (at least there)... just method changes. 
what is bad is that you have enabled the option, not that you cannot revert :)

ps: revert changes is usually handled through epicea...

**Comment by jecisc** [comment]
If some changes cannot be revert I think it would be cool to let an entry to open Epicea. Because I did not thought about Epicea while doing this and I ended up to unload and reload the package :)

**Comment by jecisc** [comment]
I get it also when I try to revert a class comment change.

**Comment by peteruhnak** [comment]
Imho reverting a class should be available, this is such a common use case too. In fact at the moment it is faster to commit and then load older commit than to try to revert many changes one by one.

**Comment by peteruhnak** [comment]
Here's some more info for IceClassChangeSet reverse

* it only works when a change was mode to the class itself (like adding/removing an instance variable)
* method changes are not considered class changes (`analyseChanges` doesn't consider the methods that are inside `elements`
* reverting reverts only class changes, and not class' methods

For the last point we actually need two actions:

* **revert** - that reverts just the single item (so here e.g. the addition of an instance variable)
* **revert recursively** - that reverts everything (so both the instance variable, and any changed methods)

But see the PR https://github.com/pharo-vcs/iceberg/pull/587 , maybe it can be better, but this should address the most immediate problems.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. There is a new changes model.
