### ISSUE TITLE
Commit and push might break the image

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#291]
It happened to me two times already that my image became unresponsive while committing via Iceberg and publishing the changes. 

Checking the git repository the commit is here but it is not pushed.

Iceberg branch: dev-0.4

Pharo: 60424

OS: OSX El Cptain

VM: 

/Users/Cyril/Pharo/Pharo.app/Contents/MacOS/Pharo
CoInterpreter * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Feb 22 2017
StackToRegisterMappingCogit * VMMaker.oscog-EstebanLorenzano.2136 uuid: 40534c32-ca6b-4e97-91ec-31d509e49b0c Feb 22 2017
VM: 201702221539 https://github.com/pharo-project/pharo-vm.git $ Date: Wed Feb 22 16:39:40 2017 +0100 $ Plugins: 201702221539 https://github.com/pharo-project/pharo-vm.git $

**Comment by estebanlm** [comment]
using SSH or HTTPS?

**Comment by jecisc** [comment]
HTTPS

**Comment by estebanlm** [comment]
yes, I have seen that. Try using SSH, should be ok.

**Comment by estebanlm** [comment]
btw... that does not closes the issue, we still need to solve that. I'm just giving you a workaround :)

**Comment by jecisc** [comment]
I'll need to try SSH :) Last time I could not get it to work with ssh but I did not try long since I was busy so I use HTTPS since.

**Comment by jecisc** [comment]
@estebanlm I used Iceberg a little since last week and I got no problem anymore. I am just lucky or did you changed something that could have correct the problem?

**Comment by estebanlm** [comment]
no idea, but maybe yes, if you updated VMs, etc.

**Comment by jecisc** [comment]
Old issue, too much changed to know if it is still valid.
