### ISSUE TITLE
Iceberg cannot use the repositories without any remote

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#296]
There cannot be registered the repositories that have no remote origin.

How to reproduce:
1) create an empty directory and inside it do: "git init"
2) add this repository as local to Iceberg

**Comment by bestlem** [comment]
It gets worse.
When running iceberg from the menu after this it complains it can't find repostitory from the directory above the one you tried to create

**Comment by estebanlm** [comment]
@bestlem this seems unrelated. 
Please open a different bug report with a reproduction explanation.

**Comment by estebanlm** [comment]
this should be fixed. 
what you cannot do now is to push without remotes, but that sounds reasonable :)

**Comment by estebanlm** [comment]
according to me, this is fixed
