### ISSUE TITLE
RSOD when we delete a branch

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#307]
I have an image with MaterialDesignLite loaded and Iceberg. I deleted one of the branch from github and locally (outside Pharo) because it was not useful anymore. When I got back in Pharo, I did one click on Iceberg and I got a  Red Square Of Death. 

![See:](https://puu.sh/uVD2s/5e8d38b0d6.png)

**Comment by jecisc** [comment]
Note: This is not urgent since it does not make Iceberg unusable. When I click on another repo and come back it's fine again.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version.
