### ISSUE TITLE
Error while cloning

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#320]
Usually I work with local directories but today I wanted to clone one from github via Iceberg but I got an error.

Here is the repo I used: https://github.com/jecisc/Bazard

How to reproduce:
- On windows 7 I installed on a Pharo 6 image iceberg 0.4-dev
- Click on `clone repository`
- Remote URL: `git@github.com:jecisc/Bazard.git`
- As local directory I choose one of my folder (`C:\Users\JeCisC\AppData\Roaming\Pharo\GitRepositories`)
- Code Subdirectory: empty
- Click on create repository

And now I get a RSOD.

![Screen](http://puu.sh/v8nNS/231493811a.png)

Maybe I did something wrong, but in that case I should get en error message explaining what I did not do right and not a RSOD.

Image
-----
C:\Users\JeCisC\AppData\Roaming\Pharo\images\Pharo 6.0 (beta)-15\Pharo 6.0 (beta)-15.image
Pharo6.0
Latest update: #60458
Unnamed

Virtual Machine
---------------
C:\Program Files (x86)\Pharo\vm\50\PharoConsole.exe
CoInterpreter * VMMaker.oscog-eem.2188 uuid: ff4ca601-cd05-4792-ab0d-dcdf19975239 Apr  3 2017
StackToRegisterMappingCogit * VMMaker.oscog-eem.2188 uuid: ff4ca601-cd05-4792-ab0d-dcdf19975239 Apr  3 2017
VM: 201704030814 https://github.com/pharo-project/pharo-vm.git $ Date: Mon Apr 3 10:14:56 2017 +0200 $ Plugins: 201704030814 https://github.com/pharo-project/pharo-vm.git $

Win32 built on Apr  3 2017 09:42:19 GMT Compiler: 5.4.0
VMMaker versionString VM: 201704030814 https://github.com/pharo-project/pharo-vm.git $ Date: Mon Apr 3 10:14:56 2017 +0200 $ Plugins: 201704030814 https://github.com/pharo-project/pharo-vm.git $
CoInterpreter * VMMaker.oscog-eem.2188 uuid: ff4ca601-cd05-4792-ab0d-dcdf19975239 Apr  3 2017
StackToRegisterMappingCogit * VMMaker.oscog-eem.2188 uuid: ff4ca601-cd05-4792-ab0d-dcdf19975239 Apr  3 2017

Operating System/Hardware
-------------------------
Win32 6.1 IX86

Operating System Details
------------------------
Operating System: Windows 7 Professional N (Build 7601 Service Pack 1)
	Registered Owner: JeCisC
	Registered Company: 
	SP major version: 1
	SP minor version: 0
	Suite mask: 100
	Product type: 1

**Comment by jecisc** [comment]
Also Iceberg becomes unusable after that.

**Comment by estebanlm** [comment]
I cannot reproduce it :( 

![screen shot 2017-04-04 at 08 54 29](https://cloud.githubusercontent.com/assets/513630/24644595/c0ea228a-1914-11e7-9b2b-c31ad279ba00.png)

I cloned and pointed to correct place (by the way, putting sources were you are putting them sucks... this is not AppData, this is development), and it worked fine. 
Can you try cloning to another place?

and to make iceberg usable again: `IceRepositories registry inspect`, then look the wrongly cloned repository and do a forget of it manually.

**Comment by jecisc** [comment]
I checked fast before going to work and it might be caused by the fact that I did not had an id_rsa ssh key on my windows. 

I'll need to check when I'll have time if it work after generating one or using my github_rsa key.

If the problem comes from here then the error should be cached and a window explaining how to set/generate keys should be opened IMO.

**Comment by estebanlm** [comment]
mmm... no, it shouldn't be that. 
if is that it will show debugger with the message "no ssh keys found" (yes, it can be enhanced, but this is not the point :P)

**Comment by jecisc** [comment]
Last week I generated an id_rsa key and today I retried and now I get a debugger `LGit_GIT_ERROR: error authenticating: failed connecting agent`

**Comment by jecisc** [comment]
And now I get this error all the time on my windows :(

**Comment by jecisc** [comment]
I got the initial error again. 
I used the folder C:/github-cache as local directory.

**Comment by jecisc** [comment]
I removed the catch in Morph>>fullDrawOn: and now I get an error `Error: LGit_GIT_ENOTFOUND: Could not find repository from 'C:\github-cache'`
```
LGitReturnCodeEnum(Object)>>error:
[ :err :rcvr | 
"Handle a drawing error"
| errCtx errMorph |
errCtx := thisContext.
[ errCtx := errCtx sender.
"Search the sender chain to find the morph causing the problem"
[ errCtx notNil and: [ errCtx receiver isMorph not ] ]
	whileTrue: [ errCtx := errCtx sender ].
"If we're at the root of the context chain then we have a fatal drawing problem"
errCtx ifNil: [ ^ self handleFatalDrawingError: err ].
errMorph := errCtx receiver.
"If the morph causing the problem has already the #drawError flag set,
			then search for the next morph above in the caller chain."
errMorph hasProperty: #errorOnDraw ] whileTrue.
errMorph setProperty: #errorOnDraw toValue: true.
"Install the old error handler, so we can re-raise the error"
rcvr error: err ] in WorldState>>displayWorldSafely: in Block: [ :err :rcvr | ...
BlockClosure>>cull:cull:
[ :ex | errorHandlerBlock cull: ex description cull: ex receiver ] in BlockClosure>>ifError: in Block: [ :ex | errorHandlerBlock cull: ex description cul...etc...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
LGit_GIT_ENOTFOUND(Exception)>>signal
LGit_GIT_ENOTFOUND class(LGitCallReturnHandler class)>>signalWith:
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>open
[ | repo |
repo := (LGitRepository on: self location) open.
aBlock value: repo ] in IceLibgitLocalRepository>>withRepoDo: in Block: [ | repo |...
[ self checkInitialized.
aBlock value ] in LGitGlobal class>>runSequence: in Block: [ self checkInitialized....
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in LGitActionSequence(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
LGitActionSequence(DynamicVariable)>>value:during:
LGitActionSequence class(DynamicVariable class)>>value:during:
LGitGlobal class>>runSequence:
IceLibgitLocalRepository>>withRepoDo:
IceLibgitLocalRepository>>lookupHead
IceLibgitLocalRepository>>branch
IceRepository>>branch
IceRepositoryModel>>branchName
ByteSymbol(Symbol)>>glamourValueWithArgs:
ByteSymbol(ProtoObject)>>glamourValue:
GLMFastTablePresentation(GLMTablePresentation)>>column:valueFor:
[ self glamourPresentation
	column: aGlamourColumn
	valueFor:
		(self glamourPresentation isWithElementIndex
			ifTrue:
				[ anElement asGlamorousMultiValue , anInteger asGlamorousMultiValue ]
			ifFalse: [ anElement ]) ] in GLMFastTableDataSource>>valueFor:withIndex:in: in Block: [ self glamourPresentation...
GLMFastTableDataSource(GLMFastListDataSource)>>cacheAt:for:ifAbsentPut:
GLMFastTableDataSource>>valueFor:withIndex:in:

```

**Comment by estebanlm** [comment]
thing is: I cannot reproduce it: I take a fresh win7, download latest vm, latest image, install iceberg and I have no problems to clone your repo.
Can you trying doing exactly that, to see what happens? (I mean, not using launcher and being sure you have the latest of everything)

**Comment by estebanlm** [comment]
now, more questions: 

- why you continue to load latest metacello ? 
  - why you cannot use the one we provide ?
  - why we should update, in case you think is needed ?
- did you try installing latest metacello *before* iceberg ?

**Comment by jecisc** [comment]
On this project I do not load latest Metacello. So the bug is not related here. 

On other project it is loaded because Dale improved the metadataless management of FileTree with Cypress and Pharo never sync with Metacello since (last update was during the dev of Pharo 5 I think). I don't know if those improvements are still needed with Iceberg, I never got the chance to test.

**Comment by dalehenrich** [comment]
Do I understand that Iceberg does not work with the latest Metacello? ... if so that is a big problem ... you guys are way behind in Metacello updates and when one of your users runs into a Metacello bug that I've fixed, they need to be able upgrade to the latest Metacello :(

**Comment by jecisc** [comment]
I know that when I load latest Metacello I have a DNU in Iceberg for #flushForScriptGet. But I don't know if this is a problem in Iceberg or Metacello part (https://github.com/npasserini/iceberg/issues/260).

But there is definitively a sync that need to be done soon. I hope at the beginning of Pharo 7 release. Because there is a lot of new stuff in the current stable metacello and there is a lot of changes in the metacello of pharo that are not in metacello-work.

**Comment by dalehenrich** [comment]
#flushForScriptGet is a Metacello method, so the DNU is a problem for Iceberg ... It's awfully frustrating for me ... I can understand how good developers get driven away from Pharo on a regular basis ...

**Comment by dalehenrich** [comment]
I have offered several times try to work out a solution to the problems and I haven't heard a peep ... ah well ...

**Comment by dalehenrich** [comment]
... and after a bit of thought ... #flushForScriptGet can/should probably be implemented as a noop ... presumably Iceberg has subclassed MCRepository and decided that the default behavior (noop) was not sufficient? AFAIK only github repositories need to respond to #flushforScriptGet, since this message is supposed to trigger a fresh download of anew zip ball from github ... all other repository should just ignore the message ...

**Comment by dalehenrich** [comment]
... hmmm, so that implies that the pharo folks have decided to fiddle the senders of #flushForScriptGet? if so then they've broken the behavior of github repositories ... as I said very frustrating and not a question from the pharo folks ....

**Comment by jecisc** [comment]
IceMetacelloRepositoryAdapter does not inherit from MCRepository.

https://github.com/npasserini/iceberg/blob/d8ba9d745d1d505dd868250191a2598222b5c198/Iceberg.package/IceMetacelloRepositoryAdapter.class/properties.json

**Comment by dalehenrich** [comment]
If IceMetacelloRepositoryAdaptor is supposed to emulate an MCRepository for Metacello, then it is clear that they need to do a bit more work on their emulation and implement #flushForScriptGet as a noop ... and/or perhaps talk to me about making **supported** changes to Metacello so that they don't have to invent IceMetacelloRepositoryAdaptor in the first place :(

I've been offering to this since last October or so and haven't heard anything back ... right now I am very busy with the release of GemStone 3.4, but back when I first started offering to make Metacello changes I wasn't nearly this busy ... :(

**Comment by estebanlm** [comment]
Hi, @dalehenrich 
There is no reason why we are not using latest Metacello. Just maybe we didn't because were not aware. Also, there is no reason why iceberg shouldn't work with latest Metacello, just... since Iceberg makes some overrides, Iceberg needs to be loaded *after* Metacello, that's all (at least that I know). 
I would want to update Metacello to its latest version, however... so we do not have any problems with it :)

**Comment by dalehenrich** [comment]
Hey @estebanlm, it would be nice if Pharo used the latest Metacello available as part of the build process, so that updates would be automagically included, but I suppose this is just one of the sticky wickets.

However, if Iceberg is overriding Metacello methods that is still a big problem, because it prevents users from being able to independently updating Metacello ... of course overrides are always a bad idea anyway ... 

I will offer once again to see if we can figure out a way to make it so that it isn't necessary for Iceberg to override Metacello methods ... as I said I am very busy right now, but I do have time to discuss the issues involved and if you guys snag the latest Metacello available today, I will only have to worry about Iceberg overrides when I next fix bugs for Metacello --- After I finish all of my work on 3.4 directly I will be spending quality time in Metacello merging my work porting Metacello to the 3.4 base image of GemStone into the master branch and will be able to implement the solutions that we come up for Iceberg as well as make the package code in Metacello tests pluggable (something that Stef has asked me to do...)

**Comment by estebanlm** [comment]
Hi, @dalehenrich 

for the first thing: that can become a reality next year, once we start to use git+bootstrap process.
the second: it would be super cool if you find out how to avoid overrides (which are in fact just two)

- `MetacelloPharoCommonPlatform>>createRepository:`
This is to add this lines: 
```Smalltalk
Smalltalk 
	at: #Iceberg
	ifPresent: [ :cl | 
		(cl enableMetacelloIntegration and: [ IceMetacelloRepositoryType canHandleType: type ])
			ifTrue: [ ^ cl mcRepositoryFor: aRepositorySpec description ] ]. 
```

- `MetacelloPharoCommonPlatform>>extractTypeFromDescription:`
```Smalltalk
ceMetacelloRepositoryType allTypes 
	detect:  [ :each | each isSuitableForLocation: description  ] 
	ifFound: [ :class | ^ class type ].
```

I guess both can be replaced with a proper registry system or something like that.

**Comment by dalehenrich** [comment]
@estebanlm ... perfect ... Is the method for `MetacelloPharoCommonPlatform>>extractTypeFromDescription:` correct? it looks like there might a typo?

I will take a bit of time and look at what I've done for the gs_port stuff as I know I had to monkey in this area as well and then come up with some proposals for you ... THX!

**Comment by jecisc** [comment]
@estebanlm I just try to download a fresh image and a fresh vm and I still get one of the two error.

Here is a video of the manipulation: https://drive.google.com/file/d/0B_KDRvt7h6lYbzdMVEFSOXpyOVE/view?usp=sharing

**Comment by guillep** [comment]
Should not be happening anymore in latest version. Please reopen if necessary
