### ISSUE TITLE
IceHttpsRemote>>#parseUrl does not work with url with more than 2 segments

### ISSUE THREAD

**Issue by jiroasaki** [pharo-vcs/iceberg#331]
The regex ``` 'https\://([\w.]+)/([\w\-]+)/([\w\-]+)(\.git)?' ``` looks exactly for two segments, example.com/user/project and it fails on anything else like example.com/git/user/project. 
I think it would be better to use ZnUrl to parse the url, since it comes with Pharo already and using a regex does not give us any benefits.

**Comment by astares** [comment]
This regex is old and was from npasserini. You use old code. I had the same trouble in the past and therefore already reworked the full HTTPS/HTTP URL support. This was already integrated by Esteban.

Please use a fresh Pharo 6 image and load Iceberg using:

Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg:dev-0.4';
  load.

or 

Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg:dev-0.4';
  load: 'allTests'.

if you need the tests.

In this version you can
 - use full domain urls like on github.com
 - use a local served git (like gogs or other) with any path
 - use HTTP and HTTPs

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
