### ISSUE TITLE
Use git credential for retrieving credentials

### ISSUE THREAD

**Issue by peteruhnak** [pharo-vcs/iceberg#334]
Git has a built-in infrastructure for retrieving credentials ( https://git-scm.com/docs/git-credential.html ) which automatically hooks into system-specific retrieval options (e.g. https://github.com/Microsoft/Git-Credential-Manager-for-Windows ).

Can Iceberg use this to retrieve creds?

That way I wouldn't have to enter credentials in every new image and it also automatically work with 2FA; at the moment I have to manually retrieve 2FA token in console from `git credential`.

**Comment by estebanlm** [comment]
no, but if you have ssh-agent it will work as a charm.
the other... I don't know if libgit2 supports it, in that case it just needs to be implemented as "another" way to retrieve credentials.

**Comment by peteruhnak** [comment]
I am on Windows and using ssh has always been kinda annoying (although bash on windows could improve that).
The "solution" would be to create a windows Process¹ and ask the system's git for credentials. (Also if the system git won't find the credentials, it will invoke native dialog that can also deal with 2FA)

Of course the user needs git in the system, but we could make it opt-in or with a fallback (this is Windows specific anyway).

Are there docs how to add new credential managers, or should I just dig through the code?

---
¹Torsten made a small library to use winapi through UFFI (in catalog under OS-Windows iirc), so that could be of help

**Comment by guillep** [comment]
This is implemented in git, but not in libgit.
We should extend the new credentials manager to access the system credential manager.
