### ISSUE TITLE
http(s) url parser improperly determines project name

### ISSUE THREAD

**Issue by peteruhnak** [pharo-vcs/iceberg#340]
https://github.com/npasserini/iceberg/blob/master/Iceberg.package/IceHttpRemote.class/instance/parseUrl.st

the projectName created from this parser leaves the `.git` suffix in the `projectName`. This breaks loading, because it creates folder with the `.git` suffix, and also it shouldn't be actually part of the name.

* SCP (`projectName = 'repo'`): https://github.com/npasserini/iceberg/blob/master/Iceberg-Tests.package/IceScpRemoteTest.class/instance/testGitHubURL.st
* HTTPS (`projectname = 'repo.git'`): https://github.com/npasserini/iceberg/blob/master/Iceberg-Tests.package/IceHttpRemoteTest.class/instance/testGitHubURL.st

**Comment by astares** [comment]
This URL parser was provided by me (which just is an enhanced regex compared to the one provided by npasserini) in older iceberg versions. It was always the case that the project name could have .git in it or not even with the previous regex. 

So this could not be the reason for your problem: I guess the code for cloning/downloading who creates the .git suffix should be reviewed.

**Comment by peteruhnak** [comment]
Well git clone will trim `.git` when creating the project folder (that seems to be the case whether invoked in the command line, or by using libgit), but iceberg will access the folder by project name, which of course will not exist (because the suffix was trimmed), at least that was my experience

**Comment by estebanlm** [comment]
I found a possible source of problem in the implementation of `IceRemote>>url:`, I will fix it soon, if @astares confirms it :)

**Comment by estebanlm** [comment]
I fixed that on 0.5 :S. So since the branch is still experimental, is not done as to close it

**Comment by estebanlm** [comment]
fixed

**Comment by estebanlm** [comment]
(I backported it to 0.4)
