### ISSUE TITLE
IceMetacelloRepositoryAdatper does not understand isCache

### ISSUE THREAD

**Issue by JurajKubelka** [pharo-vcs/iceberg#343]
Steps to reproduce:

1. Open a Pharo 6 image with Iceberg and some Iceberg repositories
2. Open Versioner and add a new dependent project to a development version
3. A debugger appears

Tested in Pharo 6.0
Latest update: #60477

[stack.txt](https://github.com/pharo-vcs/iceberg/files/990698/stact.txt)

**Solution:**

Add the method

```Smalltalk
IceMetacelloRepositoryAdatper>>#isCache
	"Polymorphic behavior to MCRepository>>#isCache, 
	a method introduced by Komitter.
	Return true, because this repository should be ignored by the Komitter.
	If it returns false, koRemote method is necessary to implement."
	^ true
```

**Comment by astares** [comment]
Also had this once and fixed it the same way ... but later also the method #koRemote was missing

**Comment by jecisc** [comment]
See: https://github.com/pharo-vcs/iceberg/issues/286

**Comment by JurajKubelka** [comment]
duplicate to #286.
