### ISSUE TITLE
Question: Adding packages from another repository

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#344]
I have a stupid problem, maybe I just missed a feature of Iceberg or maybe there is a missing feature somewhere. 

For my case:
I have a "Bazard" repository on STHub and I have a "Bazard" repository on Github. I want to move everything from the STHub one to the github one. I don't care about history.

So what I did is:
- Install Iceberg
- Clone github's Bazard
- Add sthub's bazard
- Load all the packages I needed from sthub's bazard
- In Iceberg use "Add package" to add the loaded packages to github's Bazard

And now... How do I commit them? The sync window show no change. The status is "Up to date"

**Comment by estebanlm** [comment]
this is a known bug (and an important one).
I have in my TODO fix this thing (adding packages should export them and dirty the iceberg repository).
I will try to fix today so is ready before integration.

**Comment by estebanlm** [comment]
fixed
