### ISSUE TITLE
Add a proper message if user.name and user.email git properties are not set

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#361]
if user.name and user.email git properties are not set globally or for the concerned repository, the user will end with a `LGit_GIT_ERROR: Failed to parse signature - Signature cannot have an empty name or email` error and will not be able to commit.
There should be a dialog box advising the user to set these values either with:
```bash
git config [--global] user.name "Firstname Lastname"
git config [--global] user.email "email@company.org"
```

**Comment by estebanlm** [comment]
in fact, the error is there. Is just that this kind of message was not taken (see the senders of IceGitUsernameOrEmailNotFound class). Anyway I will extend the error to this.

**Comment by estebanlm** [comment]
according to me, this is fixed ;)

**Comment by demarey** [comment]
Why not giving the user the information of what to do?
Only have a message like `Config value ''user.name'' was not found` is bit cumbersome for some users.

**Comment by estebanlm** [comment]
if you look at the code, what it actually does is to open a dialog ask for properties and adds them to repo (or global, your choice) and retries.

**Comment by demarey** [comment]
I miss that part in the diff. Looks the right thing to do.
Thanks

**Comment by estebanlm** [comment]
you missed because this is old stuff, what was missing was the message you got (I can not know all messages, and I do not have codes, just some strings to introspect)
