### ISSUE TITLE
Cannot save settings on Windows

### ISSUE THREAD

**Issue by VincentBlondeau** [pharo-vcs/iceberg#365]
I wanted to store the settings under windows, I got a "Can't find the requested origin" error.
The problem seems to be in IceSshCredentials class >>#defaultPublicKey where the reference to the file is not defined.
And by the lazy initialisation of the publicKey IV in IceSshCredentials is not helping, same problem for privateKey.

Moreover, under Windows the .ssh folder do not have a fixed location. I think that a default initialisation is not a good idea.

**Comment by estebanlm** [comment]
store settings? like in settings browser?

**Comment by VincentBlondeau** [comment]
Like in settings browser

**Comment by VincentBlondeau** [comment]
Maybe it is because Win32Environment >> getEnv: primitive is broken...

**Comment by estebanlm** [comment]
yes, I suspected that. 
This is not an iceberg problem :)

**Comment by VincentBlondeau** [comment]
But I cannot save the settings because of iceberg...

**Comment by estebanlm** [comment]
no, is because `Win32Environment>>#getEnv:` is broken :)
it just _happens_ that it explodes in iceberg. But correct fix is to fix Windows getEnv:. 

Now, which VM and image you use? (because that should be fixed).
Execute this to check it: 

```Smalltalk
FileLocator home pathString
```

**Comment by VincentBlondeau** [comment]
-> Error: can't find- the requested origin. I will update the VM

**Comment by VincentBlondeau** [comment]
Ok. It works.
Thanks Esteban :)
