### ISSUE TITLE
Iceberg does not manage the case where we change of branch outside Pharo

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#367]
If I change branch outside Pharo, Iceberg does not detect it. And if I delete the branch after switching, Iceberg will get Red Square Of Death everywhere.

**Comment by estebanlm** [comment]
this will be handled on 0.5

**Comment by estebanlm** [comment]
see #307

**Comment by estebanlm** [comment]
I think this is fixed some time ago
