### ISSUE TITLE
local repository missing when started from a different directory

### ISSUE THREAD

**Issue by rajula96reddy** [pharo-vcs/iceberg#370]
When I run iceberg from the same directory as all the local files, it is all good. But, when I changed the directory and run, something like this `./Pharo/pharo-ui  /Pharo/Pharo60499.image` iceberg gives an error 'local repository missing'.

**Comment by estebanlm** [comment]
this is not an error: you pointed your repository to 

`/your/path/to/pharo/pharo-local/iceberg/user/yourRepo`

then you changed your image location (and I guess all subdir), so you need to point the repository to its new location.
