### ISSUE TITLE
ctrl+s in commit message window no longer works

### ISSUE THREAD

**Issue by peteruhnak** [pharo-vcs/iceberg#371]
It seems that after the [push to origin] checkbox was replaced with button, ctrl+s to commit no longer work...

also I question to decision to replace the checkbox with button; as the button saves time only if pretty much every commit required the opposite behavior (as change of checkbox requires an extra click), and I don't think that's the most common use case.

**Comment by estebanlm** [comment]
problem is that now we cannot know what does it means (commit, or commit and push?)
anyway I'm not happy with the two buttons solution... I'm more like thinking on going back to the checkbox solution, with a remember choice)

**Comment by tesonep** [comment]
Fixed in 0.7
