### ISSUE TITLE
MCClassTraitDefinition needs classCategory implementation

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#378]
MCClassDefinition has an Iceberg extension method named classCategory. The same method needs to be added to MCClassTraitDefinition too. It can cause DNUs when working with traits.

**Comment by j4yk** [comment]
MCClassTraitDefinition is on the meta side, right? Why does it need (or is asked for) a class comment? Shouldn't that be on the non-meta MCTraitDefinition alone?

**Comment by pavel-krivanek** [comment]
not a class comment but category

**Comment by j4yk** [comment]
Sorry, my fault. At first, I thought the same applies to the category because the category of a class trait is the category of the base trait. But having looked at the Monticello classes now, I see the problem.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
