### ISSUE TITLE
Cannot commit changes

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#381]
OS: Windows 7
Pharo: Latest 6

Steps:

- Open Pharo 6
- Open Iceberg
- Add local repository (this repository is on dev-0.5)
- Open IceLocalBranch
- Remove unused variables
- On Iceberg the project show "Uncommited changes"
- Open synch windows
- See no changes and when I commit, the commit is empty

**Comment by estebanlm** [comment]
it is very likely that you need to fetch your repository before. 
can you try that?
(this is because it does not found any merge base in common)

**Comment by jecisc** [comment]
Cannot reproduce in latest Iceberg.
