### ISSUE TITLE
Unpushed commit color is hard to read with the dark theme

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#383]
When I have unpushed commit one Iceberg, the repo is Blue. But it is really hard to read.

**Comment by jecisc** [comment]
Culprit is: IceAbstractModel that does not rely on the Theme.

**Comment by jecisc** [comment]
The problem is that I see nothing usable in the Theme :(

**Comment by jecisc** [comment]
https://pharo.fogbugz.com/f/cases/20249/Add-some-colors-to-the-themes

**Comment by jecisc** [comment]
I proposed to add some colors to Pharo 7 themes. When this will be done we will be able to use them. We can add a Iceberg-Pharo6 package with these methods to not break compatibility.

**Comment by estebanlm** [comment]
done
