### ISSUE TITLE
Iceberg can't handle branch names containing `/` character

### ISSUE THREAD

**Issue by christophmeissner** [pharo-vcs/iceberg#385]
When I add a branch with a name containing one or more `/` characters, as suggested in [git flow](https://danielkummer.github.io/git-flow-cheatsheet/) (ie. `feature/some-feature` or `feature/experimental/experimental-feature`), it is created and checked out correctly but afterwards Iceberg gets confused about the branch name and tries to use only the name component following the last `/`. This results in errors such as being unable to find a fitting remote tracking branch or the local branch itself.

Tried Pharo 6 and 7.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
