### ISSUE TITLE
Add filter field for package tab of repository

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#393]

**Comment by jecisc** [comment]
How do you want to filter? If the name begins with the pattern? If the name includes the pattern?

**Comment by dionisiydk** [comment]
I want same filter like in MonticelloBrowser. It uses "includes the pattern" logic

**Comment by jecisc** [comment]
PR#394 waiting

**Comment by jecisc** [comment]
@estebanlm Done.
