### ISSUE TITLE
Protocol missing on the local repository side of the diff

### ISSUE THREAD

**Issue by Uko** [pharo-vcs/iceberg#400]
When you look at the diff in iceberg the right-hand side (local repo) does not contain the _protocol_ information. As the result, you have 1 more diff line in each diff
![screen shot 2017-07-13 at 11 43 33](https://user-images.githubusercontent.com/817441/28160467-8c89cefa-67c0-11e7-9a6f-0fc5c6f035ce.png)

**Comment by jecisc** [comment]
Monticello uses MCModification>>diffTo(From)Source when Iceberg uses MCModification>>to(from)Source. 

Maybe we should just do as Monticello. 

BTW. I see that Iceberg uses some Monticello classes. In the future it would be good to separate those classes into a package that can be used by both. Ideally we should clean the code inside to be sure to not get some of the Monticello bugs.

**Comment by jecisc** [comment]
Corrected in 605833210c44756cb60f5ab3677092a14e5aaf95

**Comment by jecisc** [comment]
@estebanlm Can be closed
