### ISSUE TITLE
Add checkout operation in commit history view

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#402]
It is usual operation in other IDE to load particular version from history view.
Now there is only possibility to merge into current branch or another branch

**Comment by Uko** [comment]
Also, it would be nice to checkout the currently selected branch (into the image). Because if I need to switch branch I need to switch & do a pull (needless to say that this does not work without network)

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Commit checkout is available.  Please, reopen if this is still an issue with latest version (to be announced)
