### ISSUE TITLE
Iceberg does not detect change if we update extension methods

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#403]
I changed 4 extensions methods but when I want to sync I see no change.

**Comment by jecisc** [comment]
And when I commit, the commit is empty.

**Comment by jecisc** [comment]
Also, this is weird. IceClassChange has the methods from the *Iceberg-UI protocol in the IceClassChange.class -> instance folder and not in the Iceberg-UI.class -> IceClassChange.extension folder. Is that normal?

**Comment by theseion** [comment]
Should be fixed with PR #452 (see issue #450).

**Comment by jecisc** [comment]
No. I still don't see extension methods in the sync view.

**Comment by estebanlm** [comment]
@jecisc I cannot reproduce, can you give me an example?

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
