### ISSUE TITLE
Refactor changes analysis

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#42]
There are some types MCDefinition (specifically: MCOrganizationDefinition, which arises when you create or remove a Tag/Category) that contain no package information, but originally we obtained it from a package, we should refactor the way we compute changes to not loose the package association in the first moment.

This enhancement could become unnecessary if we change the underlying changes model.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Iceberg has a new changes model.
