### ISSUE TITLE
Author name is taken from last commit to repository instead of last commit of package / method

### ISSUE THREAD

**Issue by theseion** [pharo-vcs/iceberg#420]
`IceCommitInfo>>compatibleUsername` generates the author name for an `MCVersion` (package). The author should be the author of the last commit to the package but is currently simply the author of the last commit to the repository.

The same applies to methods which should have the author name of the author of the last commit of the method instead of the author of the current commit. See `IceLibgitVersionReader>>addMethodDefinitionsForClass: className methodProperties:in: extensionMethod:`.

**Comment by estebanlm** [comment]
yes, I'm aware of this... but I'm still searching ways of fixing it :)

**Comment by theseion** [comment]
Something like `git-rev-list` should do the trick.

**Comment by estebanlm** [comment]
yeah, but it does not exists directly on libgit2 (at least at the moment), we need to implement it :(

**Comment by theseion** [comment]
I think it is possible with `git_revwalk`, using the `git_revwalk_hide_cb` callback to stop the iteration. We could use a single revwalk object to find the relevant commits for all paths in one go, instead of walking the graph multiple times. That should be reasonably fast.

**Comment by estebanlm** [comment]
yes, we need to implement something like this: https://github.com/arrbee/libgit2/blob/5e816706038c504d494c78ebd4002da2a065b971/examples/log.c

**Comment by estebanlm** [comment]
I have a fist, very naive implementation here: https://github.com/estebanlm/iceberg/tree/add-log

it allows you to do something like this: 
```Smalltalk
repo := IceRepository registry detect: [ :each | each name = 'iceberg' ]. 
timeStamps := ((repo loadedPackages 
	collect: [ :each | RPackageOrganizer default packageNamed: each packageName ])
	inject: #()
	into: [ :all :each | all, (each methods) ])
	collect: [ :each | 
		each -> ((repo newLog lastModificationOfMethod: each) ifNotNil: #compatibleTimestamp) ]
```

but while this will likely remain as a way to take individual method history, is very unlikely we will use it to set timestamps on projects, because is *very* slow (my tests took something like 4min for taking iceberg methods, and iceberg repo is a lot smaller than pharo itself).

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
