### ISSUE TITLE
Impossible to create branch in a newly created project

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#428]
To reproduce:

I create a new repository, then in the branches tab I wanted to create a new branch but then I get an error `LGit_GIT_EUNBORNBRANCH: Reference 'refs/heads/master' not found`

**Comment by bradacina** [comment]
Happens to me as well. After creating a local repository on Pharo 6.1 running on Windows, I try to create a branch and get that message.

**Comment by guillep** [comment]
This should be fixed in latest
