### ISSUE TITLE
UX improvements: default pull/push remote menu

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#431]
Currently, if I understand correctly, if a remote is a default pull/push remote, the option in the contextual menu is disabled. I think it should not be disabled and if the remote is already the default one we should show an inform to the user with "X is already the default Y remote". When a menu item is disabled we don't know the reason and I was confused at first to see that.

**Comment by jecisc** [comment]
@estebanlm I don't know how to show titles depending on the state of the model and the selected object in GLMGenericAction. Do you know how we can do this?

**Comment by estebanlm** [comment]
meh, maybe it is not possible "as is" (I think we need to change glamour to support it). 
I will check when I'm back from holidays.

**Comment by guillep** [comment]
Not valid anymore. We came back to a system of upstream (as in git) and explicit selection of pull and push branches/remotes.
