### ISSUE TITLE
Synchronizing one repository removes changes from another

### ISSUE THREAD

**Issue by Uko** [pharo-vcs/iceberg#435]
I always run into issues with synchronization. This one is absolutely bizarre.

Look:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/817441/29351806-90f8bed8-8264-11e7-93a8-8b4fffba22b5.gif)

When I open the synchronization window for the second repo, the first one looses changes

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
