### ISSUE TITLE
Pharo 6.1 crashesh on Arch because of libcurl

### ISSUE THREAD

**Issue by TeddyDD** [pharo-vcs/iceberg#436]
I guess Arch Linux has incompatible version of libcurl. When I launch Pharo as it I can't open Iceberg. 
It works with `env LD_PRELOAD='/usr/lib/libcurl.so.3' ./pharo` but it crashes when creating repository.

**Comment by estebanlm** [comment]
but this is more a problem of arch linux packagers than iceberg it self. 
please send a mail to the list (so Alistair, the Arch linux maintainer can take a look).

**Comment by TeddyDD** [comment]
No problem, wasn't sure where to report.
