### ISSUE TITLE
Windows VM Crash on repo synchronize

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#438]
Details see https://pharo.fogbugz.com/f/cases/20323/Windows-VM-Crash-on-repo-synchronize

**Comment by astares** [comment]
Looks like  defect in the synchronizer. This works without any problem on Ubuntu - but crashes the VM on
Windows.

Even when I open Iceberg manually and edit the repo to have the "pharo" repo with the local cloned folder it crashes.

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/29450194-efb42cf6-83fd-11e7-958d-482750ff2136.png)

**Comment by estebanlm** [comment]
this should be fixed on `dev-0.5` (and latest vm)

**Comment by estebanlm** [comment]
latest release (along with latest VM) should fix this problem.

Esteban

**Comment by astares** [comment]
Confirm that it is working, also closed https://pharo.fogbugz.com/f/cases/20323/Windows-VM-Crash-on-repo-synchronize
