### ISSUE TITLE
Pharo 64-bit image freeze when open iceberg on ArchLinux

### ISSUE THREAD

**Issue by badetitou** [pharo-vcs/iceberg#439]
When I try to open iceberg. My image freeze and I got this error (in the terminal)

ioLoadModule(/home/badetitou/Pharo/vms/private/pharo6.1-64/bin/lib/pharo/5.0-201707201942/libgit2.so):
  /lib/libcurl.so.4: version 'CURL_OPENSSL_3' not found (required by /home/badetitou/Pharo/vms/private/pharo6.1-64/bin/lib/pharo/5.0-201707201942/libgit2.so)
/home/badetitou/Pharo/vms/private/pharo6.1-64/bin/lib/pharo/5.0-201707201942/pharo: Relink '/lib/libgit2.so' with `/lib/librt.so.1' for IFUNC symbol 'clock_gettime'

I don't have this issue with Pharo 32-bit

**Comment by erde74** [comment]
start pharo like this 
`
env "LD_PRELOAD=libcurl.so.3" ./pharo
`
