### ISSUE TITLE
Reverting a method in the sync view make all changes disapear

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#445]
In the sync view I wanted to revert the deletion of one method but all the changes desapeared.

**Comment by Uko** [comment]
Maybe this is related to #435. @jecisc were all the changes reverted, or they just disappeared from iceberg?

**Comment by jecisc** [comment]
They just disappeared from Iceberg. Closing and opening the window again solved the problem.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
