### ISSUE TITLE
Cherry picking from multiple packages mixes up methods

### ISSUE THREAD

**Issue by theseion** [pharo-vcs/iceberg#450]

**Comment by estebanlm** [comment]
so, this should close all the others too, isn't?

**Comment by theseion** [comment]
Yes, but I didn't test them.

**Comment by estebanlm** [comment]
@jecisc can you verify?

**Comment by jecisc** [comment]
This week I can check 440 and 403 but 442 is random and I don't remember how to reproduce it.
