### ISSUE TITLE
Working on a newly added local "pharo" repo will produce error upon commit

### ISSUE THREAD

**Issue by theseion** [pharo-vcs/iceberg#453]
The "pharo" "system repository" is hidden by default but is associated with all of the pharo packages. Adding a new repository to use for development will appear to work in Iceberg but upon commit the packages are processed with the "system repository" who's `location`, `pushUrl` and `pullUrl` are uninitialized.

Workaround: go to settings and check the box for showing "system repositories", then edit the "pharo" repository to point to the desired local "pharo" repository.

@estebanlm This is quite critical to the integration process

**Comment by estebanlm** [comment]
yes, but this is not a "workaround", this is how you have to do it :)

**Comment by theseion** [comment]
Wow... I was so sure that it was not in the documentation... As we say in Switzerland: "tomatoes on the eyes"... 

I agree. However, I think that Iceberg should ask the user which repository is to be used when a package can belong to more than one.

**Comment by estebanlm** [comment]
well, yes... but is not so easy :)

**Comment by theseion** [comment]
Why not? You're a wizard, aren't you? 😁 You can close this issue if you want.

**Comment by estebanlm** [comment]
ok :)
