### ISSUE TITLE
Iceberg fails to parse valid URLs

### ISSUE THREAD

**Issue by Rydier** [pharo-vcs/iceberg#457]
$- are valid in URL paths; the regexp in IceHttpRemote >> #parseUrl fails to allow this, for instance: 'http://my-company.com:8085/company-gitrepo/_git/our-project.git'.
There are plenty other characters that are allowed which will cause the regexp to fail though; rather than keep extending it (to make it pass for my specific case to:
'((http|https)\://)(([\w]+)@)*([\w\-.]+)(\:([\d]+))*(/[\w\-]+)*/([\w\-]+)/([\w\-]+(.git)?)' ), maybe it'd be a good idea to instead extract the relevant parts from an actual url object created by sending #asZnUrl? (and handling the appropriate errors that may raise)

**Comment by peteruhnak** [comment]
The part prior to `@` should be extended too to include credentials, e.g.

`https://username:password@example.com/repo/repo.git`

**Comment by zecke** [comment]
Could we please use ZnUrl for parsing URLs? We fail to parse valid SSH urls as well (e.g. when a port is given). Also assuming that "git@" is the only valid log-in name is.. far fetched...

I see three cases:

url starts with / => local file
url has no scheme => ssh
url is a proper url..

I think ZnUrl>>#fromString:defaultScheme: comes in handy..

**Comment by zecke** [comment]
I can see two different issues:

* Parsing URLs with Regexp while we have ZnUrl.
* The assumption of owner/repo (which applies to Github, Stash/Bitbucket, Gitlab but no self hosted system). I think Iceberg shouldn't care too much

**Comment by estebanlm** [comment]
I think we can consider this solved.
