### ISSUE TITLE
Commit and push when two Iceberg windows are opened

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#465]
Just try to do it. And the synch process at the end of commit will never finish. Progress bar will continue updates and generally everything looks weird in that case.
Fortunately changes are not lost. You can close windows and progress bars and reopen Iceberg. Then you will see that push was not performed but commit is fine.

**Comment by guillep** [comment]
Stale. Please, reopen if this is still an issue with latest version (to be announced)
