### ISSUE TITLE
Commiting via Iceberg does not commit package removal

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#468]
I am contributing to Pharo and I get a problem. 

I am currently renaming packages so I do this:
- I rename the package
- I add it to the project via the packages tab of Iceberg
- I remove from the disk the old package via the same tab
- I change the baseline referencing this package
- I commit

Then in the command line `git status` tell me that the removal of the package was not commited and I have to add it manually and to amend the commit. 

This is on Windows 7 - Latest Pharo 7 (alpha.build.151.sha.9be75a5f73d858a3a2d621652cdc820cddf9fd7e)

**Comment by jecisc** [comment]
Now I get an error:

`SubclassResponsibility: IceTipRemoveFromRepositoryPackageCommand had the subclass responsibility to implement #execute`

**OS**

Windows 10

**Pharo**

60540

**Iceberg**

0.7.2

**Comment by guillep** [comment]
This was fixed as part of #556
