### ISSUE TITLE
Metacello script never checkout/switch to requested branch/tag/commit

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#479]
On fresh environment (no pharo-local/iceberg) try to load concrete version of project. For example:
```Smalltalk
Metacello new
  baseline: 'Commander';
  repository: 'github://dionisiydk/Commander:v0.2.2';
  load
```
After loading is finished try load the dev branch:
```Smalltalk
Metacello new
  baseline: 'Commander';
  repository: 'github://dionisiydk/Commander:dev';
  load
```
You will see that nothing happens. Dev branch of Commander should load extra dependency ClassAnnotation. But it not happens.

The problem is that Metacello script always use existing local copy without any switching/loading requested branch/tag/commit.

Generally it happens also with dependencies of project. Imaging that you manually load some old version of ClassAnnotation. And then you load Commander with script above. The ClassAnnotation will be not updated. And no notification will be shown

**Comment by apblack** [comment]
I have this problem too.  My packages depend on the _working_ branch of `SmaCC`.  But metacello loads whichever branch happens to be current in the local clone of the repo.

If the local repo is not up-to-date with the remote specified in the configuration, should metacell change the local repo  —  this sounds dangerous!  Would it not be better to simply fetch from the specified url?

**Comment by apblack** [comment]
It seems to be even worse than I thought.  If there is a _local clone_ of the repo, Metacello loads from taht oacl clone ... even if it is 4 versions behind the remote repository!   I was not getting fixes that I knew had been made on the master branch and pushed to github: this is why.

**Comment by estebanlm** [comment]
I think this is solved but it is on my revamp UI branch... but it will be ready for 0.7 release.
