### ISSUE TITLE
Primitive failed: primitive #createDirectory:in WindowsStore failed

### ISSUE THREAD

**Issue by vitormcruz** [pharo-vcs/iceberg#483]
On windows, when I try to clone I get:

> WindowsStore(Object)>>primitiveFailed:
> WindowsStore(Object)>>primitiveFailed
> WindowsStore(DiskStore)>>createDirectory:
> WindowsStore(FileSystemStore)>>ensureCreateDirectory:
> FileSystem>>ensureCreateDirectory:
> FileReference>>ensureCreateDirectory
> IceRepositoryCreator>>createNewRepositoryNamed:
> [ | repository |
> self projectName isEmptyOrNil
> 	ifTrue: [ Error signal: 'Project name is required' ].
> repository := IceRepositoryCreator new
> 	location: self location / self projectName;
> 	subdirectory: subdirectory text;
> 	createNewRepositoryNamed: self projectName.
> repository register.
> self window delete.
> acceptBlock ifNotNil: [ acceptBlock cull: self ] ] in IceNewRepositoryModel>>createRepository in Block: [ | repository |...
> BlockClosure>>on:do:
> IceNewRepositoryModel>>createRepository
> [ self createRepository ] in IceNewRepositoryModel(IceCreateRepositoryModel)>>initializePresenter in Block: [ self createRepository ]
> ButtonModel>>performAction
> MorphicButtonAdapter>>action
> PluggableButtonMorph>>performAction:
> [ :m | 
> (m containsPoint: evt cursorPoint)
> 	ifTrue: [ m enabled
> 			ifTrue: [ m performAction: evt ] ] ] in PluggableButtonMorph>>mouseUp: in Block: [ :m | ...
> Array(SequenceableCollection)>>do:
> PluggableButtonMorph>>mouseUp:
> PluggableButtonMorph(Morph)>>handleMouseUp:
> MouseButtonEvent>>sentTo:
> PluggableButtonMorph(Morph)>>handleEvent:
> PluggableButtonMorph(Morph)>>handleFocusEvent:
> [ ActiveHand := self.
> ActiveEvent := anEvent.
> result := focusHolder
> 	handleFocusEvent: (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear: in Block: [ ActiveHand := self....
> BlockClosure>>on:do:
> WorldMorph(PasteUpMorph)>>becomeActiveDuring:
> HandMorph>>sendFocusEvent:to:clear:
> HandMorph>>sendEvent:focus:clear:
> HandMorph>>sendMouseEvent:
> HandMorph>>handleEvent:
> HandMorph>>processEventsFromQueue:
> HandMorph>>processEvents

**Comment by estebanlm** [comment]
when you try to clone what?

**Comment by vitormcruz** [comment]
https://github.com/vitormcruz/Katas-and-Challenges-ST.git.

This happens in a new fresh image, in an older one (2 weeks +-) I got a LGit_ERROR and a FFIExtgernalStructureReferenceHandle.

**Comment by estebanlm** [comment]
I have no problem on cloning that on Windows. 
e.g. 
![screen shot 2017-10-11 at 13 27 07](https://user-images.githubusercontent.com/513630/31438432-6337bf12-ae88-11e7-878f-c1af2a74d3b8.png)

I'm quite sure you tried to clone the full repository and you expected to have access to all subdirs from there. That's a "multi-directory-sources" feature Iceberg not currently supports.
version 0.7 of Iceberg will have that feature, but it will not be here until one month or so.

In the meantime, you need to rejoin all packages from your project into a single subdirectory.
