### ISSUE TITLE
Failing cloning behind a proxy

### ISSUE THREAD

**Issue by vitormcruz** [pharo-vcs/iceberg#486]
I configured proxy appropriately,  Zinc works fine, for example, the command:

    http://zn.stfx.eu/zn/small.html' asZnUrl retrieveContents.

works properly. When I try to clone https://github.com/vitormcruz/Katas-and-Challenges-ST.git (which I changed to have all code inside pharo folder) I got the following message:

> LGit_GIT_ERROR: failed to send request: A connection qieth the server could not be stabilished

Debugging it I got to this point: 

    clone: out url: url local_path: local_path options: options
     
     ^ self
      callUnchecked:
       #(LGitReturnCodeEnum git_clone (LGitRepository *out, String url, String local_path, 
                                           LGitCloneOptions *options))
      options: #(optCoerceNilToNull)

This seams like a call to a native C code. The opts has an authentication callback, which should be called, but it is not. From Pharo Mailing list Guillermo Polito gave me some leads and I can tell that when I inspect:

    options prim_fetch_opts prim_proxy_opts prim_type

I get a “a LGitProxyTypeEnum(#git_proxy_none [0])”. It seems that no proxy is being used even if the system is configured to use one.

If needed I could help fixing it, but I would need some leads as I have no idea on where to start looking at or how to to provide a fix if I find one (should a create a branch? use Monticello? Copy the solution here?)

**Comment by vitormcruz** [comment]
I managed to make it work by putting the following code at the end of both `LGitCloneOptions>>initializeWithDefaults` and  `LGitFetchOptions>>initializeWithDefaults`:

    self prim_fetch_opts prim_proxy_opts prim_type: LGitProxyTypeEnum git_proxy_auto.

It must be at the end because `#fetch_init_options:version:` somewhat changes the `LGitProxyTypeEnum`.

**Comment by guillep** [comment]
Hi @vitormcruz, it looks like this is a libgit issue?

If so it should go here: https://github.com/pharo-vcs/libgit2-pharo-bindings

Would you try making a pull request?

**Comment by vitormcruz** [comment]
Hello @guillep, it don't seems so. `#fetch_init_options:version:` appears to load default lib2git options, and if I change that options accordingly lib2git works as expected. The problem is that Iceberg don't appears to be making this configuration in accordance with the system configuration — or maybe it does, but at a wrong time, it should do that after `LGit***Options` configuration initialization (I think).

I think Iceberg should configure proxy auto by default and maybe provide specific configuration for proxy, which may use system configuration or another specified for Iceberg only. Proxy auto, however, is good enough for most situations, as people are used to configure git proxy when needed, so specific proxy configuration can de-prioritized for a much later time.

What do you think?

I don't know the best way of configuring proxy auto, what I did may cover some cases, maybe changing  `#fetch_init_options:version:` so that the inner FFI initializes git options with proxy auto? I, however, didn't dig into how to do that.

**Comment by estebanlm** [comment]
it is a libgit2 issue, but well. 
looks like we can add this as default?

**Comment by estebanlm** [comment]
it will be incorporated in next release (0.6.2)... even if it is something from libgit2 :P
