### ISSUE TITLE
Pulling on a repository moves the HEAD back

### ISSUE THREAD

**Issue by tesonep** [pharo-vcs/iceberg#494]
When there is branch with a commit that is not in the pull repository and a Pull is performed, the HEAD is moved back to the previous commit without giving an error. It should give an error.

Steps to reproduce.

1. Have a branch that is in a remote repository. It should have commit1, and commit2.
2. Make a new commit (commit3) in the branch from the command line.
3. In an image with loaded commit1, perform a pull.

**Comment by guillep** [comment]
This is working on dev 0.7
