### ISSUE TITLE
Unclear how to do the first commit in Iceberg

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#498]
A friend tried to create its first project via Iceberg and got a problem. 

What he did:

- Create a project on gitlab
- Clone it and add a readme
- Open Iceberg and add as subfolder `src` because this is the subfolder he wants

And now he gets an error saying that there is a problem with the repository. To make it work we needed to first create by hand the `src` folder on the disk. This is not user friendly.

**Comment by estebanlm** [comment]
yeah, problem is because he created without src then he tried to add with that. 
I think this can be easily fixed.

**Comment by jecisc** [comment]
He created it via the gitlab interface then cloned it without Pharo. So there is no src directory.

**Comment by estebanlm** [comment]
I know. Now, I think if location is a valid location but subdir does not exists, maybe we should create it.

**Comment by jecisc** [comment]
At least open a dialog asking to the user if he wants to initialize the subdirectory or to abort the addition of the repository.

**Comment by astares** [comment]
Remember that as long as src folder is empty you can not commit it as git ignores empty folders.
But one can work with an empty .keep file

https://www.git-tower.com/learn/git/faq/add-empty-folder-to-version-control

**Comment by tesonep** [comment]
Commit 1d98011 fixes some problems with empty repositories.
Now 0.7 can handle it well.
The default operation is to guide you to add a package.
