### ISSUE TITLE
Unable to load a Gitlab private project

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#499]
I tried to load a private project with this script:

```Smalltalk
Metacello new
        repository: 'gitlab://yannlesage/arangoForPharo';
        baseline: 'ArangoForPharo';
        load
```

When I execute it I am asked for my ssh keys but I already added them in my settings. Also when I add the keys in the wizard I get an assertion failure because the key files does not exists. When I inspect them I see that they are not the path I gave but "Path to the image"/"name of the ssh key file".

**Comment by estebanlm** [comment]
this is not an error. 
but you need to declare it like this: ssh://git@url:port/team/project.git

**Comment by estebanlm** [comment]
unless that does not works then please reopen :)
