### ISSUE TITLE
Ensure that all possible modifications to code are supported

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#5]
We might look at the hierarchy of MCDefinition for a guide to completeness.

**Comment by tesonep** [comment]
I have found that when you add or remove a Category (not a package, a tag) it does not work because is sending the message #category. 
I could commit using the MCRepository adaptor, so I think is only a problem of the UI.

**Comment by estebanlm** [comment]
this does not has sense anymore (or I do not understand it). 
it should be covered, or iceberg wouldn't be working.
