### ISSUE TITLE
bad left/right diff names when browsing at the history of a branch

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/iceberg#505]
When looking at the history of a branch, the two windows are labelled “Left:working copy / Right: incoming updates”.  This is wrong: the two labels should be “working copy” and “selected commit <commitid>” (the one selected in the commits pane) and prior commit.   If one selects the “Changes vs. parent” tab, then the two labels should be “Parent commit <commitid>” and “selected commit <commitid>”

**Comment by tesonep** [comment]
Fixed in Related #597
