### ISSUE TITLE
Cannot resolve "4 incoming"

### ISSUE THREAD

**Issue by apblack** [pharo-vcs/iceberg#510]
Iceberg tells me that there are 4 incoming commits.  This is due to commits being made to github (edits to the `travis.yml` file) that Iceberg does not know about.  And then I rebased one commit that iceberg had made on top of these commits from github.

OK, so it's reasonable for Iceberg not to know about these external commits.  But how do I get Iceberg to realize that the code it has is actually up to date?  

The synchronize window, in the "commit your changes" tab, shows zero differences.  Pull incoming commits appears to do nothing, leaving me with the message that there are 4 incoming commits.

**Comment by estebanlm** [comment]
this is already fixed but still not published (I will release in two weeks when I comeback)
