### ISSUE TITLE
Pullrequest tool is broken because of //

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#515]
newRequestTo: aString
	^ ZnClient new 
		in: [ :this | 
			self credentials ifNotNil: [ 
				this 
					username: self credentials username 
					password: self credentials password ] ]; 
		headerAt: 'Accept' put: 'application/vnd.github.v3+json';
		url: 'https://api.github.com/', aString;
		yourself

url: parameter is https://api.github.com//borken.....'

Denis proposed: 

url: ('https://api.github.com/' asUrl / aString asUrl) aString ;

**Comment by estebanlm** [comment]
this was solved on #496
but it is still not in the image, I will prepare a merge.
