### ISSUE TITLE
Iceberg can't find changes

### ISSUE THREAD

**Issue by apblack** [pharo-vcs/iceberg#518]
This may be the same issue as #293.

Iceberg's main window says that I have uncommitted changes.  But when I do a "Synchronize repository" or "Synchronize full repository", no changes are found.  Even after that, Iceberg still says that I have uncommitted changes.

This can happen even after I have made some changes: Iceberg seems not to find them, and then of course can't commit them.

**Comment by jecisc** [comment]
I think it's corrected in v0.7. @guillep

**Comment by guillep** [comment]
Part of it is fixed, yes. If there are changes, Iceberg will effectively find them now.

However, sometimes there are false positives (show that you have changes and you don't because you reverted them). This issue is managed here https://github.com/pharo-vcs/iceberg/issues/773
