### ISSUE TITLE
Created and then deleted method causes walkback during Synchronize

### ISSUE THREAD

**Issue by apblack** [pharo-vcs/iceberg#520]
While working on a package (SmaCC-Tests), I created a method `#testUnderstandingOfStreamPosition`, which I later deleted and renamed to `#testUnderstandingOfPosition`.

When I try to do a _synchronize_, or a _synchronize full_, using Iceberg, to try to commit this (and other) changes, I get a walkback:

    KeyNotFound: key #testUnderstandingOfStreamPosition not found in MethodDictionary

which of course is entirely correct, because that method no longer exists.  

The problem is in an instance of RPackage which has a dictionary `classDefinedSelectors`, with one element for my test class being `#testUnderstandingOfStreamPosition`.  If I repeat the synchronize operation, the _same instance_ of RPackage is used, containing the same outdated information.

Clearly Iceberg needs to flush its cache and rebuild a current representation of the package before it tries to do a synchronize.

P.S.  I don't know if this is relevant, but I'm using Calypso.  There are 177 `ClyEnvironmentItems` that all have references to this same `RPackage` instance.

**Comment by guillep** [comment]
This issue should not be valid anymore in latest version
