### ISSUE TITLE
Package view do not show packages with only extensions

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#539]
For example try load Commander:
```Smalltalk
Metacello new
  baseline: 'Commander';
  repository: 'github://dionisiydk/Commander:770dd56f505ea99d6ecb70a91f1c7ca0d45b43c0';
  load
```
There is package Commander-SpecSupport. You will not see it in package view.
It is not in default baseline. But it is not matter

**Comment by guillep** [comment]
This is tonel problem apparently, please move the issue there (https://github.com/pharo-vcs/tonel/issues)
