### ISSUE TITLE
Revert changes unselect and fold all elements

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#541]
**Pharo version:**

Pharo-7.0+alpha.build.389.sha.e642e96a93951b2765dc808a512b81dc3d52e150 (32 Bit)

**OS:**

Windows 10

**VM:**

C:\Users\JeCisC\Documents\Pharo\vms\70-x86\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2265 uuid: 76b62109-629a-4c39-9641-67b53321df9a Aug 27 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2262 uuid: 8b531242-de02-48aa-b418-8d2dde0bec6c Aug 27 2017
VM: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Sun Aug 27 21:55:26 2017 +0200 $ Plugins: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Win32 built on Aug 27 2017 20:40:46 GMT Compiler: 5.4.0
VMMaker versionString VM: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Sun Aug 27 21:55:26 2017 +0200 $ Plugins: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog-eem.2265 uuid: 76b62109-629a-4c39-9641-67b53321df9a Aug 27 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2262 uuid: 8b531242-de02-48aa-b418-8d2dde0bec6c Aug 27 2017

**Action:**

I deleted some methods and during the synchronisation I wanted to revert some of those changes.

**Expected:**

I expected the method to be recompiled and just the entry of this method to be removed from the sync window

**Actual:**

The method was removed but all the checkboxes were unselected and all classes were folded.

**Comment by guillep** [comment]
@estebanlm to consider for the new UI.

**Comment by estebanlm** [comment]
I think this is like that in the new UI (there is currently a bug when refreshing... bah, when *not* refreshing ;), but I will take care of that before release.

**Comment by peteruhnak** [comment]
I wouldn't mind having normal staging area, but maybe people don't like having another (useful) git concept :)

**Comment by estebanlm** [comment]
no stage area, sorry :)
