### ISSUE TITLE
Bug during commit of a new package

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#542]
**Pharo version:**

Pharo-7.0+alpha.build.389.sha.e642e96a93951b2765dc808a512b81dc3d52e150 (32 Bit)

**OS:**

Windows 10

**VM:**

C:\Users\JeCisC\Documents\Pharo\vms\70-x86\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2265 uuid: 76b62109-629a-4c39-9641-67b53321df9a Aug 27 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2262 uuid: 8b531242-de02-48aa-b418-8d2dde0bec6c Aug 27 2017
VM: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Sun Aug 27 21:55:26 2017 +0200 $ Plugins: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Win32 built on Aug 27 2017 20:40:46 GMT Compiler: 5.4.0
VMMaker versionString VM: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Sun Aug 27 21:55:26 2017 +0200 $ Plugins: 201708271955 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog-eem.2265 uuid: 76b62109-629a-4c39-9641-67b53321df9a Aug 27 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2262 uuid: 8b531242-de02-48aa-b418-8d2dde0bec6c Aug 27 2017

**Action:**

I wanted to separate the "Alien" package of Pharo between "Alien" and "Alien-Tests". 

- I created the branch for the operation
- In the declaration of "AlienSunit" I changed the category for: `category: 'Alien-Tests'`
- Since the class was now in a subcategory of the package, I did a right click on it and selected "promote as package"
- I added the new package to the "pharo" repository in Iceberg via the "Packages" tab
- I opened the synch view
- I tried to commit

**Expected:**

I expected the commit to be done

**Actual:**

I got an error. See screen attached.

![ss 2017-12-16 at 10 39 05](https://user-images.githubusercontent.com/9519971/34074598-d55b8296-e2b2-11e7-9499-40c69c465d7a.png)

**Comment by guillep** [comment]
I cannot reproduce this issue in dev 0.7. (Same Alien scenario)
Let's wait until version 0.7 is out.

**Comment by jecisc** [comment]
I got the problem another time and I saw that in general commiting a new package fail, but commiting a new package with the "synchronize full repository" works.

**Comment by jecisc** [comment]
I tried in Iceberg v0.7.1 to commit a new package and I got no problem. I'm ok to close the issue if there is no other reason to have it in the milestone 0.7.2.
