### ISSUE TITLE
In merge window removed methods are not taken into account

### ISSUE THREAD

**Issue by noha** [pharo-vcs/iceberg#543]
If I have two merge incoming and outgoing changes, every change that is the removal of a method will not be reflected and re-added when merge is done.

**Comment by guillep** [comment]
This should be fixed in v0.7. We have properly written and tested the merge algorithm and used internally for a couple of weeks without losing any code.

**Comment by noha** [comment]
Can I use v0.7 with pharo 6.1?

**Comment by guillep** [comment]
Not sure, I've not tested it. But since Esteban is rewriting the UI, currently the old UI in the dev branch is missing all refreshes (which is a bit annoying but not critical)

**Comment by guillep** [comment]
I don't think this is valid anymore. If you see it again, please re-open.
