### ISSUE TITLE
Pull does not seem to work correctly 

### ISSUE THREAD

**Issue by georgeganea** [pharo-vcs/iceberg#544]
Usecase: making commits in a repo both from Pharo and from outside.
How to reproduce:
1. Commit from outside, push.
2. Commit from Pharo, pull then push.
A merge commit happens (which is expected) but then the changes in that commit overwrite the first commit.
Any pointers to where this is implemented? I'd like to take a look.

The about box does not show the iceberg version, so no clue as to which exact version I'm running.

**Comment by guillep** [comment]
Fixed in dev-0.7 branch. We changed with Pablo the merge algorithm. If you want to take a look, check

`IceSingleVersionWorkingCopyState>>mergeCommit: aCommit`
