### ISSUE TITLE
Give more info to the user during a checkout

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#547]
I opened Iceberg on Pharo repository. This repo was on master. In the branches tab I ask to checkout the development branch. I had to wait for at least 1min and I had no information that something was happening. 

There should be more user notification on long action like this. 

Also at the end I was on the development branch, but Iceberg still displayed "master" until I clicked on another project.

**Comment by astares** [comment]
Yes - this is a little bit annoying as one does not know if the image is stuck or the long git actions
like checkout still run.

I once talked to Esteban about that on Discord. The git library itself allows for callbacks to register to get informed about activity - and it might be possible to display a progress bar. For time reasons this has not yet been done.

**Comment by jecisc** [comment]
I guessed it was for this reason. But I still opened the issue to keep it in mind :)

**Comment by guillep** [comment]
@estebanlm to consider for the new UI.

**Comment by guillep** [comment]
The new UI has improved a bit (I hope) on user feedback. There should be more progress bars here and there, and I hope the previews before a checkout and merge also have a positive effect.

I'll close this issue, let's reopen it, or better open a more concrete one with particular cases if we find one.
