### ISSUE TITLE
Iceberg should satisfy testWorldMenuHasHelpForAllEntries

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#548]
Currently the release builds of Pharo 7 are not green because there is a release
test #testWorldMenuHasHelpForAllEntries that is not satisfied by Iceberg yet.

A help text is required for each item in the world menu. 

It can be fixed using:

```Smalltalk
menuCommandOn: aBuilder 
    "Add a custom menu item to the world menu"    
    <worldMenu> 
    
    (aBuilder item: #'Iceberg')
        order: 0.8; 
        icon: self icon;  
        parent: #'MostUsedTools';
        help: 'Tools for source code management in git';
        keyText: 'o, i';
        action: [ self open ].
```

**Comment by jecisc** [comment]
It is already integrated in Iceberg.

**Comment by jecisc** [comment]
https://github.com/pharo-vcs/iceberg/pull/538

We just wait for the next release.

**Comment by guillep** [comment]
Already in 7851b4feb7d3ba1665a4449b07ea16845b79fabd and integrated in latest Pharo since several days.
