### ISSUE TITLE
LGit_GIT_ERROR: error authenticating: failed connecting agent

### ISSUE THREAD

**Issue by elbow** [pharo-vcs/iceberg#552]
Hi,

I attempt to clone a repository from Github.  The one I used for a test was elbow/catch, but same behaviour with all I tried whether public or private.

My platform is Windows 10.  Pharo 6.1 updated via System>Software update to #60528:

> Image
> -----
> C:\Users\steve\Documents\Pharo\images\SmartHome\SmartHome.image
> Pharo6.0
> Latest update: #60528
> Unnamed
> 
> Virtual Machine
> ---------------
> C:\Users\steve\Documents\Pharo\vms\61-x86\Pharo.exe
> CoInterpreter VMMaker.oscog-eem.2254 uuid: 4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
> StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017
> VM: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 20 12:42:21 2017 -0700 $ Plugins: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
> 
> Win32 built on Jul 20 2017 20:21:26 GMT Compiler: 5.4.0
> VMMaker versionString VM: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 20 12:42:21 2017 -0700 $ Plugins: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
> CoInterpreter VMMaker.oscog-eem.2254 uuid: 4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
> StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017
> 

In my Iceberg settings the only thing I changed from default was to insert my github username and password.  

When cloning I get this error: LGit_GIT_ERROR: error authenticating: failed connecting agent

`Author: StephenDavies

LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
[ | repo cloneOptions |
repo := LGitRepository on: self location.
cloneOptions := LGitCloneOptions
	withCredentialsProvider: IceCredentialsProvider default.
cloneOptions checkoutOptions
	checkoutStrategy: LGitCheckoutStrategyEnum git_checkout_none.
repo clone: url options: cloneOptions.
repo
	checkout:
		(aBranchName
			ifNil:
				[ self branch ifNotNil: [ :b | b name ] ifNil: [ 'master' ] ]).
(LGitRemote of: repo named: 'origin')
	lookup;
	setUrl: url ] in IceLibgitLocalRepository>>cloneRepositoryFrom:branch:
[ self checkInitialized.
aBlock value ] in LGitGlobal class>>runSequence:
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in LGitActionSequence(DynamicVariable)>>value:during:
BlockClosure>>ensure:
LGitActionSequence(DynamicVariable)>>value:during:
LGitActionSequence class(DynamicVariable class)>>value:during:
LGitGlobal class>>runSequence:
IceLibgitLocalRepository>>cloneRepositoryFrom:branch:
IceRepositoryCreator>>createRepository
[ | repository |
repository := IceRepositoryCreator new
	remote: (IceRemote url: remoteUrl text trim);
	location: self location;
	subdirectory: subdirectory text;
	createRepository.
self configureRepository: repository.
self window delete ] in IceCloneRepositoryModel>>createRepository
BlockClosure>>on:do:
IceCloneRepositoryModel>>createRepository
[ self createRepository ] in IceCloneRepositoryModel(IceCreateRepositoryModel)>>initializePresenter
ButtonModel>>performAction
MorphicButtonAdapter>>action
PluggableButtonMorph>>performAction:
[ :m | 
(m containsPoint: evt cursorPoint)
	ifTrue: [ m enabled
			ifTrue: [ m performAction: evt ] ] ] in PluggableButtonMorph>>mouseUp:
Array(SequenceableCollection)>>do:
PluggableButtonMorph>>mouseUp:
PluggableButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
PluggableButtonMorph(Morph)>>handleEvent:
PluggableButtonMorph(Morph)>>handleFocusEvent:
[ ActiveHand := self.
ActiveEvent := anEvent.
result := focusHolder
	handleFocusEvent: (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>on:do:
WorldMorph(PasteUpMorph)>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
HandMorph>>processEventsFromQueue:
HandMorph>>processEvents
[ :h | 
self activeHand: h.
h processEvents.
self activeHand: nil ] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess`

Scratching in the debugger, LGitRespository#clone:options:to: does this:
`	self withReturnHandlerDo: [ 
		self 
			clone: self
			url: aString
			local_path: aFileReference pathString
			options: cloneOptions ]`

Calling #value on that block returns a LGitReturnCodeEnum with value -1

**Comment by estebanlm** [comment]
hi, 
Currently windows agent is not working, and you need to set your credentials manually. Something like this: 
```Smalltalk
IceCredentialsProvider useCustomSsh: true.
IceCredentialsProvider sshCredentials
	publicKey: 'path\to\ssh\id_rsa.pub';
	privateKey: 'path\to\ssh\id_rsa'
```

**Comment by estebanlm** [comment]
no, is not duplicated, I cannot not find the original issue

**Comment by estebanlm** [comment]
but proper fix of this is complicated since we need to implement the windows security mechanism on libgit2 (since what does not works properly on windows is ssh-agent)

**Comment by elbow** [comment]
Hi,

I was able to get this to work as suggested. For some reason my existing key for ssh wouldn't work, but I generated a new pair and I'm in business.

Thanks.

As a suggestion, it would have saved time if the issue was in the FAQ in the Readme.md.

Regards,
Steve
