### ISSUE TITLE
Unable commit new added package

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#554]
On any existing project try add new package (which is not managed by any repo yet).
Then try commit. You will got error that new package is not found .
Then if you will reopen Iceberg you will find that new package is not anymore in the list of packages. But in that state it is ok to repeat this scenario from the start - commit will be successful.

Even worth detail:
If you have other changes in addition to new package addition then first commit error will reset changes without any possibility to see that nothing was committed. And they will not be committed when you at second time will add new package.
To commit such lost changes you need manually make given packages dirty.

**Comment by jecisc** [comment]
I got it too.

**Comment by guillep** [comment]
Duplicates #542. Let's continue the discussion there.
