### ISSUE TITLE
Removed packages are not removed from git

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#556]
Now unload and remove package command do not remove it from git

**Comment by guillep** [comment]
@estebanlm was this ever implemented? I'm testing the IceTipUnloadAndRemovePackageCommand and it does not have an `execute` method. And I cannot find it in the history of the class...

**Comment by guillep** [comment]
I've implemented a remove package dialog in 61304aec3536ac5df8a86341e6e9eaa84fc4aae4 and also implemented package removal in general
 - removed packages appear in diff
 - there is an option to unload them from the image

**Comment by jecisc** [comment]
Great! This is one of the most important core piece missing :)
