### ISSUE TITLE
Crash when selecting a new commit to be imported

### ISSUE THREAD

**Issue by pisareks** [pharo-vcs/iceberg#567]
Hi Guys

When I try to import a new commit from a local repository, the VM crashes.
I use Pharo 6.1 with the default Iceberg (on Windows 10).

![capture](https://user-images.githubusercontent.com/10025581/35615095-7a19a808-0671-11e8-8775-61601ddae3c3.PNG)

**Comment by astares** [comment]
At a minimum you should give details on your VM and image configuration. Otherwise nobody will be able to reproduce.

Just go to world menu -> System Reporter, you just need to copy the infos on **Image** and **Virtual Machine**

**Comment by pisareks** [comment]
Here you are:

Image
-----
C:\Users\pisareks\Desktop\dhp\Pharo6.1 - ginger\Pharo6.1.image
Pharo6.0
Latest update: #60513
Unnamed

Virtual Machine
---------------
C:\Users\pisareks\Desktop\dhp\Pharo6.1 - ginger\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2254 uuid: 4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017
VM: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 20 12:42:21 2017 -0700 $ Plugins: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Win32 built on Jul 20 2017 20:21:26 GMT Compiler: 5.4.0
VMMaker versionString VM: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Thu Jul 20 12:42:21 2017 -0700 $ Plugins: 201707201942 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog-eem.2254 uuid: 4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017
StackToRegisterMappingCogit VMMaker.oscog-eem.2252 uuid: 2f3e9b0e-ecd3-4adf-b092-cce2e2587a5c Jul 20 2017

**Comment by astares** [comment]
Can you try latest VM from 27.11.2017:
http://files.pharo.org/get-files/70/pharo-win-latest.zip

**Comment by pisareks** [comment]
I still get a fatal error when using the VM provided:
[image: Inline images 1]

**Comment by pisareks** [comment]
But I have a workaround: I manually reload packages. So this issue is a low priority for me.

**Comment by guillep** [comment]
Do you still have this issue? It would be good to have an exact way to reproduce it.

- Does the commit you want to import have pharo code?
- Or just external files modifications (e.g., Readme.md files)
- Your image was in sync with the repo? In which commit?

I'll put this issue as invalid until there are some reproduction instructions.
