### ISSUE TITLE
create branch command  should also switch to the new branch

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#569]
I think it is common scenario that when we create branch we want switch to it.

**Comment by guillep** [comment]
It is actually like that by default. I've just tested it in

Pharo-7.0+alpha.build.498.sha.1daa984b0b2d01e7dc220b3017e23213303fd5a1 (32 Bit)

Maybe there is a bug, if you have a good way to reproduce it, just reopen the issue.

**Comment by dionisiydk** [comment]
Ok, I create another issue #570. Problem is about updating UI
