### ISSUE TITLE
Metacello script should keep local branches if necessary

### ISSUE THREAD

**Issue by JurajKubelka** [pharo-vcs/iceberg#572]
Hi @dionisiydk, @estebanlm, and @apblack!

Reading the issue #479, I am wondering what happens if someone works on a new version of an application. Let's take an example of the Calypso browser: 

Calypso has dependency on Commander and ClassAnnotation. Let's say that I am doing changes simultaneously in all three repositories, Calypso, Commander, and ClassAnnotation. In all three cases in `dev` branches. 

And now I want to test the changes in a new Pharo image. So, I will download a fresh Pharo image and execute: 

```Smalltalk
Metacello new
  baseline: 'Calypso';
  repository: 'github://dionisiydk/Calypso:dev';
  load
```

What will happen? The Calypso packages will be loaded from the `dev` branch. From my understanding, as the Calypso's baseline does have references to particular versions of Commander and ClassAnnotation, e.g,. master branch or 0.8.x tags. It means, with the changes done in #479, I will end up with the Pharo image including the dev branch of Calypso, and stable branches of Commander and ClassAnnotation. Right? In other words, I will have a broken Calypso development version.

So, the point is, that the #479 change makes impossible to easily download development versions. Am I right? Or do I miss something? 

So, I propose having something like this: 

```Smalltalk
Iceberg useLocalRepositoriesWhile: [
  Metacello new
    baseline: 'Calypso';
    repository: 'github://dionisiydk/Calypso:dev';
    load
]
```

I propose this, instead of `Iceberg useLocalRepositories: true` as it may be difficult to remember to switch it off for other projects.

What do you think?

**Comment by estebanlm** [comment]
well, I already implemented something using the metacello API: 

Metacello new
	baseline: 'Calypso';
	repository: 'github://dionisiydk/Calypso:dev';
	onUpgrade: [ :e | e useLoaded. “or #useIncoming” ];
	load

that should solve the problems, but I’m still not convinced of the API (because is more oriented to in image changes). Maybe I will work on this but using something like #localVersion and #checkoutVersion) .
anyway, this will be ready just for 0.7 :/

Esteban

**Comment by dalehenrich** [comment]
Hmmm, the Metacello lock command is intended to be used to identify 
those projects with local git clones,
   Metacello new
     baseline: 'Calypso';
     repository: '???';
     lock.
   Metacello new
     baseline: 'Commander';
     repository: '???';
     lock.
   Metacello new
     baseline: 'ClassAnnotation';
     repository: '???';
     lock.

but in an iceberg universe, I don't know know how you specify the local 
repositories - If they are on disk you can use tonel:.... or filetree://.

The lock command can be used with unloaded repositories and have the 
effect of unconditionally using the locked version of a project when 
referenced as a project dependency from another project.

You could have a startup action that locked the projects for which you 
have local clones and then you wouldn't have to manually run the lock 
commands for the projects you are working on ...

I would assume that iceberg would automatically lock the projects that 
are cloned locally as well, then there wouldn't need to be any fancy 
load commands to "get what you want" ...

Dale

**Comment by guillep** [comment]
Hi Dale,

Yes, Iceberg was so far "locking" your projects in disk by default (and without asking). The problem is that then the following scenario behaves strangely:
 - you have a local clone of Seaside (branch X checked out). Seaside is not in your image.
 - you download a project App that depends on Seaside v3.0.3.
 - Iceberg will silently install whatever is checked out in your repository instead of what is asked by App.

**Comment by dalehenrich** [comment]
So yes ... in tODE the project list provides a view of all projects known to the image and indicates which ones are locked ... now Metacello does provide notifications when locks are honored, so it may be that the the loader (yes I imagine the one should not run naked Metacello smalltalk expressions either) can be configured to handle these notifications during the load, to further interact with the developer ... if seaside hasn't been loaded then the developer should be given the choice of honoring the lock (they intend to use the locked version of seaside for this app) or to not honor the lock and go ahead and Seaside 3.0.3 ... with Seaside already loaded they don't have much choice, but they should be notified nonetheless ...
