### ISSUE TITLE
Error when trying to open "Synchronize repository..."

### ISSUE THREAD

**Issue by pisareks** [pharo-vcs/iceberg#573]
![image](https://user-images.githubusercontent.com/10025581/35928927-a487479a-0c2e-11e8-95c8-ad5cac5e5dc5.png)

Author: szymon

IceLibgitVersionReader(Object)>>error:
IceLibgitVersionReader(MCFileTreeStCypressReader)>>validateExtensionMethodCategory:for:selector:
[ :fileStream | 
| category source timestamp selector |
category := fileStream nextLine.
source := fileStream upToEnd.
selector := self methodSelectorFor: source.
timestamp := methodProperties
	at:
		(classIsMeta
			ifTrue: [ 'class' ]
			ifFalse: [ 'instance' ])
	ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
timestamp
	ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
			, self info time print24 ].
extensionMethod
	ifTrue: [ self
			validateExtensionMethodCategory: category
			for: className
			selector: selector ].
definitions
	add:
		(MCMethodDefinition
			className: className
			classIsMeta: classIsMeta
			selector: selector
			category: category
			timeStamp: timestamp
			source: source) ] in [ :methodEntry | 
methodEntry
	readStreamDo: [ :fileStream | 
		| category source timestamp selector |
		category := fileStream nextLine.
		source := fileStream upToEnd.
		selector := self methodSelectorFor: source.
		timestamp := methodProperties
			at:
				(classIsMeta
					ifTrue: [ 'class' ]
					ifFalse: [ 'instance' ])
			ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
		timestamp
			ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
					, self info time print24 ].
		extensionMethod
			ifTrue: [ self
					validateExtensionMethodCategory: category
					for: className
					selector: selector ].
		definitions
			add:
				(MCMethodDefinition
					className: className
					classIsMeta: classIsMeta
					selector: selector
					category: category
					timeStamp: timestamp
					source: source) ] ] in [ :entry | 
| classIsMeta |
classIsMeta := false.
entry name = 'class'
	ifTrue: [ classIsMeta := true ].
(entry name = 'instance' or: [ entry name = 'class' ])
	ifTrue: [ ((self fileUtils directoryFromEntry: entry) entries
			select: [ :each | each name endsWith: '.st' ])
			do: [ :methodEntry | 
				methodEntry
					readStreamDo: [ :fileStream | 
						| category source timestamp selector |
						category := fileStream nextLine.
						source := fileStream upToEnd.
						selector := self methodSelectorFor: source.
						timestamp := methodProperties
							at:
								(classIsMeta
									ifTrue: [ 'class' ]
									ifFalse: [ 'instance' ])
							ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
						timestamp
							ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
									, self info time print24 ].
						extensionMethod
							ifTrue: [ self
									validateExtensionMethodCategory: category
									for: className
									selector: selector ].
						definitions
							add:
								(MCMethodDefinition
									className: className
									classIsMeta: classIsMeta
									selector: selector
									category: category
									timeStamp: timestamp
									source: source) ] ] ] ] in IceLibgitVersionReader(MCFileTreeStCypressReader)>>addMethodDefinitionsForClass:methodProperties:in:extensionMethod:
LGitTreeEntry>>readStreamDo:
[ :methodEntry | 
methodEntry
	readStreamDo: [ :fileStream | 
		| category source timestamp selector |
		category := fileStream nextLine.
		source := fileStream upToEnd.
		selector := self methodSelectorFor: source.
		timestamp := methodProperties
			at:
				(classIsMeta
					ifTrue: [ 'class' ]
					ifFalse: [ 'instance' ])
			ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
		timestamp
			ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
					, self info time print24 ].
		extensionMethod
			ifTrue: [ self
					validateExtensionMethodCategory: category
					for: className
					selector: selector ].
		definitions
			add:
				(MCMethodDefinition
					className: className
					classIsMeta: classIsMeta
					selector: selector
					category: category
					timeStamp: timestamp
					source: source) ] ] in [ :entry | 
| classIsMeta |
classIsMeta := false.
entry name = 'class'
	ifTrue: [ classIsMeta := true ].
(entry name = 'instance' or: [ entry name = 'class' ])
	ifTrue: [ ((self fileUtils directoryFromEntry: entry) entries
			select: [ :each | each name endsWith: '.st' ])
			do: [ :methodEntry | 
				methodEntry
					readStreamDo: [ :fileStream | 
						| category source timestamp selector |
						category := fileStream nextLine.
						source := fileStream upToEnd.
						selector := self methodSelectorFor: source.
						timestamp := methodProperties
							at:
								(classIsMeta
									ifTrue: [ 'class' ]
									ifFalse: [ 'instance' ])
							ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
						timestamp
							ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
									, self info time print24 ].
						extensionMethod
							ifTrue: [ self
									validateExtensionMethodCategory: category
									for: className
									selector: selector ].
						definitions
							add:
								(MCMethodDefinition
									className: className
									classIsMeta: classIsMeta
									selector: selector
									category: category
									timeStamp: timestamp
									source: source) ] ] ] ] in IceLibgitVersionReader(MCFileTreeStCypressReader)>>addMethodDefinitionsForClass:methodProperties:in:extensionMethod:
Array(SequenceableCollection)>>do:
[ :entry | 
| classIsMeta |
classIsMeta := false.
entry name = 'class'
	ifTrue: [ classIsMeta := true ].
(entry name = 'instance' or: [ entry name = 'class' ])
	ifTrue: [ ((self fileUtils directoryFromEntry: entry) entries
			select: [ :each | each name endsWith: '.st' ])
			do: [ :methodEntry | 
				methodEntry
					readStreamDo: [ :fileStream | 
						| category source timestamp selector |
						category := fileStream nextLine.
						source := fileStream upToEnd.
						selector := self methodSelectorFor: source.
						timestamp := methodProperties
							at:
								(classIsMeta
									ifTrue: [ 'class' ]
									ifFalse: [ 'instance' ])
							ifPresent: [ :map | map at: selector asString ifAbsent: [  ] ].	"Issue 33: https://github.com/dalehenrich/filetree/issues/33"
						timestamp
							ifNil: [ timestamp := self info author , ' ' , self info date mmddyyyy , ' '
									, self info time print24 ].
						extensionMethod
							ifTrue: [ self
									validateExtensionMethodCategory: category
									for: className
									selector: selector ].
						definitions
							add:
								(MCMethodDefinition
									className: className
									classIsMeta: classIsMeta
									selector: selector
									category: category
									timeStamp: timestamp
									source: source) ] ] ] ] in IceLibgitVersionReader(MCFileTreeStCypressReader)>>addMethodDefinitionsForClass:methodProperties:in:extensionMethod:
Array(SequenceableCollection)>>do:
IceLibgitVersionReader(MCFileTreeStCypressReader)>>addMethodDefinitionsForClass:methodProperties:in:extensionMethod:
IceLibgitVersionReader(MCFileTreeStCypressReader)>>addExtensionClassAndMethodDefinitionsFromEntry:
[ :entry | 
(entry name endsWith: '.trait')
	ifTrue: [ self addTraitAndMethodDefinitionsFromEntry: entry ].
(entry name endsWith: '.class')
	ifTrue: [ self addClassAndMethodDefinitionsFromEntry: entry ].
(entry name endsWith: '.extension')
	ifTrue: [ self addExtensionClassAndMethodDefinitionsFromEntry: entry ] ] in IceLibgitVersionReader(MCFileTreeStCypressReader)>>addClassAndMethodDefinitionsFromDirectory:
Array(SequenceableCollection)>>do:
IceLibgitVersionReader(MCFileTreeStCypressReader)>>addClassAndMethodDefinitionsFromDirectory:
IceLibgitVersionReader(MCFileTreeStCypressReader)>>loadDefinitions
IceLibgitVersionReader(MCVersionReader)>>definitions
IceLibgitVersionReader(MCVersionReader)>>snapshot
IceLibgitVersionReader(MCFileTreeStCypressReader)>>basicVersion
IceLibgitVersionReader(MCVersionReader)>>version
[ ^ (IceLibgitVersionReader on: commit iceVersion: iceVersion) version ] in [ :repo | 
| commit |
commit := LGitCommit
	of: repo
	fromId: (LGitId fromHexString: iceVersion commit id).
[ ^ (IceLibgitVersionReader on: commit iceVersion: iceVersion) version ]
	on: IceMissingRepositoryEntry
	do: [ IceVersionDoesNotExist new
			version: iceVersion;
			signal ] ] in IceLibgitLocalRepository>>mcVersionFor:
BlockClosure>>on:do:
[ :repo | 
| commit |
commit := LGitCommit
	of: repo
	fromId: (LGitId fromHexString: iceVersion commit id).
[ ^ (IceLibgitVersionReader on: commit iceVersion: iceVersion) version ]
	on: IceMissingRepositoryEntry
	do: [ IceVersionDoesNotExist new
			version: iceVersion;
			signal ] ] in IceLibgitLocalRepository>>mcVersionFor:
[ | repo |
repo := (LGitRepository on: self location) open.
aBlock value: repo ] in IceLibgitLocalRepository>>withRepoDo:
[ self checkInitialized.
aBlock value ] in LGitGlobal class>>runSequence:
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in LGitActionSequence(DynamicVariable)>>value:during:
BlockClosure>>ensure:
LGitActionSequence(DynamicVariable)>>value:during:
LGitActionSequence class(DynamicVariable class)>>value:during:
LGitGlobal class>>runSequence:
IceLibgitLocalRepository>>withRepoDo:
IceLibgitLocalRepository>>mcVersionFor:
IceSavedPackageVersion>>mcVersion
[ self mcVersion snapshot ] in IceSavedPackageVersion(IceAbstractVersion)>>snapshot
BlockClosure>>on:do:
IceSavedPackageVersion(IceAbstractVersion)>>snapshot
IceLoadedCode>>snapshotFor:
IceDiff>>theirSnapshot:
IcePackageChangeSet>>basicChanges
IcePackageChangeSet>>analyseChanges
IcePackageChangeSet>>changes
IcePackageChangeSet>>initialElements
IcePackageChangeSet(IceAbstractDiff)>>elements
IcePackageChangeSet>>hasChanges
ByteSymbol(Symbol)>>value:
[ :stream | 
1 to: self size do: [ :index | 
	(aBlock value: (each := self at: index))
		ifTrue: [ stream nextPut: each ] ] ] in Array(SequenceableCollection)>>select:
Array class(SequenceableCollection class)>>new:streamContents:
Array(SequenceableCollection)>>select:
IceDiffCherryPickChangeTreeBuilder(IceDiffChangeTreeBuilder)>>elements
[ self elements ] in IceDiffCherryPickChangeTreeBuilder>>buildOn:
BlockClosure>>glamourValueWithArgs:
BlockClosure(ProtoObject)>>glamourValue:
GLMCherryPickTreePresentation(GLMPresentation)>>displayValue
GLMCherryPickTreePresentation(GLMListingPresentation)>>displayValue
GLMCherryPickTreeDataSource(GLMFastTreeDataSource)>>basicRoots
GLMCherryPickTreeDataSource(GLMFastTreeDataSource)>>createRootItem
GLMCherryPickTreeDataSource(GLMFastTreeDataSource)>>rootItem
GLMCherryPickTreeDataSource(FTTreeDataSource)>>numberOfRows
FTTableMorph>>numberOfRows
FTTableContainerMorph>>calculateStartIndexWhenShowing:
FTTableContainerMorph>>updateExposedRows
FTTableMorph>>resetPosition
FTTableMorph>>dataSource:
GLMMorphicCherryPickTreeRenderer(GLMMorphicFTRenderer)>>initializeTableMorph
GLMMorphicCherryPickTreeRenderer(GLMMorphicFTRenderer)>>render:
GLMMorphicCherryPickTreeRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderCherryPickTreePresentation:
GLMCherryPickTreePresentation>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderObject:
[ self renderObject: each ] in [ :each | 
tabs
	addLazyPage: [ self renderObject: each ]
	label: (self titleOrIconOf: each in: tabs)
	toolbar: (self renderToolbarForPresentation: each inMorph: tabs)
	action: (self labelActionBrickFor: each) ] in GLMMorphicTabbedRenderer>>render:
LazyTabPage>>actualPageMorph
LazyTabGroupMorph>>pageAt:
LazyTabGroupMorph>>updatePageIndex:
LazyTabGroupMorph(TabGroupMorph)>>update:
LazyTabGroupMorph(Object)>>update:with:
MorphChangedWithArguments>>deliverTo:
LazyTabGroupMorph(Morph)>>handleUpdate:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver:
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt:
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
Announcer>>announce:
GLMTabSelectorBrick(Morph)>>doAnnounce:
GLMTabSelectorBrick(Morph)>>changed:with:
GLMTabSelectorBrick>>selectedIndex:
LazyTabGroupMorph(TabGroupMorph)>>selectedPageIndex:
[ tabs selectedPageIndex: index ] in GLMMorphicTabbedRenderer>>render:
BlockClosure>>ensure:
GLMAnnouncer>>suspendAllWhile:
GLMMorphicTabbedRenderer>>render:
GLMMorphicTabbedRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabbedCompositePresentation:
GLMTabbedArrangement>>renderGlamorouslyOn:
GLMCompositePresentation>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicPaneRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicPaneRenderer>>renderContainerFor:
GLMMorphicPaneRenderer>>render:
GLMMorphicPaneRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderPane:
GLMPane>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabulatorRenderer(GLMMorphicWidgetRenderer)>>renderObject:
[ :index :each | 
each hasId
	ifTrue: [ pane := self renderObject: (aBrowser paneNamed: each id) ]
	ifFalse: [ pane := GLMMorphic containerMorph.
		self
			renderCustomColumn: each
			ofPane: aPane
			inUI: pane
			inBrowser: aBrowser.
		pane addPaneSplitters ].
pane
	layoutFrame:
		(LayoutFrame new
			topFraction: 0 offset: 0;
			leftFraction: currentSpanPosition / totalSpans
				offset: currentOffset + self margin;
			bottomFraction: 1 offset: 0;
			rightFraction: (currentSpanPosition + each span) / totalSpans
				offset: currentOffset + each size - self margin;
			yourself).
aMorph addMorphBack: pane.
currentSpanPosition := currentSpanPosition + each span.
currentOffset := currentOffset + each size ] in GLMMorphicTabulatorRenderer>>renderCustomRow:ofPane:inUI:inBrowser:
OrderedCollection(SequenceableCollection)>>keysAndValuesDo:
GLMMorphicTabulatorRenderer>>renderCustomRow:ofPane:inUI:inBrowser:
[ :index :each | 
each hasId
	ifTrue: [ pane := self renderObject: (aBrowser paneNamed: each id) ]
	ifFalse: [ pane := GLMMorphic containerMorph.
		self
			renderCustomRow: each
			ofPane: aPane
			inUI: pane
			inBrowser: aBrowser.
		pane addPaneSplitters ].
pane
	layoutFrame:
		(LayoutFrame new
			topFraction: currentSpanPosition / totalSpans
				offset: currentOffset + self margin;
			leftFraction: 0 offset: 0;
			bottomFraction: (currentSpanPosition + each span) / totalSpans
				offset: currentOffset + each size - self margin;
			rightFraction: 1 offset: 0;
			yourself).
aMorph addMorphBack: pane.
currentSpanPosition := currentSpanPosition + each span.
currentOffset := currentOffset + each size ] in GLMMorphicTabulatorRenderer>>renderCustomColumn:ofPane:inUI:inBrowser:
OrderedCollection(SequenceableCollection)>>keysAndValuesDo:
GLMMorphicTabulatorRenderer>>renderCustomColumn:ofPane:inUI:inBrowser:
GLMMorphicTabulatorRenderer>>render:
GLMMorphicTabulatorRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabulator:
GLMTabulator>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderWithTitleOrNil:
GLMMorphicTabbedRenderer>>render:
GLMMorphicTabbedRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabbedCompositePresentation:
GLMTabbedArrangement>>renderGlamorouslyOn:
IceGlamourCommitBrowser(GLMCompositePresentation)>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderWithTitleOrNil:
GLMMorphicTabbedRenderer>>render:
GLMMorphicTabbedRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabbedCompositePresentation:
GLMTabbedArrangement>>renderGlamorouslyOn:
GLMCompositePresentation>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicPaneWithoutTitleRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicPaneWithoutTitleRenderer>>renderMorphFor:
GLMMorphicPaneWithoutTitleRenderer>>render:
[ GLMMorphicPaneWithoutTitleRenderer new
	renderer: self renderer;
	render: each ] in [ :each | 
self flag: 'add toolbar'.
tabs
	addLazyPage: [ GLMMorphicPaneWithoutTitleRenderer new
			renderer: self renderer;
			render: each ]
	label: (self titleOrIconOf: each presentations in: tabs)
	toolbar: (self renderToolbarForPresentation: each presentations inMorph: tabs) ] in GLMMorphicStackerRenderer>>render:
LazyTabPage>>actualPageMorph
LazyTabGroupMorph>>pageAt:
LazyTabGroupMorph>>updatePageIndex:
LazyTabGroupMorph(TabGroupMorph)>>update:
LazyTabGroupMorph(Object)>>update:with:
MorphChangedWithArguments>>deliverTo:
LazyTabGroupMorph(Morph)>>handleUpdate:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver:
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt:
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
Announcer>>announce:
GLMTabSelectorBrick(Morph)>>doAnnounce:
GLMTabSelectorBrick(Morph)>>changed:with:
GLMTabSelectorBrick>>selectedIndex:
LazyTabGroupMorph(TabGroupMorph)>>selectedPageIndex:
GLMMorphicStackerRenderer>>render:
GLMMorphicStackerRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderStacker:
GLMStacker>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicTabbedRenderer(GLMMorphicWidgetRenderer)>>renderWithTitleOrNil:
GLMMorphicTabbedRenderer>>render:
GLMMorphicTabbedRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>renderTabbedCompositePresentation:
GLMTabbedArrangement>>renderGlamorouslyOn:
IceGlamourSynchronizer(GLMCompositePresentation)>>renderGlamorouslyOn:
GLMMorphicRenderer(GLMRenderer)>>render:
GLMMorphicWindowRenderer(GLMMorphicWidgetRenderer)>>renderObject:
GLMMorphicWindowRenderer>>render:
GLMMorphicWindowRenderer class(GLMMorphicWidgetRenderer class)>>render:from:
GLMMorphicRenderer>>open:
IceGlamourSynchronizer(GLMCompositePresentation)>>openWith:
IceGlamourSynchronizer(GLMCompositePresentation)>>openOn:with:
IceGlamourSynchronizer(GLMCompositePresentation)>>openOn:
IceGlamourSynchronizer class>>synchronize:
IceRepositoryModel>>synchronize
MessageSend>>value
MessageSend>>cull:
[ :presentation | 
presentation selection
	ifNotNil: [ :sel | 
		(MessageSend receiver: sel selector: actionSelector)
			cull: presentation ] ] in GLMGenericAction>>selectionAction:
BlockClosure>>glamourValueWithArgs:
GLMGenericAction(GLMAction)>>actOn:
GLMGenericAction(GLMAction)>>morphicActOn:
[ :ann | ann action morphicActOn: aPresentation ] in GLMMorphicFastTableRenderer(GLMMorphicWidgetRenderer)>>installActionsOnModel:fromPresentation:
BlockClosure>>cull:
BlockClosure>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver:
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt:
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
GLMAnnouncer(Announcer)>>announce:
GLMAnnouncer>>announce:
GLMFastTableDataSource(GLMFastListDataSource)>>executeMenuAction:
[ | selArgCount |
"show cursor in case item opens a new MVC window"
(selArgCount := selector numArgs) = 0
	ifTrue: [ target perform: selector ]
	ifFalse: [ selArgCount = arguments size
			ifTrue: [ target perform: selector withArguments: arguments ]
			ifFalse: [ target perform: selector withArguments: (arguments copyWith: evt) ].
		self showShortcut ].
self changed ] in ToggleMenuItemMorph(MenuItemMorph)>>invokeWithEvent:
BlockClosure>>ensure:
CursorWithMask(Cursor)>>showWhile:
ToggleMenuItemMorph(MenuItemMorph)>>invokeWithEvent:
ToggleMenuItemMorph(MenuItemMorph)>>mouseUp:
ToggleMenuItemMorph(MenuItemMorph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
ToggleMenuItemMorph(Morph)>>handleEvent:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseUp:
MouseButtonEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
ToggleMenuItemMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseUp:
MouseButtonEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
MenuMorph(Morph)>>processEvent:using:
MenuMorph(Morph)>>processEvent:
MenuMorph>>handleFocusEvent:
[ ActiveHand := self.
ActiveEvent := anEvent.
result := focusHolder
	handleFocusEvent: (anEvent transformedBy: (focusHolder transformedFrom: self)) ] in HandMorph>>sendFocusEvent:to:clear:
BlockClosure>>on:do:
WorldMorph(PasteUpMorph)>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
HandMorph>>processEventsFromQueue:
HandMorph>>processEvents
[ :h | 
self activeHand: h.
h processEvents.
self activeHand: nil ] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess

**Comment by pisareks** [comment]
Image
-----
C:\Users\pisareks\Desktop\dhp\Pharo6.1 - ginger\Pharo6.1.image
Pharo6.0
Latest update: #60513
Unnamed

Virtual Machine
---------------
C:\Users\pisareks\Desktop\dhp\Pharo6.1 - ginger\Pharo.exe
CoInterpreter VMMaker.oscog- nice.2281 uuid: 4beeaee7-567e-1a4b-b0fb-bd95ce302516 Nov 27 2017
StackToRegisterMappingCogit VMMaker.oscog-nice.2283 uuid: 2d20324d-a2ab-48d6-b0f6-9fc3d66899da Nov 27 2017
VM: 201711262336 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Mon Nov 27 00:36:29 2017 +0100 $ Plugins: 201711262336 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $

Win32 built on Nov 27 2017 00:05:42 GMT Compiler: 6.4.0
VMMaker versionString VM: 201711262336 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Mon Nov 27 00:36:29 2017 +0100 $ Plugins: 201711262336 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
CoInterpreter VMMaker.oscog- nice.2281 uuid: 4beeaee7-567e-1a4b-b0fb-bd95ce302516 Nov 27 2017
StackToRegisterMappingCogit VMMaker.oscog-nice.2283 uuid: 2d20324d-a2ab-48d6-b0f6-9fc3d66899da Nov 27 2017

**Comment by guillep** [comment]
Hi, can you provide more information on this? Is the project you're loading public? if so, that would help to share it with the instructions to reproduce the problem.

Usually, this error may happen because the repository is corrupt. If we check that, we can see how to fix/patch the repository.

Also, usually this problem should not happen in the next release (v0.7) but without instructions to reproduce it it is complicated.
