### ISSUE TITLE
Use "utilities" method protocol (instead of "utils") for IceLibgitLocalRepository

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#580]
IceLibgitLocalRepository class>>#verifyBackendAvailabilityIfNot: 
IceLibgitLocalRepository class>>#requiredLibGit2MinimumVersion

should be in "utilities" method protocol instead of just "utils" like
any other utilities method.

See https://pharo.fogbugz.com/f/cases/21447/Use-utilities-method-protocol-instead-of-utils-for-IceLibgitLocalRepository

**Comment by estebanlm** [comment]
this will not be valid on 0.7 because there is no IceLibgitLocalRepository anymore :)
