### ISSUE TITLE
Recompile package command for package tab

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#581]

**Comment by guillep** [comment]
Does not "Reload package" do it?

**Comment by dionisiydk** [comment]
It reloads code from local copy which of course recompiles it but in case of dirty packages it resets changes.

**Comment by guillep** [comment]
But why would you need so? Because there is some broken binding?

Then I don't see why it should be Iceberg's responsibility and not for example calypso's?

**Comment by dionisiydk** [comment]
Good idea. I will add it.
There was same feature in Monticello. That's why I expect it here too.
