### ISSUE TITLE
DefaultFileFormatType return an Object instead of a format

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#582]
Pharo version: 60536

VM: C:\Users\JeCisC\Documents\Pharo\vms\61-x86\Pharo.exe
CoInterpreter VMMaker.oscog-eem.2254 uuid: 4f2c2cce-f4a2-469a-93f1-97ed941df0ad Jul 20 2017

OS: Windows 7

Problem:

IceRepository class variable named DefaultFileFormatType is set by default with "an Object". This cause a bug when trying to create a new repository.

Here is the stack:

```
Object>>doesNotUnderstand: #asSymbol
IceRepository class>>defaultFileFormat
IceRepositoryCreator>>formatToUse
IceRepositoryCreator>>addPropertiesFileTo:
IceRepositoryCreator>>createNewRepositoryNamed:
[ | repository |
self projectName isEmptyOrNil
	ifTrue: [ Error signal: 'Project name is required' ].
repository := IceRepositoryCreator new
	location: self location / self projectName;
	subdirectory: subdirectory text;
	createNewRepositoryNamed: self projectName.
repository register.
self window delete.
acceptBlock ifNotNil: [ acceptBlock cull: self ] ] in IceNewRepositoryModel>>createRepository in Block: [ | repository |...
BlockClosure>>on:do:
IceNewRepositoryModel>>createRepository
[ self createRepository ] in IceNewRepositoryModel(IceCreateRepositoryModel)>>initializePresenter in Block: [ self createRepository ]
ButtonModel>>performAction
MorphicButtonAdapter>>action
PluggableButtonMorph>>performAction:
```

**Comment by guillep** [comment]
How did you arrive to that case? There is no code setting that variable to "an Object". I was checking in the history, but that variable is set to `nil` by default since commit 033fe211e73adac934e5d145fa9b442e7760b041

**Comment by jecisc** [comment]
@guillep Juste download a Pharo 61 image (I did it via the PharoLauncher) and inspect IceRepository defaultFileFormatType

**Comment by guillep** [comment]
Duplicates #579

**Comment by guillep** [comment]
I'll close this one. Please, let's continue the conversation in the other issue..
