### ISSUE TITLE
Creating a tonel project does not commit the properties file

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#583]
Detected in: v0.6.8 

Problem:

When creating a tonel repository it will generate a .properties file which tell that the project is a tonel project. 

The problem is that this file is not commited when we do our first commit. If we commit then try to load the project through Metacello we get an obscure error. "BaselineOfXXX not resolved"

**Comment by guillep** [comment]
The following workaround should work for people working on older versions:
- If you just created your repository, go to the terminal, `git add` the `.properties` file and `git commit`it.
- If you are loading a metacello baseline, you'll probably have to fix your repository first. As soon as you import your repository in iceberg, Iceberg will create the `.properties` file for you. Commit it from the command line as in the point above.

**Comment by guillep** [comment]
This is already working and now tested in 0.7.3
