### ISSUE TITLE
Metacello fails in the context of missing git repositories

### ISSUE THREAD

**Issue by igordejanovic** [pharo-vcs/iceberg#585]
This happened while trying to install `Brick` in a clean `Moose` 6.1 image. The image used several git repos. The Exception raised is:
```
Instance of IceUnknownBranch did not understand #versionFor:
```
Here is a screenshot that depicts the situation:
![brik_bloc_install_problem](https://user-images.githubusercontent.com/1673425/37555578-f36ffafe-29e9-11e8-9d18-6ef57bdab7fc.png)

The workaround is to "forget" all missing repos.

**Comment by guillep** [comment]
This issue is superseeded by https://github.com/pharo-vcs/iceberg/issues/949.
Also note that that version of iceberg is not supported anymore.
Please upgrade to latest 1.*
