### ISSUE TITLE
Possible incompatibilities when loading a new package from a repository from which we already loaded other packages.

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#59]
```
loadLatest
    "Warning: loading the latest version of a package could be tricky if there are other packages from the same repository already loaded in the image, with incompatible versions. We should check that situation and produce an alert."
    (repository latestVersionForPackage: package) load.

    repository announcer announce: IcePackageLoaded new.
    repository refresh
```

**Comment by npasserini** [comment]
The default operation should be to load the compatible version of the rest of the packages in the repository (or latest if there are none and no specific version is requested).

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Each Iceberg package handles now its own packages independently of monticello and of other iceberg packages. So it can handle dirtyness on its own.
