### ISSUE TITLE
Iceberg uncaught error when user.name and user.email are not set

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#614]
From @demarey:

The error pops up when your git repository does not have user.name and user.email set

LGit_GIT_ERROR: Failed to parse signature - Signature cannot have an empty name or email

LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>defaultSignature
[ signature := repo defaultSignature ] in [ :repo |
| signature commitId indexTreeId |
[ signature := repo defaultSignature ]
        on: LGit_GIT_ENOTFOUND
        do:
                [ :e | IceGitUsernameOrEmailNotFound guessKind: e ifNot: [ e pass ] ].
indexTreeId := repo index writeTreeAndReturnOid.
commitId := (LGitCommitBuilder of: repo)
        tree: (LGitTree of: repo fromId: indexTreeId);
        message: message withUnixLineEndings utf8Encoded;
        parents:
                (repo isUnborn
                        ifTrue: [ #() ]
                        ifFalse: [ self libGitCommitsFrom: repo for: parentCommits ]);
        "'HEAD' branch could not exist yet. No problem, libgit will create it,
                        but we have to remember it to notify the frontend."
                updateReference:
                ([ repo head name ]
                        on: LGit_GIT_EUNBORNBRANCH
                        do: [ 'refs/heads/' , repository branch nameForFirstCommit ]);
        author: signature;
        committer: signature;
        writeCommit;
        commitId.
^ repository
        commitFromGitCommit: (LGitCommit of: repo fromId: commitId) ] in IceGitIndex>>commitWithMessage:andParents: in Block: [ signature := repo defaultSignature ]
BlockClosure>>on:do:
[ :repo |
| signature commitId indexTreeId |
[ signature := repo defaultSignature ]
        on: LGit_GIT_ENOTFOUND
        do:
                [ :e | IceGitUsernameOrEmailNotFound guessKind: e ifNot: [ e pass ] ].
indexTreeId := repo index writeTreeAndReturnOid.
commitId := (LGitCommitBuilder of: repo)
        tree: (LGitTree of: repo fromId: indexTreeId);
        message: message withUnixLineEndings utf8Encoded;
        parents:
                (repo isUnborn
                        ifTrue: [ #() ]
                        ifFalse: [ self libGitCommitsFrom: repo for: parentCommits ]);
        "'HEAD' branch could not exist yet. No problem, libgit will create it,
                        but we have to remember it to notify the frontend."
                updateReference:
                ([ repo head name ]
                        on: LGit_GIT_EUNBORNBRANCH
                        do: [ 'refs/heads/' , repository branch nameForFirstCommit ]);
        author: signature;
        committer: signature;
        writeCommit;
        commitId.
^ repository
        commitFromGitCommit: (LGitCommit of: repo fromId: commitId) ] in IceGitIndex>>commitWithMessage:andParents: in Block: [ :repo | ...
[ aBlock value: self repositoryHandle ] in IceLibgitRepository>>withRepoDo: in Block: [ aBlock value: self repositoryHandle ]
[ self checkInitialized.
aBlock value ] in LGitGlobal class>>runSequence: in Block: [ self checkInitialized....
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in LGitActionSequence(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
LGitActionSequence(DynamicVariable)>>value:during:
LGitActionSequence class(DynamicVariable class)>>value:during:
LGitGlobal class>>runSequence:
IceLibgitRepository>>withRepoDo:
IceGitIndex>>commitWithMessage:andParents:
IceLibgitRepository(IceRepository)>>commitIndexWithMessage:andParents:
IceWorkingCopy>>commitChanges:withMessage:
IceLibgitRepository(IceRepository)>>commitChanges:withMessage:
[ self repository
        commitChanges: (diff copyWithOnly: items)
        withMessage: message.
self isPublish
        ifTrue: [ self repository push ] ] in IceTipCommitAction>>basicExecute in Block: [ self repository...
[ :bar |
bar label: aString.
aBlock value ] in MorphicUIManager(UIManager)>>informUser:during: in Block: [ :bar | ...
[ :bar | aBlock value: bar ] in MorphicUIManager>>informUserDuring: in Block: [ :bar | aBlock value: bar ]
BlockClosure>>cull:
[ ^ block cull: self ] in [ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
CurrentJob(DynamicVariable)>>value:during:
CurrentJob class(DynamicVariable class)>>value:during:
[ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning....
BlockClosure>>ensure:
Job>>run

**Comment by estebanlm** [comment]
this is still an issue? 
in older series (0.6*) I added a fallback to ask for them if they were not present. Maybe that was not copy to 0.7?

**Comment by estebanlm** [comment]
look at 

```Smalltalk
IceGitUsernameOrEmailNotFound class >> guessKind:ifNot: 
```
and around.

**Comment by estebanlm** [comment]
btw... I was not happy with the mechanism. But it was there ;)

**Comment by guillep** [comment]
I don't know, it was @demarey that reported it to me by email. I'd say from the stack trace that this happens on the commit operation?

We need to try to write a test for it.

**Comment by demarey** [comment]
It happened with the latest version of Iceberg (March, 30th) when I tried to commit a change.
It is quite easy to reproduce if you have no global user.name and user.email git property configured

**Comment by guillep** [comment]
Apparently the code that trapped the exception was in the old UI models. I'll adapt to to the new one.

**Comment by guillep** [comment]
Fixed in latest dev-0.7
