### ISSUE TITLE
Show tag version instead of "Detached HEAD"

### ISSUE THREAD

**Issue by peteruhnak** [pharo-vcs/iceberg#637]
I've installed my test project, which loaded Mocketry with tag v4.0.x, which in turn loaded StateSpecs:v2.4.x and Ghost:v3.1.x .

The UI shows me this
![image](https://user-images.githubusercontent.com/1276328/38735796-3668bfda-3f2a-11e8-9fcb-c6ac56d5dad9.png)

and to me such red text says: **there is something wrong and I should fix it**.
But actually there is nothing wrong here.

I think it would me much better to do a reverse-lookup (`git describe --contains SHA` ( https://git-scm.com/docs/git-describe )) or something like that (I assume this can be done via libgit) so people are not needlessly alerted. (plus this is a valuable feature regardless of the confusion issue)

So Detached HEAD should be only shown when the commit is _only_ Detached HEAD (i.e. there are no tags (annotated or not).)

**Comment by peteruhnak** [comment]
> (plus this is a valuable feature regardless of the confusion issue)

I meant it would be nice to show the tag here (if available), alongside the short SHA

![image](https://user-images.githubusercontent.com/1276328/38741957-8395bd24-3f3b-11e8-8c3f-5517fa34fab1.png)

**Comment by guillep** [comment]
Well, even if you've checked out a tag, you're still on detached head, and I want people to know it.

The important property of detached head is that (so far in iceberg) you cannot commit. We decided that you should be in a branch to be able to commit to avoid misbehaviours and human mistakes so far...

And being in a tag does not change that. You're not in a branch. So your commits may get lost.

Maybe the red color is to reddish? Maybe put it in yellow?

I also want to add a help button next to the status text at some point so people can learn what is detached head, and what are the consequences of it.

**Comment by jecisc** [comment]
The help button would be really great indeed!

**Comment by peteruhnak** [comment]
> We decided that you should be in a branch to be able to commit to avoid misbehaviours and human mistakes so far...

can we:

* completely remove the styling in the listing (so not even yellow... just plain black text)
* keep it red when I open the repo

that way it will not create any visual noise, and when people open a specific repo (implying they want to perform some potentially problematic action) they would still see it in red

Because practically speaking:
* in my current work image I have about ~25 repositories, but I usually only change one, sometimes couple more (maybe 5 max)... but for the rest they are just there, because I have iceberg integration enable, and I don't care about them (until I encounter bug)

Having an option to hide certain repos (and then show/hide all hidden repos) would also resolve this problem (assuming I can script it so I don't have to manually hide repos every time I build new work image)
