### ISSUE TITLE
Iceberg update script for version 6.1 fails

### ISSUE THREAD

**Issue by pjgoodall** [pharo-vcs/iceberg#646]
Hello,
The latest Pharo 6.1 image #60540, deployed by Pharo launcher as 6.1 (stable) fails when running , as instructed, the iceberg update script in the current iceberg `README.md`.

During installation a lot of Class structures are read from streams as instances of UndefinedObject. I tried a little patching to get it working, but there were too many occurrences. There must be some basic misconfiguration in the load process.

First occurrence for me is in "MCFileTreeStCypressReader>>#addClassAndMethodDefinitionsFromEntry:"

I reported the exception - not sure how to retrieve it.

```
Image
-----
[...]/Documents/Pharo/images/SVG-One/SVG-One.image
Pharo6.0
Latest update: #60540
Unnamed

Image Commandline Parameters
----------------------------
none

Image Sources
-------------
SourceFileArray
MultiByteFileStream: '[...]/Documents/Pharo/vms/61-x64/Pharo.app/Contents/MacOS/PharoV60.sources'
MultiByteFileStream: '[...]/Documents/Pharo/images/SVG-One/SVG-One.changes'

Virtual Machine Commandline Options
-----------------------------------
none

Operating System/Hardware
-------------------------
Mac OS 1013.4 x64

```

**Comment by estebanlm** [comment]
you had a download problem. 
other people are using it without problems on 6.1. 

can you try again in a clean image/directory?
