### ISSUE TITLE
"Create new branch from issue" is leaving image in detached working copy state

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#650]
When creating a new branch from Pharo issue, the repository is in detached working copy state and still needs to be fixed manually (e.g. create a new branch with a random name, remove the issue branch and create+checkout a new branch with the same name)

**Comment by guillep** [comment]
This should be fixed for next release 0.7.3.

People can try it by updating iceberg:
 - clone iceberg
 - switch to branch origin/dev-0.7
