### ISSUE TITLE
Sensibility of package filter seems odd

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#665]
**OS**

Windows 10

**Pharo**

60540

**Iceberg**

0.7.2

**Problem**

I tried to add three packages to my repository:
- ChartJs-Core
- ChartJs-Demo
- ChartJs-Library

So I tried to filter with "Chart" but I got 0 result.

Then I tried with "chart" and I got results. That's odd.

![2018-04-21_00-53-44](https://user-images.githubusercontent.com/9519971/39076907-8b972a30-44fe-11e8-9c65-251ef823385b.gif)

**Comment by guillep** [comment]
We've seen this during the sprint, yes
