### ISSUE TITLE
Iceberg sometimes add a `$` to commit message

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#666]
**OS**

Windows 10

**Pharo**

60540

**Iceberg**

0.7.2

**Problem**

Sometimes Iceberg seems to add a `$` to the end of my commit messages. 

See:

- https://github.com/DuneSt/ChartJs/commit/d0817da06e95693b52fc96426418e617760e92b3
- https://github.com/DuneSt/ChartJs/commit/38e70fe66b960ca9a036e755b791f9ba4734fcb3
- https://github.com/DuneSt/ChartJs/commit/af119519ec0bc7ee15b930c14fcabdfcd5ff61d3

**Comment by guillep** [comment]
Yes, I've seen that several times. I don't understand where it comes from.

**Comment by jecisc** [comment]
I tried to look at what happened with the commit message during a commit but I saw no problem until it was passed to the LibGit call...

**Comment by guillep** [comment]
@tesonep found a way to reproduce it. It has something to do with how bytestrings are padded and transformed to strings by uffi
