### ISSUE TITLE
On Latest Pharo loading Calypso with Metacello failed

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#668]
Maybe something should be improved in Calypso (and dependencies). But I need to know what.
Try update Calypso to dev version using Metacello:
```Smalltalk
Metacello new
  baseline: 'Calypso';
  repository: 'github://dionisiydk/Calypso:dev';
  onUpgrade: [:err | err useIncoming];
  load
```
You will see many debuggers.

**Comment by guillep** [comment]
Could not reproduce in latest iceberg. If still valid, please re-open.
