### ISSUE TITLE
Cannot load project in Pharo 6.1 with Iceberg dev-0.7

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#669]
**OS**

Windows 10

**Pharo**
60540

**Iceberg** 

dev-0.7 (2376c1b544a0da23538293913f52fea177c9879c)

**What I did**

- Download a new Pharo 6.1 image
- Open it without launching the settings
- Install Iceberg dev-0.7
- Launch settings (in my case they set the default folder, my ssh key and register a project)
- Try to install prismJs

```Smalltalk
Metacello new
	githubUser: 'DuneSt' project: 'PrismCodeDisplayer' commitish: 'development' path: 'src';
	baseline: 'PrismCodeDisplayer';
	onUpgrade: [ :e | e useIncoming ];
	onWarningLog;
	load
```

Current PrismJS SHA on the development branch: 56c14637c84a08301046ea2dca144f05792ec144

**Result**

I get an error:

```
SmallInteger(Object)>>altDNU:
SmallInteger(Object)>>doesNotUnderstand: #isSeparator
STONReader>>consumeWhitespace
STONReader>>next
STON class>>fromStream:
[ :stream | STON fromStream: stream ] in IceRepositoryProperties class>>fromCommitish: in Block: [ :stream | STON fromStream: stream ]
[ aBlock value: stream ] in FileReference(AbstractFileReference)>>readStreamDo: in Block: [ aBlock value: stream ]
BlockClosure>>ensure:
FileReference(AbstractFileReference)>>readStreamDo:
IceRepositoryProperties class>>fromCommitish:
IceGitCommit>>properties
IceGitCommit>>writerClass
IceGitCommit>>fetchPackageNames
IceGitCommit>>packageNames
IceGitCommit(IceCommit)>>packages
IceWorkingCopy>>initializePackagesFromRepository
IceRepositoryCreator>>addLocalRepository
IceRepositoryCreator>>addLocalRepositoryAndCheckout
IceMetacelloDuplicatedNotification>>useIncoming
[ :e | e useIncoming ] in UndefinedObject>>DoIt in Block: [ :e | e useIncoming ]
BlockClosure>>cull:
BlockClosure>>cull:cull:
BlockClosure>>cull:cull:cull:
MetacelloScriptEngine>>handleUpgrade:
```

*Note:* In the method `fromCommitish:`, if I try to inspect `ref` I get either an error about ZnBufferStream not indexable or a VM crash

**Comment by jecisc** [comment]
I could not reproduce with Iceberg `v0.7.2`.

**Comment by jecisc** [comment]
And I could confirm it again with Iceberg 0c76de04cc059ca80d71432ab0069ba343cb72db

So it is a bug introduced in the dev branch.

**Comment by guillep** [comment]
Yeah, I actually filled in also #670. Duplicated maybe.
We should check how to make properties file access from a commit compatible with pharo 6. Access to properties file is required for #678.

The problem seems to be that a commit's file system does not behave the same in pharo 6 and 7.

**Comment by estebanlm** [comment]
ok, this is not done. And kind of relevant :)

**Comment by jecisc** [comment]
In IceRepositoryProperties>>fromCommitish:, if I inspect `ref readStream upToEnd` I get a ByteArray and not a string. I think that STON does not expect a ByteArray.

**Comment by jecisc** [comment]
Problems comes from:

```Smalltalk
fromCommitish: aCommitish
	| ref properties repository dir |
	repository := aCommitish repository.
	dir := repository subdirectory isEmptyOrNil
		ifTrue: [ aCommitish fileSystem ]
		ifFalse: [ aCommitish fileSystem / repository subdirectory ].
	ref := dir / self propertiesFileName.
	properties := ref exists 
		ifTrue: [ ref readStreamDo: [ :stream | STON fromStream: stream ] ]
		ifFalse: [ Dictionary new ].
	^ (self fromDictionary: properties)
		repository: repository;
		yourself
```

In this case `ref` is a FileReference on `git://src`.

On Pharo 6.1 it returns "true" to #exists, but false on Pharo 7.

**Comment by guillep** [comment]
Well, first, there is no such thing as "the HEAD of master" and "the HEAD of development"...

**Comment by jecisc** [comment]
I mean the last commit of the remote branch.

**Comment by guillep** [comment]
But I don't understand. There is indeed a bug in how we recover the properties file from a commit. And it looks like it comes from the fact that there is a difference in how streams are handled.

But what does that have to do with pharo 7, pharo 6 and the commits? Is that a separate issue?

**Comment by jecisc** [comment]
They are the differences I saw between Pharo 61 And Pharo 7 in the debugger for the issue I described. 

I don't know if this is the issue you had in mind or not.
