### ISSUE TITLE
Updating Iceberg in Pharo6 raised warnings

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#671]
We had a warning because "PharoDarkTheme" was not there.

**Comment by jecisc** [comment]
Hi,

I think Esteban did not wanted to correct that, so there were a workaround in this commit:

https://github.com/pharo-vcs/iceberg/commit/2546f3d4efcd5b8ac3c28b39fe89e57e20a6869b

**Comment by guillep** [comment]
the `onWarningLog` works. I'll close this issue.
