### ISSUE TITLE
Duplicated project error when loading in a fresh image

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#688]
steps to reproduce:
- clone cargo: `git clone https://github.com/demarey/cargo.git /tmp/cargo`
- Take a fresh Pharo image
- Run Iceberg
- Add a local repository
 - local directory: `/tmp/cargo`
 - source directory: `repository`
- Right-click on `cargo repository / Metacello / Install baseline of Cargo ...`
 - groups to install: `tests`

=> `Duplicated project!` There is already a project "cargo" in this image

**Comment by guillep** [comment]
112f5fa partially provides a fix with better feedback. There is still an issue, when iceberg founds that a clone already exist, it will ask you to upgrade even if you asked to load the same commitish.

This is related to issue #168.

I'll close this one.
