### ISSUE TITLE
Specifying that Clone GitHub repository only deals with ssh mode

### ISSUE THREAD

**Issue by eleonoreW** [pharo-vcs/iceberg#695]
On the GitHub site, there are two mode to clone a repository, https and ssh.
In Iceberg, the "Clone GitHub repository" option only deals with ssh mode. It would be nice, (1) to let a comment to the user in order that she changes the mode on github or on iceberg and (2) to correctly capture the exception

**Comment by guillep** [comment]
Thanks! So I'd say:
- the "Clone from github" window should have a dropdown asking for ssh/https
- exceptions should be correctly handled

**Comment by guillep** [comment]
1cdfe13 adds support to choose the protocol not only for github but also bitbucket and gitlab.
