### ISSUE TITLE
Recompile after update

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#697]
I tried to install dev-0.7 to the latest Pharo 7 and I got problems because of Obsolete classes in Iceberg. 

Maybe the script to update Iceberg should end with `OpalCompiler recompileAll`?

What do you think?

**Comment by guillep** [comment]
That's not an iceberg problem. That's a problem from Calypso's plugin...
And that's a Pharo problem in general also:

https://pharo.fogbugz.com/f/cases/21519/RemoveFromSystem-does-not-work-well-with-Undeclareds
