### ISSUE TITLE
Cannot add a repository in current dev-0.7 branch

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#698]
**OS**

Windows 10

**Pharo**
Pharo-7.0+alpha.build.805.sha.cf9cfd92678dc27aae1efc37a12b5fcea6d25ba2 (32 Bit)

**Iceberg** 

dev-0.7 (042319340d1cc4a0e8c8e3a3d86553d8c3642125)

**What I did**

- Download a new Pharo 7 image
- Open it without launching the settings
- Install Iceberg dev-0.7
- Open the UI an clicked on "Add"

**Result**

I get an error:

```
UndefinedObject(Object)>>doesNotUnderstand: #owner:
IceTipNewRepositoryPanel(ComposablePresenter)>>instantiate:
IceTipNewRepositoryPanel(IceTipRepositoryTypePanel)>>initializeProjectLocation
IceTipNewRepositoryPanel(IceTipRepositoryTypePanel)>>initializeWidgets
IceTipNewRepositoryPanel>>initializeWidgets
IceTipNewRepositoryPanel(ComposablePresenter)>>initializePrivateHooks
IceTipNewRepositoryPanel(ComposablePresenter)>>initialize
IceTipNewRepositoryPanel class(Behavior)>>new
ByteSymbol(Symbol)>>value:
OrderedCollection>>collect:
IceTipRepositoryTypePanel class>>allTypes
IceTipRegisterRepositoryDialog>>allTypes
IceTipRegisterRepositoryDialog(IceTipOptionDialog)>>newTypeListDataSource
IceTipRegisterRepositoryDialog(IceTipOptionDialog)>>initializeTypeList
IceTipRegisterRepositoryDialog(IceTipOptionDialog)>>initializeWidgets
IceTipRegisterRepositoryDialog(ComposablePresenter)>>initializePrivateHooks
IceTipRegisterRepositoryDialog(ComposablePresenter)>>initialize
IceTipRegisterRepositoryDialog class(Behavior)>>new
IceTipAddRepositoryCommand>>execute
IceTipRepositoryListContext(CmdToolContext)>>executeCommand:by:
[ self prepareCommandForExecution.
context executeCommand: command by: self.
self applyCommandResult ] in CmdCommandActivator>>executeCommand in Block: [ self prepareCommandForExecution....
BlockClosure>>on:do:
CmdCommandActivator>>executeCommand
[ self executeCommand ] in CmdCommandActivator>>buildToolbarItem in Block: [ self executeCommand ]
BlockClosure>>cull:
IceTipToolbarItem>>execute
IceTipToolbarItemButtonMorph(PluggableButtonMorph)>>performAction:
[ :m | 
(m containsPoint: evt cursorPoint)
	ifTrue: [ m enabled
			ifTrue: [ m performAction: evt ] ] ] in IceTipToolbarItemButtonMorph(PluggableButtonMorph)>>mouseUp: in Block: [ :m | ...
Array(SequenceableCollection)>>do:
IceTipToolbarItemButtonMorph(PluggableButtonMorph)>>mouseUp:

```

Maybe this is an already known error since it's on the dev branch but I prefer to fill a report in case it is not.

**Comment by jecisc** [comment]
I just updated the Pharo version info because it was wrong.

**Comment by guillep** [comment]
How did you "Install dev-0.7"? Because the instructions in the readme say explicitly they are for Pharo 6.1. If you want to install dev-0.7 you only have to clone and checkout (I'll make a video of that later this afternoon).

**Comment by jecisc** [comment]
I installed it with the script of the README because I did not wanted to risk to update Iceberg with Iceberg.

But since the update script use `(each asPackageIfAbsent: [ nil ]) ifNotNil: #removeFromSystem`, is there a reason not to add all current packages to the script to make it work also in Pharo 7? And the script will be up to date if there is a new Iceberg loaded in Pharo 6 and people needs to update to another dev version.

**Comment by guillep** [comment]
Yeh, but in any case the readme says that is the update script for Pharo6.1, not for Pharo 7 :)

https://github.com/pharo-vcs/iceberg/blob/dev-0.7/README.md

I'll close this issue and open one to make a screencast on how to contribute to iceberg.
