### ISSUE TITLE
Class instance variables are ignored

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#714]
It looks like Iceberg ignores adding of the class instance variables to classes.

### How to reproduce

- create empty class
- save it to a (tonel) repository using Iceberg, the definition looks like this:
```
Class {
	#name : #MyClass,
	#superclass : #Object,
	#category : #TonelIssue
}
```
- add a class instance variable (cvar)
- commit changes, the diff tool will display the class side definition change however but after the commit, the window does not disappear
- the exported definition is still the same

it is not directly an issue of Tonel because when I try:
```

exportDir := '/tmp/src' asFileReference ensureCreateDirectory.

packageNames := 'TonelIssue' lines.

(packageNames collect: #asPackage) do: [ :pkg |
	| newVersion |
	newVersion := MCVersion new
		setPackage: pkg mcWorkingCopy package
		info: (IceMCVersionInfo package: pkg message: '')
		snapshot: pkg mcWorkingCopy package snapshot
		dependencies: #().
	
	TonelWriter fileOut: (newVersion) on: exportDir. ].
```
then the exported definition looks like this:
```
Class {
	#name : #MyClass,
	#superclass : #Object,
	#classInstVars : [
		'cvar'
	],
	#category : #TonelIssue
}
```

**Comment by pavel-krivanek** [comment]
one part of this issue - that class side changes are showed as additions instead of modifications can be solved easily using
```
!MCClassDefinition methodsFor: 'visiting' stamp: 'pk 4/26/2018 16:28'!
accept: aVisitor
	aVisitor visitClassDefinition: self.
	aVisitor visitMetaclassDefinition: self.
! !
```

**Comment by pavel-krivanek** [comment]
...so instance side and class side are both always compared

**Comment by pavel-krivanek** [comment]
continue in investigation from IceGitWorkingCopyUpdateVisitor>>visitPackage:

**Comment by guillep** [comment]
Commit bf19d1911843f94b4fc807fc53296dbb67353464 fixes the big issue.

There is still the problem that the modification is seen as an addition (because for monticello these are different entities the class and instance sides). I'd put that however in another issue.
