### ISSUE TITLE
"#pathString was sent to nil" if Pharo repository is not resolved

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-vcs/iceberg#716]
If you try to load a new external project using the Metacello (or simply try to load development version of Iceberg), it fails on an error `#pathString was sent to nil`. That happens if the predefined Pharo repository is not correctly resolved.

I think it is a critical bug because it makes impossible to load external packages into a fresh image

**Comment by guillep** [comment]
I'm working on it right now. It will be in for the next Iceberg minor release (either tomorrow or next week)
