### ISSUE TITLE
Update iceberg after modifying it requires unnecessary merge

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#72]
1) Import iceberg from metacello

```
Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg';
  load.
```

2) Introduce modifications.
3) Try to update 
`Iceberg update.`

Even if update is not bringing a new version, it will complain that a merge is necessary. This is (most probably) because we are loosing track of the commits.

**Comment by estebanlm** [comment]
I do not think this is an issue now
