### ISSUE TITLE
Repository creation error not handled

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#721]
By doing a mistake when creating a repository in Iceberg, I got a debugger with the following message: `LGit_GIT_EEOF: ERROR: Repository not found`

To reproduce:
- Open Iceberg
- Add a repository
- Clone github repository
 - give wrong username (or project name)

**Comment by tesonep** [comment]
Fixed in a2876861fc17583a9b8cc83e4d1753ab128fa2a0
