### ISSUE TITLE
Propose to pull before launching a Metacello loading

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#723]
From Iceberg v0.7.2 on Pharo 6.1.

Situation:
- On my work computer, I work on a project. I do commit 35 on branch dev.
- The evening at home I clone and do commit 36 on dev.
- The next day at work I take a new image and want to reinstall the project. So I use the Iceberg Metacello integration and ask to install the development branch either via the Iceberg interface or a Metacello script. 

In that case, it will install the version on the disk which is on commit 35 and not commit 36. This is normal, but maybe Iceberg could open a window:

"
Your local branch is behind the upstream remote branch. What do you want to do?

- Install anyway
- Pull branch then install
"

Of course with the possibility to have an option to manage that in a non-interactive mode with Metacello script.

What do you think about that? Do you think it would make sense and be possible?

**Comment by guillep** [comment]
I don't quite understand. Once the project is installed, Is the repository registered in iceberg? Cannot you pull from Iceberg's UI?

I understand that pulling before installing would mean that you will install the newest metacello baseline also.

I'm not sure how to manage it yet, I should really read metacello's doc to see how to reload a project when the baseline changes, how to deal with metacello's project registry, and so on... I'll come back with something more concrete.

**Comment by jecisc** [comment]
I'll try to give more details for you to understand (I know I'm not really good to explain things). 

With a project on Monticello managed via a ConfigurationOf, when you install it it will download the .mcz in the package cache and install the project with the version/baseline you asked. 

If you ask for development, you'll get the latest packages described in the "development" baseline.

Now, with a project hosted on github and managed via a baseline, if the Iceberg Metacello integration is enabled, when I ask to load the branch "development", I'm not sure I'll get the latest version of the packages.

If there is no local clone of the project it will clone the project and checkout the latest version of the branch.  But, if I already have a local clone with the branch (not in sync with the remote branch), it will install the version present locally. This version might be 5 commits behind the remote branch.

That's why, maybe Iceberg can check the remote branch before installing the repository and if the local branch is behind the remote branch, it can ask the user what to do. Either install the local version or pull the install.

Is that better or I am still unclear?

**Comment by guillep** [comment]
I think this is duplicated with #168. Is it?

**Comment by jecisc** [comment]
Yes, sorry I did not see this issue.

Closing this one.
