### ISSUE TITLE
Remove "pharo" Repository with "also remove from filesystem" gives error

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#738]
- Download fresh Pharo image
- click on the pharo repo
- remove it while in the remove dialog select "Also remove repository from file system"

---------------------------------------------------------------------------------------------------------
UndefinedObject(Object)>>doesNotUnderstand: #ensureDeleteAll
IceLibgitRepository>>delete
[ self entity delete ] in IceTipRepositoryModel>>delete in Block: [ self entity delete ]
[ :bar | 
bar label: aString.
aBlock value ] in MorphicUIManager(UIManager)>>informUser:during: in Block: [ :bar | ...
[ :bar | aBlock value: bar ] in MorphicUIManager>>informUserDuring: in Block: [ :bar | aBlock value: bar ]
BlockClosure>>cull:
[ ^ block cull: self ] in [ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
CurrentJob(DynamicVariable)>>value:during:
CurrentJob class(DynamicVariable class)>>value:during:
[ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning....
BlockClosure>>ensure:
Job>>run
MorphicUIManager(UIManager)>>displayProgress:from:to:during:
MorphicUIManager>>informUserDuring:
MorphicUIManager(UIManager)>>informUser:during:
IceTipStandardAction>>basicExecute
[ self basicExecute.
self finishSuccess ] in IceTipStandardAction(IceTipAction)>>execute in Block: [ self basicExecute....
BlockClosure>>on:do:
IceTipStandardAction(IceTipAction)>>withErrorHandlingDo:
IceTipStandardAction(IceTipAction)>>execute
IceTipStandardAction>>execute:
IceTipRepositoryModel>>delete
IceTipCachedModel>>forwardMessage:
IceTipCachedModel>>doesNotUnderstand: #delete
IceTipRemoveRepositoryDialog>>accept
[ self accept ] in IceTipRemoveRepositoryDialog(IceTipDialog)>>openDialogWithSpec in Block: [ self accept ]
[ okAction value value == false
	ifFalse: [ owner ifNil: [ self delete ] ifNotNil: [ owner delete ] ] ] in OkCancelToolbar(OkToolbar)>>okActionBlock in Block: [ okAction value value == false...
ButtonPresenter>>performAction

**Comment by guillep** [comment]
Fixed (+ tested) in ae8938463eba71a8cf5669ce32cff645d8971bf8
