### ISSUE TITLE
Initial focus should be in "FogBugz issue" field, also rename the label

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#739]
- open Iceberg
- select Pharo -> Create new branch for issue
- in the dialog the cursor is in the second edit field (Title) but should be in the first one (FogBugz issue) so one can enter an issue number and the title is grabbed from the issue tracking tool

Ideally we would also rename the label into just "Pharo Issue Number" because
FogBugz is now known as Manuscript (fogbugz.com redirects to manuscript.com)

**Comment by jecisc** [comment]
I don't understand why the issue number field is not selected first...

In the code there is:
```
self focusOrder
		add: issueNumberText;
		add: issueText
```

So I assume it should be selected first. (But I don't know spec that much...)

**Comment by jecisc** [comment]
Ok, the problem comes from the fact that this Presenters inherits from another one defining a focus order but all the content of the superclass does not seem to be used.

As the `branchInputText`

**Comment by guillep** [comment]
Should be fixed with #740 for next release
