### ISSUE TITLE
Input password to commit to public gitlab repo fails

### ISSUE THREAD

**Issue by Marmat21** [pharo-vcs/iceberg#745]
The image freezes after inserting the login to push to a public gitlab repository in HTTPS (not hosted on gitlab.com)

**Comment by tesonep** [comment]
Hello @Marmat21, can you guide us more with the problem?
Does the gitlab server uses something special in the HTTPS authentication (ie: a proxy?)
I have tested with a gitlab basic installation and it works. 
I think there is some differences with the configuration of the authentication.

Thanks.
