### ISSUE TITLE
Code subdirectory in empty repository

### ISSUE THREAD

**Issue by tesonep** [pharo-vcs/iceberg#748]
When cloning an empty repository, it should be able to create the missing code subdirectory.

**Comment by estebanlm** [comment]
wasn't this fixed?

**Comment by tesonep** [comment]
Not when cloning, only when creating a new local one.

**Comment by estebanlm** [comment]
mmm... what I tested is to create a project on gitub, clone defining "src" as subdirectory.
There was an error "local blabla" there, but I was able to add my packages and commit, then the "local directory missing" problem was fixed...
I'm not saying this is how it has to work, but well, at least it worked ;)

**Comment by tesonep** [comment]
I didn't try that, but I thought having some repair actions was a good idea. They are so easy to implement 😃  
Also I have addressed two scenarios:

1. If the src directory is wrong, yes ... it is just a shortcut to edit repository... but you know the users...
2. If the src directory is the intended but it does not exists. In the repair action I create the directory, because a lot of things only work if the directory is there (when it calculates the packages for example). 

I was talking with @guillep about this solution. I don't like it, but it is a patch until we work better the subdirectory problem.

I intended only to prevent the red, you know the users see a problem and they start doing crazy things. So giving them some repair actions I think is good. Do you think we can solve it in another way?

**Comment by guillep** [comment]
I'm thinking about this:
1. I clone a repo (I don't put a src directory)
2. Iceberg cannot find my .iceberg or .properties file
3. then Iceberg, if in interactive mode, will ask me "Where is the repository"
4. if there is no .properties file, Iceberg should create one, setting Tonel or Filetree (depending on existing code for example), maybe asking me before what I want to do.

**Comment by guillep** [comment]
Ok, I merged the PR for now, as it is a compromise solution until we have something better. Let's keep the issue as enhancement however.
