### ISSUE TITLE
Create branch dialog layout is broken

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#753]
The second line of the form, the branch name text box is aligned to the bottom:

![checkout new branch from issue](https://user-images.githubusercontent.com/708322/39522196-f11ce8b0-4e11-11e8-9308-4a2e684334d4.png)

**Comment by estebanlm** [comment]
this is because you need to add an invisible "space" panel behind. 
it was there in previous versions, I don't know why is not there anymore :(

**Comment by guillep** [comment]
@jecisc did a refactoring on #740.

Now, everything that has no automated tests will eventually break, we cannot test every dialog every time :/. So we have to think on how to test the window navigation and the layouts.
