### ISSUE TITLE
GitHub password required but Git password asked

### ISSUE THREAD

**Issue by Larcheveque** [pharo-vcs/iceberg#763]
When you try to push commits, iceberg ask for the git username and password but expect your github username and password

**Comment by tesonep** [comment]
We have to recover the password request dialog and also save the passwords separated by hosts

**Comment by astares** [comment]
More is broken:

In latest iceberg version/Pharo 7 image it does not even ask for the credentials when I click "Push" - it just gives dialog with a message that it was not able to authenticate. 

(I follow my scenario as seen in the videos on https://pharoweekly.wordpress.com/2018/05/19/pharocontributor-videos/) 

In the second video (https://www.youtube.com/watch?v=24ERozCePME)
at 4:34 you will see that it asked for credentials. 

If do the same today it will not ask but display the message dialog.

**Comment by guillep** [comment]
@tesonep both issues should be working in latest version
