### ISSUE TITLE
Inverse merge preview shows wrong diff

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#768]
My image points to branch2 and have some changes. My local copy points to branch1. 
I press repair with "merge image with existing branch" where I select branch2. 
The result diff shows changes between branch1 and branch2. 
But it should compare branch2 with image according to the name "merge image with existing branch"

**Comment by guillep** [comment]
You mean the diff is inverted?

Actually what you're doing there is what we call an "inverse merge" (though the name is not in the interface for simplicity). The thing is that an inverse merge will potentially modify both your working copy in the image and the repository if the merge is not just a fast forward.

If you think it well, both directions of the merge are right:
 - you may be applying changes of your image into the repository (so image could be on the right)
 - you may be applying changes of the repository into the image (so repository could also be on the right)

We decided for consistency to leave the image on the left and the repository changes on the right. The rationale is that we want to show that you apply your changes in your image.
Why?
 - Consistency first with the other merges
 - The repository can always be repaired. Every action is logged and you can come back to an older commit. On the other side the image cannot be repaired so easily. If you mess with it and you did not have a backup, you'll have to start from scratch.

**Comment by dionisiydk** [comment]
I not understand why you just close the issue.
Let's try again:

working copy = image. Right?

So I worked in branch1 and save and close the image. Then I worked in another image on branch2.  I checkout branch2 and load code into this new image.

Then I decided to continue work with "imageForBranch1": it points to branch1 and was saved in that state. So I expect that this image is a working copy of branch1. Am I correct here?

Then when I open imageForBranch1 I see in iceberg that repository is actually points to branch2 and I need to repair it.

The option "merge image with existing branch" looks like it is exactly what I need. Does it?

But when I choose it and select branch1 the diff shows me changes between branch1 and branch2. Is it expected from you?

I expect to see diff between my image working copy and branch1 (which in fact has no difference).
Should I submit such merge? What will happen with image changes if I did them before repair?
Even if it will work correctly I found this diff super confusing because it does not show what will be changed in the image.

**Comment by guillep** [comment]
I've closed the issue because I misunderstood you :)

>Then I decided to continue work with "imageForBranch1": it points to branch1 and was saved in that state. So I expect that this image is a working copy of branch1. Am I correct here?

Nope, an image is never on a branch. An image is on a commit.

>Then when I open imageForBranch1 I see in iceberg that repository is actually points to branch2 and I need to repair it.
>
>The option "merge image with existing branch" looks like it is exactly what I need. Does it?

Yes, you want to merge your image with `branch1`.

> But when I choose it and select branch1 the diff shows me changes between branch1 and branch2. Is it expected from you?

You mean the merge preview? It **should** show the diff between your image and branch1, if you selected branch1. Otherwise, yes, that's a bug.

Can you confirm that's the problem you encountered?

> I expect to see diff between my image working copy and branch1 (which in fact has no difference).
Should I submit such merge? What will happen with image changes if I did them before repair?
Even if it will work correctly I found this diff super confusing because it does not show what will be changed in the image.

The merge should work correctly afterwards. Can you confirm it?

In any case, if the preview is broken I agree that we have to fix it.

**Comment by dionisiydk** [comment]
> You mean the merge preview? It should show the diff between your image and branch1, if you selected branch1. Otherwise, yes, that's a bug.
> 
> Can you confirm that's the problem you encountered?

Yes, I confirm: that is the problem.
Look at following screens:
![icebergmergeproblem1](https://user-images.githubusercontent.com/8149664/39858436-3d62557e-543f-11e8-9104-974441eb7a9e.png)
It is the image which was saved at commit from branch dev. So I start repair it by merging dev into the image.
![icebergmergeproblem2](https://user-images.githubusercontent.com/8149664/39858435-3d432b72-543f-11e8-90f4-5d466d56c177.png)
![icebergmergeproblem3](https://user-images.githubusercontent.com/8149664/39858434-3d24d74e-543f-11e8-9ace-ab88a3b859d5.png)
![icebergmergeproblem4](https://user-images.githubusercontent.com/8149664/39858433-3d0284fa-543f-11e8-9903-00d66e4b78f7.png)
![icebergmergeproblem5](https://user-images.githubusercontent.com/8149664/39858432-3cd15d94-543f-11e8-8e6f-77c35c55c2f0.png)
As you see at last screen there are a lot of changes. It is changes between dev and contextRefactor2 instead of dev and image. There were no changes in image and in dev when image was saved. So this tree should be empty.
