### ISSUE TITLE
Copy Wiki contribution page to pharo-project/pharo wiki

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#774]
There is an outdated wiki about contribution in the pharo-project/pharo repository and iceberg contains un up to date version.

We should either get the correct version in the Pharo repository or have one reference the other to avoid duplication.

https://github.com/pharo-project/pharo/wiki/Contribute-a-fix-to-Pharo

**Comment by guillep** [comment]
Yeh, I don't know. I'd keep iceberg documentation close to iceberg? And set a link from that repo to this one.  Iceberg is under pharo-vcs so it's pharo too ^^.

**Comment by jecisc** [comment]
I agree. That's why I added the option "or have one reference the other to avoid duplication." in my proposition.

**Comment by guillep** [comment]
Done

https://github.com/pharo-vcs/iceberg/wiki/Contributing-to-Pharo
https://github.com/pharo-project/pharo/wiki/Contribute-a-fix-to-Pharo

**Comment by jecisc** [comment]
@guillep Thank you!
