### ISSUE TITLE
Reviewing a PR is broken

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#775]
**OS**

Windows 7

**Pharo**

Build information: Pharo-7.0+alpha.build.863.sha.794a5428eb0aa4d4413eb7e979f9651ec76be461 (32 Bit)

**Iceberg**

v0.7.5

**Problem**

I wanted to review this PR: https://github.com/pharo-project/pharo/pull/1331

I opened the PR View windows of the Pharo repository, selected the one from sven and tried to review.

I only got an empty window.

![image](https://user-images.githubusercontent.com/9519971/39893633-acf9351e-54a4-11e8-9dbe-db086c3b5bac.png)

**Comment by bencoman** [comment]
Windows 10, Pharo: 6.1...
Downloaded http://files.pharo.org/platform/Pharo6.1-win.zip
Updated Icerberg per https://github.com/pharo-vcs/iceberg#update-iceberg
Iceberg 
  > Settings > Use custom keys = Enabled
  > Add > Clone remote repository
      Remote URL = [hidden email]:exercism/pharo.git
  ==> "pharo" repo appears, status "Not loaded"
  > "pharo" repo > Packages ==> BaselineOfExercism, Exercism, etc
  > "pharo" repo > Github > View pull request > origin > enter github account password
  ==> shows PR#98 "Move setup to class initialization..."
    > right-click 98 > Review pull request
  ==> an empty window titled "Browsing pull request: #98...." appeared...
![a03-empty-pull-request-review](https://user-images.githubusercontent.com/1713447/45266202-ca28f080-b489-11e8-9de1-16143d473181.png)
