### ISSUE TITLE
How to know url of repository?

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#782]
Maybe I am blind but I can't find actual url to repository in Iceberg UI.
I loaded big project with many dependencies and I tried to find actual place where they were loaded.

**Comment by estebanlm** [comment]
there is no such thing as url of a repository.
you have remotes and remotes have (usually) an url. 

but there is no direct match between a repository and an url since you can have many of them (and there is no central point)

**Comment by dionisiydk** [comment]
Ok. I knew it. I should better describe issues.
I can't find where to see url of remote.

**Comment by jecisc** [comment]
What would be cool would be to add an"edit remote" option. Then you could see the current URL.

**Comment by dionisiydk** [comment]
I would like to have tooltip over remote with url
