### ISSUE TITLE
Key not found error when switching back to original branch after adding new package with new class

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#786]
Found an issue in Iceberg while making some contributions this week:

 - have a recent image with 'development' branch in synch
 - create a branch for a Pharo issue
 - add a new package in browser and add a new class to it
 - add the new package also in iceberg
 - commit and push (where push is optional)
So that is fine

 - but now go to "branches" and switch back to the local -> development branch

This gives an key not found error.

Side note: If you usually do a change, commit + push and switch back to the development branch the image is set back to the previous state.
But unfortunately not when a new package with a new class is involved due to this error.

I had this twice. So it should be reproducible.

**Comment by jecisc** [comment]
Might be corrected by https://github.com/pharo-vcs/iceberg/pull/780
