### ISSUE TITLE
Add the commit message to history window

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#793]
When browsing the history of a method I think it would be good to have also the comment of the commits.

**Comment by guillep** [comment]
- Maybe a shortened version in the table?
- And a textbox with the full comment on selection? Because with big comments it would not be good to put them in the message

**Comment by jecisc** [comment]
@guillep I agree, but where would you want to add the text area?

![image](https://user-images.githubusercontent.com/9519971/40120882-8c1f53d4-5920-11e8-9fad-236eb6b902dd.png)

**Comment by estebanlm** [comment]
why not just to include the commit info tab?

**Comment by jecisc** [comment]
Yes, it would be a good solution. 

Currently, this browser is done with Glamour. Is it planned to move it to Spec?

If that's the case I'll probably wait the transition is done since I don't know much of Glamour and Spec.

**Comment by estebanlm** [comment]
yes, we should move it to spec.

**Comment by guillep** [comment]
Ah, you meant DAT history window. I thought you were talking about the repository window. But I see it is already there.
