### ISSUE TITLE
Auto-fetch in background

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#798]
It's maybe not possible for now but I'm sure so I'll ask anyway.

In gitkraken there is a setting to do a background auto-fetch. It's pretty cool. 

For example, you can ask to automatically fetch your repositories every 3min. 

Would that be feasible in Pharo? Do we have the possibility to launch FFI commands without "pausing the world"?

**Comment by estebanlm** [comment]
it is not. 
we need threaded FFI for that. 
we will revisit everything once we have it.
