### ISSUE TITLE
Conflicts creating a repository after changing branches.

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#8]
We can reproduce it by changing pharo-git branch, and starting IceExamples exampleSynchronizer

```
exampleSynchronizer
    | repository changeSet |
    repository := Git new origin: 'git@github.com:npasserini/pharo-git.git'.
    changeSet := IceRepositoryChangeSet fromRepository: repository.
    IceSynchronizer new
        changeSet: changeSet;
        openWithSpec.
```

I do not think it is a problem of the example, can happen in production code.
We should decide if we take the branch from the (pre)existing directory, use another directory or something smarter. Maybe we could let the user decide in each case.

On the other hand, if we removed the working copies from disk, this error would never happen.

**Comment by npasserini** [comment]
Ask the user to make a decission, with options:
1) override the existing repository and checkout the desired branch.
2) keep both, so select another repository
3) abort

**Comment by npasserini** [comment]
Closed by mistake.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. Iceberg shows that the image version is not in sync with the repository and shows several recovery strategies to the user.
