### ISSUE TITLE
Convert sources to tonel raises an Exception 

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#828]
May be I should load it first. 
I tried to convert Ducasse/SRT2VTT
![screen shot 2018-05-30 at 16 01 47](https://user-images.githubusercontent.com/432549/40725105-de7926c0-6422-11e8-8c9f-618975d099af.png)

**Comment by Ducasse** [comment]
Then I got 
![screen shot 2018-05-30 at 16 05 33](https://user-images.githubusercontent.com/432549/40725289-504e0b08-6423-11e8-9a8f-70f9f20c71d5.png)

**Comment by Ducasse** [comment]
Apparently the local repo was empty even if the github repo was not empty.

**Comment by estebanlm** [comment]
I cannot reproduce this.
I tried several repositories and it works every time :(

**Comment by guillep** [comment]
Try it with a *not loaded* repository.

**Comment by estebanlm** [comment]
no, it still worked

**Comment by guillep** [comment]
Well I don't know how @Ducasse got it, but I can reproduce it by:
 - create a new repository using the "New repository"
 - try to migrate the repository

The same may happen if you
 - create a new repository in github without README (so it will have no commits)
 - clone
 - try to migrate the repository

**Comment by guillep** [comment]
This can be also reproduced with https://github.com/Ducasse/Skeletonizer

**Comment by guillep** [comment]
Will be in next release
