### ISSUE TITLE
Move tags under remotes in Repository view

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#847]
Currently, in the repository view we have:

- Local branches
- Tags
- Remotes

I think we should have 

- Locals branches
- Remotes
- Tags

In general, we have fewer remotes than tags. 

Now it's long to scroll to the remotes when we browse Pharo for example.

**Comment by jecisc** [comment]
Or, at least the tags section should be collapsable and collapsed by default as the remotes.

**Comment by guillep** [comment]
We were already talking about this with Esteban. We left it as is for the moment to have a first release.

We will see if we implement collapsed
