### ISSUE TITLE
VM crash while saving credentials

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#849]
Today I tried to push a branch. I got asked for my github credentials. 

I passed them and checked the "remember credentials" checkbox. I got a warning saying that a file credential.fuel did not exist. When I click on the option to force the file creation I got a VM crash. 

![image](https://user-images.githubusercontent.com/9519971/41290313-cd355210-6e4c-11e8-9c2e-657cdc5d70be.png)

**Comment by tesonep** [comment]
Fixed when using the fileReferences properly
