### ISSUE TITLE
Error msg after an http timeout is unreadable

### ISSUE THREAD

**Issue by macta** [pharo-vcs/iceberg#869]
I had a timeout when trying to reconnect my pharo repo in Pharo 7. When I went to try again I got an error msg but the dialog message is cut off - it only says: You already have an iceberg repository and then some pixels of a line below (using halos showed me the real message:

You already have an Iceberg repository 
at /Users/macta/Dev/Smalltalk/Pharo/Pharo-7.0.0-alpha.build.1072.64bit-2018-07-19/pharo-local/iceberg/macta/pharo. 

If you really want create another one, 
please locate it in a different directory.

**Comment by macta** [comment]
I guess the message is too big - however stretching the dialog still doesn't show me the contents

**Comment by guillep** [comment]
Easily reproducible with:
 ```
[ Error signal: String loremIpsum ]
	on: Error do:  [ :error | (IceTipErrorDialog on: error) openDialogWithSpec ]
```

**Comment by guillep** [comment]
With the fix coming in next version, the label is not cut, and resizing the dialog (in case there is too much text expands the label too)
