### ISSUE TITLE
Putting "." in project src field gives dnu

### ISSUE THREAD

**Issue by macta** [pharo-vcs/iceberg#880]
I'm still struggling to load Calypso that isn't in a "src" directory. Thinking that if I put nothing in the src field of a project it will inherit the default value specificed in the settings - I put "." for current directory. However this gives a DNU.

UndefinedObject(Object)>>doesNotUnderstand: #nextChildNodeStartingFrom:suchThat:ifNone:
IceNode>>firstNodeSuchThat:ifNone:
IceNode>>firstNodeSuchThat:
[ tree
	firstNodeSuchThat: [ :definition | self isCodeSubdirectory: definition ] ] in IceDiff>>codeSubdirectoryNode in Block: [ tree...
BlockClosure>>cull:
ByteString(Collection)>>ifNotEmpty:ifEmpty:
IceDiff>>codeSubdirectoryNode
IceDiff>>includesPackageNamed:
[ :each | each beDirty: (diff includesPackageNamed: each name) ] in IceWorkingCopy>>adoptCommit: in Block: [ :each | each beDirty: (diff includesPackageNamed...etc...
Array(SequenceableCollection)>>do:
IceWorkingCopy>>adoptCommit:
IceWorkingCopy>>initializePackagesFromRepository
IceRepositoryCreator>>cloneRepository
[ self validate.
self isCloning
	ifTrue: [ self cloneRepository ]
	ifFalse: [ self addLocalRepository ] ] in IceRepositoryCreator>>createRepository in Block: [ self validate....
BlockClosure>>on:do:
IceRepositoryCreator>>createRepository
[ ^ IceRepositoryCreator new
	repository: repository;
	remote: (IceGitRemote url: self remoteUrl);
	location: self projectLocation location;
	subdirectory: self subdirectoryInputText text asString trimmed;
	createRepository ] in IceTipGitHubRepositoryPanel(IceTipGitRepositoryPanel)>>newRepository in Block: [ ^ IceRepositoryCreator new...
[ :bar | 
bar label: aString.
aBlock value ] in MorphicUIManager(UIManager)>>informUser:during: in Block: [ :bar | ...
[ :bar | aBlock value: bar ] in MorphicUIManager>>informUserDuring: in Block: [ :bar | aBlock value: bar ]
BlockClosure>>cull:
[ ^ block cull: self ] in [ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ ^ block cull: self ]
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in CurrentJob(DynamicVariable)>>value:during: in Block: [ activeProcess psValueAt: index put: anObject....
BlockClosure>>ensure:
CurrentJob(DynamicVariable)>>value:during:
CurrentJob class(DynamicVariable class)>>value:during:
[ self prepareForRunning.
CurrentJob value: self during: [ ^ block cull: self ] ] in Job>>run in Block: [ self prepareForRunning....
BlockClosure>>ensure:
Job>>run
MorphicUIManager(UIManager)>>displayProgress:from:to:during:
MorphicUIManager>>informUserDuring:

**Comment by guillep** [comment]
Hi @macta , I'm working on it.

However, when you clone, if you don't specify the src directory (i.e., an empty string '') it will use the root.

**Comment by macta** [comment]
I added a separate issue - as I just can't seem to clone Calypso using https (and my office blocks ssh, so I can't do any lunch time experiments). I had thought it was the use of the root directory (hence how I found this minor bug).

**Comment by guillep** [comment]
No problem. I've added ~140 more tests with a setup using a `src` directory and a `.`directory
