### ISSUE TITLE
Create a LGitConfig

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#90]
It is created by https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_config
Also we have to create a LGitConfigEntry.

When pushing a branch we should look for the properties 
- branch.<branchName>.remote 
- branch.<branchName>.merge
- branch.<branchName>.pushRemote
  in the config.

Maybe we can look for all of them at the same time using git_config_iterator_glob_new and a blob specifier branch.<branchName>.*

**Comment by estebanlm** [comment]
done
