### ISSUE TITLE
Conversion to tonel raises an error

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#900]
Steps to reproduce:
- donwload latest 70
- clone Ducasse/Skeletonizer
- convert to tonel
- force recursive....

**Comment by Ducasse** [comment]
![screen shot 2018-06-26 at 19 27 55](https://user-images.githubusercontent.com/432549/41929021-4bd31d0c-7977-11e8-99b7-bd1c12940c22.png)

**Comment by Ducasse** [comment]
I can show you on my machine...

**Comment by guillep** [comment]
Duplicates #828

**Comment by guillep** [comment]
I'll try to reproduce it with https://github.com/Ducasse/Skeletonizer also
