### ISSUE TITLE
optCoerceNilToNull does not seem to work.

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#91]
After fixing it, review the sends of treebuilder_new: repo: source: because they have hand-crafted null management that should be removed.

**Comment by estebanlm** [comment]
yes, `optCoerceNilToNull` had sense for NB, but UFFI does not implements it (can be added if needed, but didn't seemed like a priority at the moment)

**Comment by npasserini** [comment]
Yes it is not needed but it could be a "nice to have". If you agree that it
could be a good idea to have it, I would like to spend some time in it,
after ESUG.

**Comment by estebanlm** [comment]
nah, not related to iceberg (UFFI, in anycase)
