### ISSUE TITLE
Sync Wiki with documentation directory automatically

### ISSUE THREAD

**Issue by guillep** [pharo-vcs/iceberg#914]
More details in #909

**Comment by guillep** [comment]
Just so this issue is self-contained, I quote @cdlm:

> That would be
> install https://github.com/ingydotnet/git-subrepo
> git subrepo clone docs https://github.com/pharo-vcs/iceberg.wiki.git
> re-apply your grammatical changes (btw there's an images/ directory in the wiki repo… didn't check if they are linked from the text)
> from there, git status/commit/push as usual; it's transparent, normal contributors don't even need to have git-subrepo installed
> from time to time, someone should do git subrepo pull/push to sync content with the wiki.

BTW, @cdlm, do you know what happens if people try to commit and subrepo is not installed? Because if that breaks it would mean we are breaking every user's environment...

**Comment by guillep** [comment]
To answer myself, in the doc of subrepo it says
> Users do not need to install git-subrepo, ever.
> Collaborators do not need to install unless they want to push/pull.

So I'd say it's a no go.

Maybe we can write something custom and les magical that keeps the sync in travis and that's all.

**Comment by guillep** [comment]
This is now finished in 4716107, people can (and actually they should) contribute into the docs directory now. The wiki repository is read only, as it's content is always generated from the docs directory.

**Comment by cdlm** [comment]
_So I'd say it's a no go._
Why? the docs say it **will** work. The repository just contains a subdirectory which happens to have contents identical to the wiki. git-subrepo is only ever used to push these contents to the actual wiki, or pull from there, possibly merging in the process (which I agree might be a chore unless it's done regularly). Making the wiki read-only and `docs/` the authoritative source does eliminate half of the problem, but your `scripts/sync-wiki.sh` script is really the same as `git subrepo push docs`.

**Comment by cdlm** [comment]
_Maybe I just misunderstood the readme and they meant to push to the subrepo, not push to the main repo?_
Yes, git-subrepo would only be needed to sync the docs directory with the wiki (and to manage merges in case the wiki is read/write). Pushing to the main repo, including changes to the docs, uses plain git.
