### ISSUE TITLE
cannot see error message in dialog box

### ISSUE THREAD

**Issue by demarey** [pharo-vcs/iceberg#917]
I wanted to commit a change and got an error. As you can see, the dialog box prevents you to see the full description of the error even if you resize the window.

![capture d ecran 2018-07-10 a 14 23 06](https://user-images.githubusercontent.com/2494203/42509755-35693cbe-844d-11e8-9728-2826ddb3a85b.png)

Full error message:

> ERROR: Sorry, but @pharo-pkg has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help.
>
>If you personally created this key, you can approve it at:
>
>  https://github.com/settings/ssh/audit/47544/policy
>
>Otherwise, please upload a new key:
>
>  https://github.com/settings/keys
>
>Fingerprint: dc:f0:2e:d4:d3:90:dc:f0:2e:d4:d3:90
>
>[EPOLICYKEYAGE]

**Comment by guillep** [comment]
This is already fixed in latest dev.
Duplicates #869
