### ISSUE TITLE
missing method: projectName

### ISSUE THREAD

**Issue by apblack** [pharo-vcs/iceberg#927]
When loading SmaCC with Iceberg, I get a walkback with the message

> Instance of MetacelloAllowConflictingProjectUpgrade did not understand #projectName

The following definition seems to fix the problem:

```
MetacelloAllowConflictingProjectUpgrade >> projectName
	^ existingProjectRegistration projectName
```

**Comment by guillep** [comment]
In latest iceberg this is already included. Actually, it is defined in the superclass `MetacelloResolveProjectUpgrade`. We are working on a new release for the end of this week that will include this.
