### ISSUE TITLE
Changed ivar/slot name in stateful trait not recognized as a change

### ISSUE THREAD

**Issue by astares** [pharo-vcs/iceberg#930]
To reproduce: use latest Pharo 7 (here Pharo-7.0+alpha.build.1139.sha.9fe3ff4d8578d7e53b4d4104254d98ae850a7cc0 (64 Bit))

and run 

Metacello new
      baseline:'Bootstrap4';
      repository: 'github://astares/Seaside-Bootstrap4:master/src';
      load

to load Seaside and Bootstrap. 

There is a stateful trait "SBSTContextualStyled" with two slots (#modifier. #contextStyle)

Change the name of one of the slots by redefining from 

Trait named: #SBSTContextualStyled
	 uses: {}
	 slots: { #modifier. #contextStyle }
	 category: 'Bootstrap4-Core-Traits'

to 

Trait named: #SBSTContextualStyled
	 uses: {}
	 slots: { #modifier. #foo }
	 category: 'Bootstrap4-Core-Traits'

and Iceberg will not notice this change.

**Comment by tesonep** [comment]
This is an issue in Pharo.
Issue #22292
