### ISSUE TITLE
New project window should be coherent on the vocabulary

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#951]
In the new repair action to add a .project file, it is asked to select the "Directory" of the project.

I find it confusing. I would expect "Subdirectory" to be coherent because it was the name used until now.

Or if you don't want to keep the name "subdirectory" maybe "Source directory"?

**Comment by guillep** [comment]
I'm putting "code directory" because of window space. If I change the space of the labels it will not be coherent with the other windows. I also would have liked to put a tooltip but I couldn't find how to do it yet.
