### ISSUE TITLE
Add test: after merging there shouldn't be incomming commits.

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#96]
1) Create a package with incomming commits (in upstream, not merged to local branch).
2) Perform a local modification and commit.
3) Try to pull the incomming commits, it should fire a merge.

Check status after successful merging:
- there shouldn't be any incomming commits
- the merge commit should have both previous commits as parents.

Check status after cancelling merge:
- I should still have the incomming commits
- Code in image shouldn't have changed.

**Comment by guillep** [comment]
This should not be valid anymore in the latest version. I added new merge tests covering several complicated merge cases.
