### ISSUE TITLE
use instanceSide/classSide instead of other API

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#972]

**Comment by Ducasse** [comment]
I have the impression that my changes are breaking senders/implementers because I get a rub object instead of a selector. 

Now this method is really bad because how its client that know it fails?

findSelectorFromAST
	"Try to make a selector out of the current text selection"

	| node fallbackBlock |

	fallbackBlock := [^self].
	node := self bestNodeInTextAreaOnError: fallbackBlock.
	
	node isMethod ifFalse: [ 
		(node isValue and: [ node value isSymbol ]) ifTrue: [ ^node value ].
				
		[ node isMessage ] whileFalse: [ 
	 		(node := node parent) ifNil: fallbackBlock ]].
	
	^node selector

**Comment by Ducasse** [comment]
Oops it was for Pharo and not Pharo-vcs

**Comment by Ducasse** [comment]
There is a pull request in ligit2-pharo-bindings.

**Comment by guillep** [comment]
It's integrated in libgit 1.5.1, integrated in iceberg in 1066e8446addcb428d5e0fe8bce76cda55bdc6c4.

It'll come with iceberg 1.2.2 this afternoon.
