### ISSUE TITLE
migration tool fails to migrate a package with just extensions

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/iceberg#992]
Since in that case snapshot will not have a class organisation definition, it will raise a DNU.

**Comment by guillep** [comment]
Some more digging into it.
This seems to happen with repositories written in old versions of filetree, that do not contain the categories file in the package metadata.
For example, this seaside package shows the problem:

https://github.com/SeasideSt/Seaside/tree/master/repository/Seaside-GemStone240-Flow.package/monticello.meta
